# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Synchronous TikHub client.

Resource attributes are wired up in ``__init__`` - one per OpenAPI tag.
Method signatures match ``AsyncTikHub`` apart from ``async``/``await``.
"""

from __future__ import annotations

import httpx

from tikhub._base_client import DEFAULT_TIMEOUT, BaseClient
from tikhub.resources.bilibili_app import BilibiliApp
from tikhub.resources.bilibili_web import BilibiliWeb
from tikhub.resources.demo import Demo
from tikhub.resources.douyin_app_v3 import DouyinAppV3
from tikhub.resources.douyin_billboard import DouyinBillboard
from tikhub.resources.douyin_creator import DouyinCreator
from tikhub.resources.douyin_creator_v2 import DouyinCreatorV2
from tikhub.resources.douyin_index import DouyinIndex
from tikhub.resources.douyin_search import DouyinSearch
from tikhub.resources.douyin_web import DouyinWeb
from tikhub.resources.douyin_xingtu import DouyinXingtu
from tikhub.resources.douyin_xingtu_v2 import DouyinXingtuV2
from tikhub.resources.health_check import HealthCheck
from tikhub.resources.hybrid_parsing import HybridParsing
from tikhub.resources.instagram_v1 import InstagramV1
from tikhub.resources.instagram_v2 import InstagramV2
from tikhub.resources.instagram_v3 import InstagramV3
from tikhub.resources.ios_shortcut import IosShortcut
from tikhub.resources.kuaishou_app import KuaishouApp
from tikhub.resources.kuaishou_web import KuaishouWeb
from tikhub.resources.lemon8_app import Lemon8App
from tikhub.resources.linkedin_web import LinkedinWeb
from tikhub.resources.linkedin_web_v2 import LinkedinWebV2
from tikhub.resources.pipixia_app import PipixiaApp
from tikhub.resources.reddit_app import RedditApp
from tikhub.resources.sora2 import Sora2
from tikhub.resources.temp_mail import TempMail
from tikhub.resources.threads_web import ThreadsWeb
from tikhub.resources.tikhub_downloader import TikhubDownloader
from tikhub.resources.tikhub_user import TikhubUser
from tikhub.resources.tiktok_ads import TiktokAds
from tikhub.resources.tiktok_analytics import TiktokAnalytics
from tikhub.resources.tiktok_app_v3 import TiktokAppV3
from tikhub.resources.tiktok_creator import TiktokCreator
from tikhub.resources.tiktok_interaction import TiktokInteraction
from tikhub.resources.tiktok_shop_web import TiktokShopWeb
from tikhub.resources.tiktok_web import TiktokWeb
from tikhub.resources.toutiao_app import ToutiaoApp
from tikhub.resources.toutiao_web import ToutiaoWeb
from tikhub.resources.twitter_web import TwitterWeb
from tikhub.resources.wechat_channels import WechatChannels
from tikhub.resources.wechat_media_platform_web import WechatMediaPlatformWeb
from tikhub.resources.weibo_app import WeiboApp
from tikhub.resources.weibo_web import WeiboWeb
from tikhub.resources.weibo_web_v2 import WeiboWebV2
from tikhub.resources.xiaohongshu_app import XiaohongshuApp
from tikhub.resources.xiaohongshu_app_v2 import XiaohongshuAppV2
from tikhub.resources.xiaohongshu_web import XiaohongshuWeb
from tikhub.resources.xiaohongshu_web_v2 import XiaohongshuWebV2
from tikhub.resources.xiaohongshu_web_v3 import XiaohongshuWebV3
from tikhub.resources.xigua_app_v2 import XiguaAppV2
from tikhub.resources.youtube_web import YoutubeWeb
from tikhub.resources.youtube_web_v2 import YoutubeWebV2
from tikhub.resources.zhihu_web import ZhihuWeb

__all__ = ["TikHub"]


class TikHub(BaseClient):
    """Synchronous TikHub API client.

    Example::

        from tikhub import TikHub

        with TikHub(api_key="YOUR_API_KEY") as client:
            video = client.douyin_web.fetch_one_video(aweme_id="...")
            print(video)

    The constructor reads ``$TIKHUB_API_KEY`` if ``api_key`` is omitted.
    """

    def __init__(
        self,
        api_key: str | None = None,
        *,
        timeout: float | None = DEFAULT_TIMEOUT,
        base_url: str | None = None,
        max_retries: int = 3,
        proxy: str | None = None,
        user_agent: str | None = None,
        parse_response: bool = True,
        http_client: httpx.Client | None = None,
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        super().__init__(
            api_key,
            timeout=timeout,
            base_url=base_url,
            max_retries=max_retries,
            proxy=proxy,
            user_agent=user_agent,
            parse_response=parse_response,
            http_client=http_client,
            transport=transport,
        )

        # ----- Resources (one attribute per OpenAPI tag) ------------------
        self.bilibili_app: BilibiliApp = BilibiliApp(self)
        self.bilibili_web: BilibiliWeb = BilibiliWeb(self)
        self.demo: Demo = Demo(self)
        self.douyin_app_v3: DouyinAppV3 = DouyinAppV3(self)
        self.douyin_billboard: DouyinBillboard = DouyinBillboard(self)
        self.douyin_creator: DouyinCreator = DouyinCreator(self)
        self.douyin_creator_v2: DouyinCreatorV2 = DouyinCreatorV2(self)
        self.douyin_index: DouyinIndex = DouyinIndex(self)
        self.douyin_search: DouyinSearch = DouyinSearch(self)
        self.douyin_web: DouyinWeb = DouyinWeb(self)
        self.douyin_xingtu: DouyinXingtu = DouyinXingtu(self)
        self.douyin_xingtu_v2: DouyinXingtuV2 = DouyinXingtuV2(self)
        self.health_check: HealthCheck = HealthCheck(self)
        self.hybrid_parsing: HybridParsing = HybridParsing(self)
        self.instagram_v1: InstagramV1 = InstagramV1(self)
        self.instagram_v2: InstagramV2 = InstagramV2(self)
        self.instagram_v3: InstagramV3 = InstagramV3(self)
        self.ios_shortcut: IosShortcut = IosShortcut(self)
        self.kuaishou_app: KuaishouApp = KuaishouApp(self)
        self.kuaishou_web: KuaishouWeb = KuaishouWeb(self)
        self.lemon8_app: Lemon8App = Lemon8App(self)
        self.linkedin_web: LinkedinWeb = LinkedinWeb(self)
        self.linkedin_web_v2: LinkedinWebV2 = LinkedinWebV2(self)
        self.pipixia_app: PipixiaApp = PipixiaApp(self)
        self.reddit_app: RedditApp = RedditApp(self)
        self.sora2: Sora2 = Sora2(self)
        self.temp_mail: TempMail = TempMail(self)
        self.threads_web: ThreadsWeb = ThreadsWeb(self)
        self.tikhub_downloader: TikhubDownloader = TikhubDownloader(self)
        self.tikhub_user: TikhubUser = TikhubUser(self)
        self.tiktok_ads: TiktokAds = TiktokAds(self)
        self.tiktok_analytics: TiktokAnalytics = TiktokAnalytics(self)
        self.tiktok_app_v3: TiktokAppV3 = TiktokAppV3(self)
        self.tiktok_creator: TiktokCreator = TiktokCreator(self)
        self.tiktok_interaction: TiktokInteraction = TiktokInteraction(self)
        self.tiktok_shop_web: TiktokShopWeb = TiktokShopWeb(self)
        self.tiktok_web: TiktokWeb = TiktokWeb(self)
        self.toutiao_app: ToutiaoApp = ToutiaoApp(self)
        self.toutiao_web: ToutiaoWeb = ToutiaoWeb(self)
        self.twitter_web: TwitterWeb = TwitterWeb(self)
        self.wechat_channels: WechatChannels = WechatChannels(self)
        self.wechat_media_platform_web: WechatMediaPlatformWeb = WechatMediaPlatformWeb(self)
        self.weibo_app: WeiboApp = WeiboApp(self)
        self.weibo_web: WeiboWeb = WeiboWeb(self)
        self.weibo_web_v2: WeiboWebV2 = WeiboWebV2(self)
        self.xiaohongshu_app: XiaohongshuApp = XiaohongshuApp(self)
        self.xiaohongshu_app_v2: XiaohongshuAppV2 = XiaohongshuAppV2(self)
        self.xiaohongshu_web: XiaohongshuWeb = XiaohongshuWeb(self)
        self.xiaohongshu_web_v2: XiaohongshuWebV2 = XiaohongshuWebV2(self)
        self.xiaohongshu_web_v3: XiaohongshuWebV3 = XiaohongshuWebV3(self)
        self.xigua_app_v2: XiguaAppV2 = XiguaAppV2(self)
        self.youtube_web: YoutubeWeb = YoutubeWeb(self)
        self.youtube_web_v2: YoutubeWebV2 = YoutubeWebV2(self)
        self.zhihu_web: ZhihuWeb = ZhihuWeb(self)

    def __repr__(self) -> str:
        return f"TikHub(base_url={self._base_url!r})"
