# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Douyin-Web-API resource.

OpenAPI tag: ``Douyin-Web-API``
SDK attribute: ``client.douyin_web`` / ``async_client.douyin_web``

Endpoints: 68
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncDouyinWeb", "DouyinWeb"]


class DouyinWeb(SyncResource):
    """Sync ``Douyin-Web-API`` resource (68 endpoints)."""

    def fetch_one_video(
        self,
        *,
        aweme_id: str,
        need_anchor_info: bool | None = None,
    ) -> Any:
        """获取单个作品数据/Get single video data

        ``GET /api/v1/douyin/web/fetch_one_video``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "need_anchor_info": need_anchor_info,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_one_video", params=params)

    def fetch_one_video_v2(
        self,
        *,
        aweme_id: str,
    ) -> Any:
        """获取单个作品数据 V2/Get single video data V2

        ``GET /api/v1/douyin/web/fetch_one_video_v2``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_one_video_v2", params=params)

    def fetch_one_video_by_share_url(
        self,
        *,
        share_url: str,
    ) -> Any:
        """根据分享链接获取单个作品数据/Get single video data by sharing link

        ``GET /api/v1/douyin/web/fetch_one_video_by_share_url``
        """
        params = _drop_none({
            "share_url": share_url,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_one_video_by_share_url", params=params)

    def fetch_video_high_quality_play_url(
        self,
        *,
        aweme_id: str | None = None,
        share_url: str | None = None,
        region: str | None = None,
    ) -> Any:
        """获取视频的最高画质播放链接/Get the highest quality play URL of the video

        ``GET /api/v1/douyin/web/fetch_video_high_quality_play_url``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "share_url": share_url,
            "region": region,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_video_high_quality_play_url", params=params)

    def fetch_multi_video_high_quality_play_url(
        self,
        *,
        aweme_ids: str | None = None,
        region: Any | None = None,
    ) -> Any:
        """批量获取视频的最高画质播放链接/Batch get the highest quality play URL of videos

        ``POST /api/v1/douyin/web/fetch_multi_video_high_quality_play_url``
        """
        json_body = _drop_none({
            "aweme_ids": aweme_ids,
            "region": region,
        })
        return self._client._request("POST", "/api/v1/douyin/web/fetch_multi_video_high_quality_play_url", json=json_body)

    def fetch_multi_video(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """批量获取视频信息/Batch Get Video Information

        ``POST /api/v1/douyin/web/fetch_multi_video``
        """
        json_body = body
        return self._client._request("POST", "/api/v1/douyin/web/fetch_multi_video", json=json_body)

    def fetch_one_video_danmaku(
        self,
        *,
        item_id: str,
        duration: int,
        end_time: int,
        start_time: int,
    ) -> Any:
        """获取单个作品视频弹幕数据/Get single video danmaku data

        ``GET /api/v1/douyin/web/fetch_one_video_danmaku``
        """
        params = _drop_none({
            "item_id": item_id,
            "duration": duration,
            "end_time": end_time,
            "start_time": start_time,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_one_video_danmaku", params=params)

    def fetch_home_feed(
        self,
        *,
        count: int | None = None,
        refresh_index: int | None = None,
    ) -> Any:
        """获取首页推荐数据/Get home feed data

        ``GET /api/v1/douyin/web/fetch_home_feed``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_home_feed", params=params)

    def fetch_related_posts(
        self,
        *,
        aweme_id: str,
        refresh_index: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取相关作品推荐数据/Get related posts recommendation data

        ``GET /api/v1/douyin/web/fetch_related_posts``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "refresh_index": refresh_index,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_related_posts", params=params)

    def fetch_user_post_videos(
        self,
        *,
        sec_user_id: str,
        max_cursor: str | None = None,
        count: int | None = None,
        filter_type: str | None = None,
        cookie: str | None = None,
    ) -> Any:
        """获取用户主页作品数据/Get user homepage video data

        ``GET /api/v1/douyin/web/fetch_user_post_videos``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "max_cursor": max_cursor,
            "count": count,
            "filter_type": filter_type,
            "cookie": cookie,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_post_videos", params=params)

    def fetch_user_like_videos(
        self,
        *,
        sec_user_id: str,
        max_cursor: int | None = None,
        counts: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """获取用户喜欢作品数据/Get user like video data

        ``POST /api/v1/douyin/web/fetch_user_like_videos``
        """
        json_body = _drop_none({
            "sec_user_id": sec_user_id,
            "max_cursor": max_cursor,
            "counts": counts,
            "cookie": cookie,
        })
        return self._client._request("POST", "/api/v1/douyin/web/fetch_user_like_videos", json=json_body)

    def fetch_user_collection_videos(
        self,
        *,
        cookie: str,
        max_cursor: int | None = None,
        counts: int | None = None,
    ) -> Any:
        """获取用户收藏作品数据/Get user collection video data

        ``POST /api/v1/douyin/web/fetch_user_collection_videos``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "max_cursor": max_cursor,
            "counts": counts,
        })
        return self._client._request("POST", "/api/v1/douyin/web/fetch_user_collection_videos", json=json_body)

    def fetch_user_collects(
        self,
        *,
        cookie: str,
        max_cursor: int | None = None,
        counts: int | None = None,
    ) -> Any:
        """获取用户收藏夹/Get user collection

        ``POST /api/v1/douyin/web/fetch_user_collects``
        """
        json_body = _drop_none({
            "max_cursor": max_cursor,
            "counts": counts,
            "cookie": cookie,
        })
        return self._client._request("POST", "/api/v1/douyin/web/fetch_user_collects", json=json_body)

    def fetch_user_collects_videos(
        self,
        *,
        collects_id: str,
        max_cursor: int | None = None,
        counts: int | None = None,
    ) -> Any:
        """获取用户收藏夹数据/Get user collection data

        ``GET /api/v1/douyin/web/fetch_user_collects_videos``
        """
        params = _drop_none({
            "collects_id": collects_id,
            "max_cursor": max_cursor,
            "counts": counts,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_collects_videos", params=params)

    def fetch_user_mix_videos(
        self,
        *,
        mix_id: str,
        max_cursor: int | None = None,
        counts: int | None = None,
    ) -> Any:
        """获取用户合辑作品数据/Get user mix video data

        ``GET /api/v1/douyin/web/fetch_user_mix_videos``
        """
        params = _drop_none({
            "mix_id": mix_id,
            "max_cursor": max_cursor,
            "counts": counts,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_mix_videos", params=params)

    def fetch_user_live_videos(
        self,
        *,
        webcast_id: str,
    ) -> Any:
        """获取用户直播流数据/Get user live video data

        ``GET /api/v1/douyin/web/fetch_user_live_videos``
        """
        params = _drop_none({
            "webcast_id": webcast_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_live_videos", params=params)

    def fetch_user_live_videos_by_sec_uid(
        self,
        *,
        sec_uid: str,
    ) -> Any:
        """通过sec_uid获取指定用户的直播流数据/Get live video data of specified user by sec_uid

        ``GET /api/v1/douyin/web/fetch_user_live_videos_by_sec_uid``
        """
        params = _drop_none({
            "sec_uid": sec_uid,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_live_videos_by_sec_uid", params=params)

    def fetch_user_live_videos_by_room_id(
        self,
        *,
        room_id: str,
    ) -> Any:
        """通过room_id获取指定用户的直播流数据 V1/Get live video data of specified user by room_id V1

        ``GET /api/v1/douyin/web/fetch_user_live_videos_by_room_id``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        params = _drop_none({
            "room_id": room_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_live_videos_by_room_id", params=params)

    def fetch_user_live_videos_by_room_id_v2(
        self,
        *,
        room_id: str,
    ) -> Any:
        """通过room_id获取指定用户的直播流数据 V2/Gets the live stream data of the specified user by room_id V2

        ``GET /api/v1/douyin/web/fetch_user_live_videos_by_room_id_v2``
        """
        params = _drop_none({
            "room_id": room_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_live_videos_by_room_id_v2", params=params)

    def fetch_live_gift_ranking(
        self,
        *,
        room_id: str,
        rank_type: int | None = None,
    ) -> Any:
        """获取直播间送礼用户排行榜/Get live room gift user ranking

        ``GET /api/v1/douyin/web/fetch_live_gift_ranking``
        """
        params = _drop_none({
            "room_id": room_id,
            "rank_type": rank_type,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_live_gift_ranking", params=params)

    def fetch_live_room_product_result(
        self,
        *,
        room_id: str,
        author_id: str,
        offset: int | None = None,
        limit: int | None = None,
    ) -> Any:
        """抖音直播间商品信息/Douyin live room product information

        ``GET /api/v1/douyin/web/fetch_live_room_product_result``
        """
        params = _drop_none({
            "room_id": room_id,
            "author_id": author_id,
            "offset": offset,
            "limit": limit,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_live_room_product_result", params=params)

    def fetch_product_sku_list(
        self,
        *,
        product_id: str,
        author_id: str,
    ) -> Any:
        """获取商品SKU列表/Get product SKU list

        ``GET /api/v1/douyin/web/fetch_product_sku_list``
        """
        params = _drop_none({
            "product_id": product_id,
            "author_id": author_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_product_sku_list", params=params)

    def fetch_product_coupon(
        self,
        *,
        product_id: str,
        shop_id: str,
        price: str,
        author_id: str,
        sec_user_id: str,
    ) -> Any:
        """获取商品优惠券信息/Get product coupon information

        ``GET /api/v1/douyin/web/fetch_product_coupon``
        """
        params = _drop_none({
            "product_id": product_id,
            "shop_id": shop_id,
            "price": price,
            "author_id": author_id,
            "sec_user_id": sec_user_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_product_coupon", params=params)

    def fetch_product_review_score(
        self,
        *,
        product_id: str,
        shop_id: str,
    ) -> Any:
        """获取商品评价评分/Get product review score

        ``GET /api/v1/douyin/web/fetch_product_review_score``
        """
        params = _drop_none({
            "product_id": product_id,
            "shop_id": shop_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_product_review_score", params=params)

    def fetch_product_review_list(
        self,
        *,
        product_id: str,
        shop_id: str,
        cursor: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
    ) -> Any:
        """获取商品评价列表/Get product review list

        ``GET /api/v1/douyin/web/fetch_product_review_list``
        """
        params = _drop_none({
            "product_id": product_id,
            "shop_id": shop_id,
            "cursor": cursor,
            "count": count,
            "sort_type": sort_type,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_product_review_list", params=params)

    def fetch_user_profile_by_uid(
        self,
        *,
        uid: str,
    ) -> Any:
        """使用UID获取用户信息/Get user information by UID

        ``GET /api/v1/douyin/web/fetch_user_profile_by_uid``
        """
        params = _drop_none({
            "uid": uid,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_profile_by_uid", params=params)

    def fetch_batch_user_profile_v1(
        self,
        *,
        sec_user_ids: str,
    ) -> Any:
        """获取批量用户信息(最多10个)/Get batch user profile (up to 10)

        ``GET /api/v1/douyin/web/fetch_batch_user_profile_v1``
        """
        params = _drop_none({
            "sec_user_ids": sec_user_ids,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_batch_user_profile_v1", params=params)

    def fetch_batch_user_profile_v2(
        self,
        *,
        sec_user_ids: str,
    ) -> Any:
        """获取批量用户信息(最多50个)/Get batch user profile (up to 50)

        ``GET /api/v1/douyin/web/fetch_batch_user_profile_v2``
        """
        params = _drop_none({
            "sec_user_ids": sec_user_ids,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_batch_user_profile_v2", params=params)

    def fetch_user_live_info_by_uid(
        self,
        *,
        uid: str,
    ) -> Any:
        """使用UID获取用户开播信息/Get user live information by UID

        ``GET /api/v1/douyin/web/fetch_user_live_info_by_uid``
        """
        params = _drop_none({
            "uid": uid,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_live_info_by_uid", params=params)

    def fetch_user_profile_by_short_id(
        self,
        *,
        short_id: str,
    ) -> Any:
        """使用Short ID获取用户信息/Get user information by Short ID

        ``GET /api/v1/douyin/web/fetch_user_profile_by_short_id``
        """
        params = _drop_none({
            "short_id": short_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_profile_by_short_id", params=params)

    def handler_shorten_url(
        self,
        *,
        target_url: str,
    ) -> Any:
        """生成短链接

        ``GET /api/v1/douyin/web/handler_shorten_url``
        """
        params = _drop_none({
            "target_url": target_url,
        })
        return self._client._request("GET", "/api/v1/douyin/web/handler_shorten_url", params=params)

    def handler_user_profile(
        self,
        *,
        sec_user_id: str,
    ) -> Any:
        """使用sec_user_id获取指定用户的信息/Get information of specified user by sec_user_id

        ``GET /api/v1/douyin/web/handler_user_profile``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/handler_user_profile", params=params)

    def handler_user_profile_v2(
        self,
        *,
        unique_id: str,
    ) -> Any:
        """使用unique_id（抖音号）获取指定用户的信息/Get information of specified user by unique_id

        ``GET /api/v1/douyin/web/handler_user_profile_v2``
        """
        params = _drop_none({
            "unique_id": unique_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/handler_user_profile_v2", params=params)

    def encrypt_uid_to_sec_user_id(
        self,
        *,
        uid: str,
    ) -> Any:
        """加密用户uid到sec_user_id/Encrypt user uid to sec_user_id

        ``GET /api/v1/douyin/web/encrypt_uid_to_sec_user_id``
        """
        params = _drop_none({
            "uid": uid,
        })
        return self._client._request("GET", "/api/v1/douyin/web/encrypt_uid_to_sec_user_id", params=params)

    def handler_user_profile_v3(
        self,
        *,
        uid: str,
    ) -> Any:
        """根据抖音uid获取指定用户的信息/Get information of specified user by uid

        ``GET /api/v1/douyin/web/handler_user_profile_v3``
        """
        params = _drop_none({
            "uid": uid,
        })
        return self._client._request("GET", "/api/v1/douyin/web/handler_user_profile_v3", params=params)

    def handler_user_profile_v4(
        self,
        *,
        sec_user_id: str,
    ) -> Any:
        """根据sec_user_id获取指定用户的信息（性别，年龄，直播等级、牌子）/Get information of specified user by sec_user_id (gender, age, live level、brand)

        ``GET /api/v1/douyin/web/handler_user_profile_v4``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/handler_user_profile_v4", params=params)

    def fetch_user_fans_list(
        self,
        *,
        sec_user_id: str | None = None,
        max_time: str | None = None,
        count: int | None = None,
        source_type: int | None = None,
    ) -> Any:
        """获取用户粉丝列表/Get user fans list

        ``GET /api/v1/douyin/web/fetch_user_fans_list``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "max_time": max_time,
            "count": count,
            "source_type": source_type,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_fans_list", params=params)

    def fetch_user_following_list(
        self,
        *,
        sec_user_id: str | None = None,
        max_time: str | None = None,
        count: int | None = None,
        source_type: int | None = None,
    ) -> Any:
        """获取用户关注列表/Get user following list

        ``GET /api/v1/douyin/web/fetch_user_following_list``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "max_time": max_time,
            "count": count,
            "source_type": source_type,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_following_list", params=params)

    def fetch_video_comments(
        self,
        *,
        aweme_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取单个视频评论数据/Get single video comments data

        ``GET /api/v1/douyin/web/fetch_video_comments``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "cursor": cursor,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_video_comments", params=params)

    def fetch_video_comment_replies(
        self,
        *,
        item_id: str,
        comment_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取指定视频的评论回复数据/Get comment replies data of specified video

        ``GET /api/v1/douyin/web/fetch_video_comment_replies``
        """
        params = _drop_none({
            "item_id": item_id,
            "comment_id": comment_id,
            "cursor": cursor,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_video_comment_replies", params=params)

    def fetch_user_search_result_v3(
        self,
        *,
        keyword: str,
        cursor: str | None = None,
        douyin_user_type: str | None = None,
        douyin_user_fans: str | None = None,
    ) -> Any:
        """获取指定关键词的用户搜索结果 V3 (已弃用，替代接口请参考下方文档)/Get user search results of specified keywords V3 (deprecated, please refer to the following document for replacement interface)

        ``GET /api/v1/douyin/web/fetch_user_search_result_v3``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        params = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "douyin_user_type": douyin_user_type,
            "douyin_user_fans": douyin_user_fans,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_user_search_result_v3", params=params)

    def fetch_challenge_posts(
        self,
        *,
        challenge_id: str | None = None,
        sort_type: int | None = None,
        cursor: int | None = None,
        count: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """话题作品/Challenge Posts

        ``POST /api/v1/douyin/web/fetch_challenge_posts``
        """
        json_body = _drop_none({
            "challenge_id": challenge_id,
            "sort_type": sort_type,
            "cursor": cursor,
            "count": count,
            "cookie": cookie,
        })
        return self._client._request("POST", "/api/v1/douyin/web/fetch_challenge_posts", json=json_body)

    def fetch_hot_search_result(
        self,
    ) -> Any:
        """获取抖音热榜数据/Get Douyin hot search results

        ``GET /api/v1/douyin/web/fetch_hot_search_result``
        """
        return self._client._request("GET", "/api/v1/douyin/web/fetch_hot_search_result")

    def fetch_video_channel_result(
        self,
        *,
        tag_id: int,
        count: int | None = None,
        refresh_index: int | None = None,
    ) -> Any:
        """抖音视频频道数据/Douyin video channel data

        ``GET /api/v1/douyin/web/fetch_video_channel_result``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "count": count,
            "refresh_index": refresh_index,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_video_channel_result", params=params)

    def fetch_douyin_web_guest_cookie(
        self,
        *,
        user_agent: str,
    ) -> Any:
        """获取抖音Web的游客Cookie/Get the guest Cookie of Douyin Web

        ``GET /api/v1/douyin/web/fetch_douyin_web_guest_cookie``
        """
        params = _drop_none({
            "user_agent": user_agent,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_douyin_web_guest_cookie", params=params)

    def generate_real_msToken(
        self,
    ) -> Any:
        """生成真实msToken/Generate real msToken

        ``GET /api/v1/douyin/web/generate_real_msToken``
        """
        return self._client._request("GET", "/api/v1/douyin/web/generate_real_msToken")

    def generate_ttwid(
        self,
        *,
        user_agent: str | None = None,
    ) -> Any:
        """生成ttwid/Generate ttwid

        ``GET /api/v1/douyin/web/generate_ttwid``
        """
        params = _drop_none({
            "user_agent": user_agent,
        })
        return self._client._request("GET", "/api/v1/douyin/web/generate_ttwid", params=params)

    def fetch_query_user(
        self,
        *,
        body: Any = None,
    ) -> Any:
        """查询抖音用户基本信息/Query Douyin user basic information

        ``POST /api/v1/douyin/web/fetch_query_user``
        """
        json_body = body
        return self._client._request("POST", "/api/v1/douyin/web/fetch_query_user", json=json_body)

    def generate_verify_fp(
        self,
    ) -> Any:
        """生成verify_fp/Generate verify_fp

        ``GET /api/v1/douyin/web/generate_verify_fp``
        """
        return self._client._request("GET", "/api/v1/douyin/web/generate_verify_fp")

    def generate_s_v_web_id(
        self,
    ) -> Any:
        """生成s_v_web_id/Generate s_v_web_id

        ``GET /api/v1/douyin/web/generate_s_v_web_id``
        """
        return self._client._request("GET", "/api/v1/douyin/web/generate_s_v_web_id")

    def generate_wss_xb_signature(
        self,
        *,
        user_agent: str,
        room_id: str,
        user_unique_id: str,
    ) -> Any:
        """生成弹幕xb签名/Generate barrage xb signature

        ``GET /api/v1/douyin/web/generate_wss_xb_signature``
        """
        params = _drop_none({
            "user_agent": user_agent,
            "room_id": room_id,
            "user_unique_id": user_unique_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/generate_wss_xb_signature", params=params)

    def generate_x_bogus(
        self,
        *,
        url: str,
        user_agent: str,
    ) -> Any:
        """使用接口网址生成X-Bogus参数/Generate X-Bogus parameter using API URL

        ``POST /api/v1/douyin/web/generate_x_bogus``
        """
        json_body = _drop_none({
            "url": url,
            "user_agent": user_agent,
        })
        return self._client._request("POST", "/api/v1/douyin/web/generate_x_bogus", json=json_body)

    def generate_a_bogus(
        self,
        *,
        url: str,
        data: str,
        user_agent: str,
        index_0: int | None = None,
        index_1: int | None = None,
        index_2: int | None = None,
    ) -> Any:
        """使用接口网址生成A-Bogus参数/Generate A-Bogus parameter using API URL

        ``POST /api/v1/douyin/web/generate_a_bogus``
        """
        json_body = _drop_none({
            "url": url,
            "data": data,
            "user_agent": user_agent,
            "index_0": index_0,
            "index_1": index_1,
            "index_2": index_2,
        })
        return self._client._request("POST", "/api/v1/douyin/web/generate_a_bogus", json=json_body)

    def get_sec_user_id(
        self,
        *,
        url: str,
    ) -> Any:
        """提取单个用户id/Extract single user id

        ``GET /api/v1/douyin/web/get_sec_user_id``
        """
        params = _drop_none({
            "url": url,
        })
        return self._client._request("GET", "/api/v1/douyin/web/get_sec_user_id", params=params)

    def get_all_sec_user_id(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """提取列表用户id/Extract list user id

        ``POST /api/v1/douyin/web/get_all_sec_user_id``
        """
        json_body = body
        return self._client._request("POST", "/api/v1/douyin/web/get_all_sec_user_id", json=json_body)

    def get_aweme_id(
        self,
        *,
        url: str,
    ) -> Any:
        """提取单个作品id/Extract single video id

        ``GET /api/v1/douyin/web/get_aweme_id``
        """
        params = _drop_none({
            "url": url,
        })
        return self._client._request("GET", "/api/v1/douyin/web/get_aweme_id", params=params)

    def get_all_aweme_id(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """提取列表作品id/Extract list video id

        ``POST /api/v1/douyin/web/get_all_aweme_id``
        """
        json_body = body
        return self._client._request("POST", "/api/v1/douyin/web/get_all_aweme_id", json=json_body)

    def get_webcast_id(
        self,
        *,
        url: str,
    ) -> Any:
        """提取直播间号/Extract webcast id

        ``GET /api/v1/douyin/web/get_webcast_id``
        """
        params = _drop_none({
            "url": url,
        })
        return self._client._request("GET", "/api/v1/douyin/web/get_webcast_id", params=params)

    def get_all_webcast_id(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """提取列表直播间号/Extract list webcast id

        ``POST /api/v1/douyin/web/get_all_webcast_id``
        """
        json_body = body
        return self._client._request("POST", "/api/v1/douyin/web/get_all_webcast_id", json=json_body)

    def webcast_id_2_room_id(
        self,
        *,
        webcast_id: str,
    ) -> Any:
        """直播间号转房间号/Webcast id to room id

        ``GET /api/v1/douyin/web/webcast_id_2_room_id``
        """
        params = _drop_none({
            "webcast_id": webcast_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/webcast_id_2_room_id", params=params)

    def douyin_live_room(
        self,
        *,
        live_room_url: str,
        danmaku_type: str,
    ) -> Any:
        """提取直播间弹幕/Extract live room danmaku

        ``GET /api/v1/douyin/web/douyin_live_room``
        """
        params = _drop_none({
            "live_room_url": live_room_url,
            "danmaku_type": danmaku_type,
        })
        return self._client._request("GET", "/api/v1/douyin/web/douyin_live_room", params=params)

    def fetch_live_im_fetch(
        self,
        *,
        room_id: str,
        user_unique_id: str,
    ) -> Any:
        """抖音直播间弹幕参数获取/Douyin live room danmaku parameters

        ``GET /api/v1/douyin/web/fetch_live_im_fetch``
        """
        params = _drop_none({
            "room_id": room_id,
            "user_unique_id": user_unique_id,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_live_im_fetch", params=params)

    def fetch_series_aweme(
        self,
        *,
        offset: int,
        count: int,
        content_type: int,
        cookie: str | None = None,
    ) -> Any:
        """短剧作品/Series Video

        ``GET /api/v1/douyin/web/fetch_series_aweme``
        """
        params = _drop_none({
            "offset": offset,
            "count": count,
            "content_type": content_type,
            "cookie": cookie,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_series_aweme", params=params)

    def fetch_knowledge_aweme(
        self,
        *,
        count: int,
        refresh_index: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """知识作品推荐/Knowledge Video

        ``GET /api/v1/douyin/web/fetch_knowledge_aweme``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
            "cookie": cookie,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_knowledge_aweme", params=params)

    def fetch_game_aweme(
        self,
        *,
        count: int,
        refresh_index: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """游戏作品推荐/Game Video

        ``GET /api/v1/douyin/web/fetch_game_aweme``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
            "cookie": cookie,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_game_aweme", params=params)

    def fetch_cartoon_aweme(
        self,
        *,
        count: int,
        refresh_index: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """二次元作品推荐/Anime Video

        ``GET /api/v1/douyin/web/fetch_cartoon_aweme``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
            "cookie": cookie,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_cartoon_aweme", params=params)

    def fetch_music_aweme(
        self,
        *,
        count: int,
        refresh_index: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """音乐作品推荐/Music Video

        ``GET /api/v1/douyin/web/fetch_music_aweme``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
            "cookie": cookie,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_music_aweme", params=params)

    def fetch_food_aweme(
        self,
        *,
        count: int,
        refresh_index: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """美食作品推荐/Food Video

        ``GET /api/v1/douyin/web/fetch_food_aweme``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
            "cookie": cookie,
        })
        return self._client._request("GET", "/api/v1/douyin/web/fetch_food_aweme", params=params)


class AsyncDouyinWeb(AsyncResource):
    """Async ``Douyin-Web-API`` resource (68 endpoints)."""

    async def fetch_one_video(
        self,
        *,
        aweme_id: str,
        need_anchor_info: bool | None = None,
    ) -> Any:
        """获取单个作品数据/Get single video data

        ``GET /api/v1/douyin/web/fetch_one_video``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "need_anchor_info": need_anchor_info,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_one_video", params=params)

    async def fetch_one_video_v2(
        self,
        *,
        aweme_id: str,
    ) -> Any:
        """获取单个作品数据 V2/Get single video data V2

        ``GET /api/v1/douyin/web/fetch_one_video_v2``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_one_video_v2", params=params)

    async def fetch_one_video_by_share_url(
        self,
        *,
        share_url: str,
    ) -> Any:
        """根据分享链接获取单个作品数据/Get single video data by sharing link

        ``GET /api/v1/douyin/web/fetch_one_video_by_share_url``
        """
        params = _drop_none({
            "share_url": share_url,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_one_video_by_share_url", params=params)

    async def fetch_video_high_quality_play_url(
        self,
        *,
        aweme_id: str | None = None,
        share_url: str | None = None,
        region: str | None = None,
    ) -> Any:
        """获取视频的最高画质播放链接/Get the highest quality play URL of the video

        ``GET /api/v1/douyin/web/fetch_video_high_quality_play_url``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "share_url": share_url,
            "region": region,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_video_high_quality_play_url", params=params)

    async def fetch_multi_video_high_quality_play_url(
        self,
        *,
        aweme_ids: str | None = None,
        region: Any | None = None,
    ) -> Any:
        """批量获取视频的最高画质播放链接/Batch get the highest quality play URL of videos

        ``POST /api/v1/douyin/web/fetch_multi_video_high_quality_play_url``
        """
        json_body = _drop_none({
            "aweme_ids": aweme_ids,
            "region": region,
        })
        return await self._client._request("POST", "/api/v1/douyin/web/fetch_multi_video_high_quality_play_url", json=json_body)

    async def fetch_multi_video(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """批量获取视频信息/Batch Get Video Information

        ``POST /api/v1/douyin/web/fetch_multi_video``
        """
        json_body = body
        return await self._client._request("POST", "/api/v1/douyin/web/fetch_multi_video", json=json_body)

    async def fetch_one_video_danmaku(
        self,
        *,
        item_id: str,
        duration: int,
        end_time: int,
        start_time: int,
    ) -> Any:
        """获取单个作品视频弹幕数据/Get single video danmaku data

        ``GET /api/v1/douyin/web/fetch_one_video_danmaku``
        """
        params = _drop_none({
            "item_id": item_id,
            "duration": duration,
            "end_time": end_time,
            "start_time": start_time,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_one_video_danmaku", params=params)

    async def fetch_home_feed(
        self,
        *,
        count: int | None = None,
        refresh_index: int | None = None,
    ) -> Any:
        """获取首页推荐数据/Get home feed data

        ``GET /api/v1/douyin/web/fetch_home_feed``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_home_feed", params=params)

    async def fetch_related_posts(
        self,
        *,
        aweme_id: str,
        refresh_index: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取相关作品推荐数据/Get related posts recommendation data

        ``GET /api/v1/douyin/web/fetch_related_posts``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "refresh_index": refresh_index,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_related_posts", params=params)

    async def fetch_user_post_videos(
        self,
        *,
        sec_user_id: str,
        max_cursor: str | None = None,
        count: int | None = None,
        filter_type: str | None = None,
        cookie: str | None = None,
    ) -> Any:
        """获取用户主页作品数据/Get user homepage video data

        ``GET /api/v1/douyin/web/fetch_user_post_videos``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "max_cursor": max_cursor,
            "count": count,
            "filter_type": filter_type,
            "cookie": cookie,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_post_videos", params=params)

    async def fetch_user_like_videos(
        self,
        *,
        sec_user_id: str,
        max_cursor: int | None = None,
        counts: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """获取用户喜欢作品数据/Get user like video data

        ``POST /api/v1/douyin/web/fetch_user_like_videos``
        """
        json_body = _drop_none({
            "sec_user_id": sec_user_id,
            "max_cursor": max_cursor,
            "counts": counts,
            "cookie": cookie,
        })
        return await self._client._request("POST", "/api/v1/douyin/web/fetch_user_like_videos", json=json_body)

    async def fetch_user_collection_videos(
        self,
        *,
        cookie: str,
        max_cursor: int | None = None,
        counts: int | None = None,
    ) -> Any:
        """获取用户收藏作品数据/Get user collection video data

        ``POST /api/v1/douyin/web/fetch_user_collection_videos``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "max_cursor": max_cursor,
            "counts": counts,
        })
        return await self._client._request("POST", "/api/v1/douyin/web/fetch_user_collection_videos", json=json_body)

    async def fetch_user_collects(
        self,
        *,
        cookie: str,
        max_cursor: int | None = None,
        counts: int | None = None,
    ) -> Any:
        """获取用户收藏夹/Get user collection

        ``POST /api/v1/douyin/web/fetch_user_collects``
        """
        json_body = _drop_none({
            "max_cursor": max_cursor,
            "counts": counts,
            "cookie": cookie,
        })
        return await self._client._request("POST", "/api/v1/douyin/web/fetch_user_collects", json=json_body)

    async def fetch_user_collects_videos(
        self,
        *,
        collects_id: str,
        max_cursor: int | None = None,
        counts: int | None = None,
    ) -> Any:
        """获取用户收藏夹数据/Get user collection data

        ``GET /api/v1/douyin/web/fetch_user_collects_videos``
        """
        params = _drop_none({
            "collects_id": collects_id,
            "max_cursor": max_cursor,
            "counts": counts,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_collects_videos", params=params)

    async def fetch_user_mix_videos(
        self,
        *,
        mix_id: str,
        max_cursor: int | None = None,
        counts: int | None = None,
    ) -> Any:
        """获取用户合辑作品数据/Get user mix video data

        ``GET /api/v1/douyin/web/fetch_user_mix_videos``
        """
        params = _drop_none({
            "mix_id": mix_id,
            "max_cursor": max_cursor,
            "counts": counts,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_mix_videos", params=params)

    async def fetch_user_live_videos(
        self,
        *,
        webcast_id: str,
    ) -> Any:
        """获取用户直播流数据/Get user live video data

        ``GET /api/v1/douyin/web/fetch_user_live_videos``
        """
        params = _drop_none({
            "webcast_id": webcast_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_live_videos", params=params)

    async def fetch_user_live_videos_by_sec_uid(
        self,
        *,
        sec_uid: str,
    ) -> Any:
        """通过sec_uid获取指定用户的直播流数据/Get live video data of specified user by sec_uid

        ``GET /api/v1/douyin/web/fetch_user_live_videos_by_sec_uid``
        """
        params = _drop_none({
            "sec_uid": sec_uid,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_live_videos_by_sec_uid", params=params)

    async def fetch_user_live_videos_by_room_id(
        self,
        *,
        room_id: str,
    ) -> Any:
        """通过room_id获取指定用户的直播流数据 V1/Get live video data of specified user by room_id V1

        ``GET /api/v1/douyin/web/fetch_user_live_videos_by_room_id``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        params = _drop_none({
            "room_id": room_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_live_videos_by_room_id", params=params)

    async def fetch_user_live_videos_by_room_id_v2(
        self,
        *,
        room_id: str,
    ) -> Any:
        """通过room_id获取指定用户的直播流数据 V2/Gets the live stream data of the specified user by room_id V2

        ``GET /api/v1/douyin/web/fetch_user_live_videos_by_room_id_v2``
        """
        params = _drop_none({
            "room_id": room_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_live_videos_by_room_id_v2", params=params)

    async def fetch_live_gift_ranking(
        self,
        *,
        room_id: str,
        rank_type: int | None = None,
    ) -> Any:
        """获取直播间送礼用户排行榜/Get live room gift user ranking

        ``GET /api/v1/douyin/web/fetch_live_gift_ranking``
        """
        params = _drop_none({
            "room_id": room_id,
            "rank_type": rank_type,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_live_gift_ranking", params=params)

    async def fetch_live_room_product_result(
        self,
        *,
        room_id: str,
        author_id: str,
        offset: int | None = None,
        limit: int | None = None,
    ) -> Any:
        """抖音直播间商品信息/Douyin live room product information

        ``GET /api/v1/douyin/web/fetch_live_room_product_result``
        """
        params = _drop_none({
            "room_id": room_id,
            "author_id": author_id,
            "offset": offset,
            "limit": limit,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_live_room_product_result", params=params)

    async def fetch_product_sku_list(
        self,
        *,
        product_id: str,
        author_id: str,
    ) -> Any:
        """获取商品SKU列表/Get product SKU list

        ``GET /api/v1/douyin/web/fetch_product_sku_list``
        """
        params = _drop_none({
            "product_id": product_id,
            "author_id": author_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_product_sku_list", params=params)

    async def fetch_product_coupon(
        self,
        *,
        product_id: str,
        shop_id: str,
        price: str,
        author_id: str,
        sec_user_id: str,
    ) -> Any:
        """获取商品优惠券信息/Get product coupon information

        ``GET /api/v1/douyin/web/fetch_product_coupon``
        """
        params = _drop_none({
            "product_id": product_id,
            "shop_id": shop_id,
            "price": price,
            "author_id": author_id,
            "sec_user_id": sec_user_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_product_coupon", params=params)

    async def fetch_product_review_score(
        self,
        *,
        product_id: str,
        shop_id: str,
    ) -> Any:
        """获取商品评价评分/Get product review score

        ``GET /api/v1/douyin/web/fetch_product_review_score``
        """
        params = _drop_none({
            "product_id": product_id,
            "shop_id": shop_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_product_review_score", params=params)

    async def fetch_product_review_list(
        self,
        *,
        product_id: str,
        shop_id: str,
        cursor: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
    ) -> Any:
        """获取商品评价列表/Get product review list

        ``GET /api/v1/douyin/web/fetch_product_review_list``
        """
        params = _drop_none({
            "product_id": product_id,
            "shop_id": shop_id,
            "cursor": cursor,
            "count": count,
            "sort_type": sort_type,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_product_review_list", params=params)

    async def fetch_user_profile_by_uid(
        self,
        *,
        uid: str,
    ) -> Any:
        """使用UID获取用户信息/Get user information by UID

        ``GET /api/v1/douyin/web/fetch_user_profile_by_uid``
        """
        params = _drop_none({
            "uid": uid,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_profile_by_uid", params=params)

    async def fetch_batch_user_profile_v1(
        self,
        *,
        sec_user_ids: str,
    ) -> Any:
        """获取批量用户信息(最多10个)/Get batch user profile (up to 10)

        ``GET /api/v1/douyin/web/fetch_batch_user_profile_v1``
        """
        params = _drop_none({
            "sec_user_ids": sec_user_ids,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_batch_user_profile_v1", params=params)

    async def fetch_batch_user_profile_v2(
        self,
        *,
        sec_user_ids: str,
    ) -> Any:
        """获取批量用户信息(最多50个)/Get batch user profile (up to 50)

        ``GET /api/v1/douyin/web/fetch_batch_user_profile_v2``
        """
        params = _drop_none({
            "sec_user_ids": sec_user_ids,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_batch_user_profile_v2", params=params)

    async def fetch_user_live_info_by_uid(
        self,
        *,
        uid: str,
    ) -> Any:
        """使用UID获取用户开播信息/Get user live information by UID

        ``GET /api/v1/douyin/web/fetch_user_live_info_by_uid``
        """
        params = _drop_none({
            "uid": uid,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_live_info_by_uid", params=params)

    async def fetch_user_profile_by_short_id(
        self,
        *,
        short_id: str,
    ) -> Any:
        """使用Short ID获取用户信息/Get user information by Short ID

        ``GET /api/v1/douyin/web/fetch_user_profile_by_short_id``
        """
        params = _drop_none({
            "short_id": short_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_profile_by_short_id", params=params)

    async def handler_shorten_url(
        self,
        *,
        target_url: str,
    ) -> Any:
        """生成短链接

        ``GET /api/v1/douyin/web/handler_shorten_url``
        """
        params = _drop_none({
            "target_url": target_url,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/handler_shorten_url", params=params)

    async def handler_user_profile(
        self,
        *,
        sec_user_id: str,
    ) -> Any:
        """使用sec_user_id获取指定用户的信息/Get information of specified user by sec_user_id

        ``GET /api/v1/douyin/web/handler_user_profile``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/handler_user_profile", params=params)

    async def handler_user_profile_v2(
        self,
        *,
        unique_id: str,
    ) -> Any:
        """使用unique_id（抖音号）获取指定用户的信息/Get information of specified user by unique_id

        ``GET /api/v1/douyin/web/handler_user_profile_v2``
        """
        params = _drop_none({
            "unique_id": unique_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/handler_user_profile_v2", params=params)

    async def encrypt_uid_to_sec_user_id(
        self,
        *,
        uid: str,
    ) -> Any:
        """加密用户uid到sec_user_id/Encrypt user uid to sec_user_id

        ``GET /api/v1/douyin/web/encrypt_uid_to_sec_user_id``
        """
        params = _drop_none({
            "uid": uid,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/encrypt_uid_to_sec_user_id", params=params)

    async def handler_user_profile_v3(
        self,
        *,
        uid: str,
    ) -> Any:
        """根据抖音uid获取指定用户的信息/Get information of specified user by uid

        ``GET /api/v1/douyin/web/handler_user_profile_v3``
        """
        params = _drop_none({
            "uid": uid,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/handler_user_profile_v3", params=params)

    async def handler_user_profile_v4(
        self,
        *,
        sec_user_id: str,
    ) -> Any:
        """根据sec_user_id获取指定用户的信息（性别，年龄，直播等级、牌子）/Get information of specified user by sec_user_id (gender, age, live level、brand)

        ``GET /api/v1/douyin/web/handler_user_profile_v4``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/handler_user_profile_v4", params=params)

    async def fetch_user_fans_list(
        self,
        *,
        sec_user_id: str | None = None,
        max_time: str | None = None,
        count: int | None = None,
        source_type: int | None = None,
    ) -> Any:
        """获取用户粉丝列表/Get user fans list

        ``GET /api/v1/douyin/web/fetch_user_fans_list``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "max_time": max_time,
            "count": count,
            "source_type": source_type,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_fans_list", params=params)

    async def fetch_user_following_list(
        self,
        *,
        sec_user_id: str | None = None,
        max_time: str | None = None,
        count: int | None = None,
        source_type: int | None = None,
    ) -> Any:
        """获取用户关注列表/Get user following list

        ``GET /api/v1/douyin/web/fetch_user_following_list``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "max_time": max_time,
            "count": count,
            "source_type": source_type,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_following_list", params=params)

    async def fetch_video_comments(
        self,
        *,
        aweme_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取单个视频评论数据/Get single video comments data

        ``GET /api/v1/douyin/web/fetch_video_comments``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "cursor": cursor,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_video_comments", params=params)

    async def fetch_video_comment_replies(
        self,
        *,
        item_id: str,
        comment_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取指定视频的评论回复数据/Get comment replies data of specified video

        ``GET /api/v1/douyin/web/fetch_video_comment_replies``
        """
        params = _drop_none({
            "item_id": item_id,
            "comment_id": comment_id,
            "cursor": cursor,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_video_comment_replies", params=params)

    async def fetch_user_search_result_v3(
        self,
        *,
        keyword: str,
        cursor: str | None = None,
        douyin_user_type: str | None = None,
        douyin_user_fans: str | None = None,
    ) -> Any:
        """获取指定关键词的用户搜索结果 V3 (已弃用，替代接口请参考下方文档)/Get user search results of specified keywords V3 (deprecated, please refer to the following document for replacement interface)

        ``GET /api/v1/douyin/web/fetch_user_search_result_v3``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        params = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "douyin_user_type": douyin_user_type,
            "douyin_user_fans": douyin_user_fans,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_user_search_result_v3", params=params)

    async def fetch_challenge_posts(
        self,
        *,
        challenge_id: str | None = None,
        sort_type: int | None = None,
        cursor: int | None = None,
        count: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """话题作品/Challenge Posts

        ``POST /api/v1/douyin/web/fetch_challenge_posts``
        """
        json_body = _drop_none({
            "challenge_id": challenge_id,
            "sort_type": sort_type,
            "cursor": cursor,
            "count": count,
            "cookie": cookie,
        })
        return await self._client._request("POST", "/api/v1/douyin/web/fetch_challenge_posts", json=json_body)

    async def fetch_hot_search_result(
        self,
    ) -> Any:
        """获取抖音热榜数据/Get Douyin hot search results

        ``GET /api/v1/douyin/web/fetch_hot_search_result``
        """
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_hot_search_result")

    async def fetch_video_channel_result(
        self,
        *,
        tag_id: int,
        count: int | None = None,
        refresh_index: int | None = None,
    ) -> Any:
        """抖音视频频道数据/Douyin video channel data

        ``GET /api/v1/douyin/web/fetch_video_channel_result``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "count": count,
            "refresh_index": refresh_index,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_video_channel_result", params=params)

    async def fetch_douyin_web_guest_cookie(
        self,
        *,
        user_agent: str,
    ) -> Any:
        """获取抖音Web的游客Cookie/Get the guest Cookie of Douyin Web

        ``GET /api/v1/douyin/web/fetch_douyin_web_guest_cookie``
        """
        params = _drop_none({
            "user_agent": user_agent,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_douyin_web_guest_cookie", params=params)

    async def generate_real_msToken(
        self,
    ) -> Any:
        """生成真实msToken/Generate real msToken

        ``GET /api/v1/douyin/web/generate_real_msToken``
        """
        return await self._client._request("GET", "/api/v1/douyin/web/generate_real_msToken")

    async def generate_ttwid(
        self,
        *,
        user_agent: str | None = None,
    ) -> Any:
        """生成ttwid/Generate ttwid

        ``GET /api/v1/douyin/web/generate_ttwid``
        """
        params = _drop_none({
            "user_agent": user_agent,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/generate_ttwid", params=params)

    async def fetch_query_user(
        self,
        *,
        body: Any = None,
    ) -> Any:
        """查询抖音用户基本信息/Query Douyin user basic information

        ``POST /api/v1/douyin/web/fetch_query_user``
        """
        json_body = body
        return await self._client._request("POST", "/api/v1/douyin/web/fetch_query_user", json=json_body)

    async def generate_verify_fp(
        self,
    ) -> Any:
        """生成verify_fp/Generate verify_fp

        ``GET /api/v1/douyin/web/generate_verify_fp``
        """
        return await self._client._request("GET", "/api/v1/douyin/web/generate_verify_fp")

    async def generate_s_v_web_id(
        self,
    ) -> Any:
        """生成s_v_web_id/Generate s_v_web_id

        ``GET /api/v1/douyin/web/generate_s_v_web_id``
        """
        return await self._client._request("GET", "/api/v1/douyin/web/generate_s_v_web_id")

    async def generate_wss_xb_signature(
        self,
        *,
        user_agent: str,
        room_id: str,
        user_unique_id: str,
    ) -> Any:
        """生成弹幕xb签名/Generate barrage xb signature

        ``GET /api/v1/douyin/web/generate_wss_xb_signature``
        """
        params = _drop_none({
            "user_agent": user_agent,
            "room_id": room_id,
            "user_unique_id": user_unique_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/generate_wss_xb_signature", params=params)

    async def generate_x_bogus(
        self,
        *,
        url: str,
        user_agent: str,
    ) -> Any:
        """使用接口网址生成X-Bogus参数/Generate X-Bogus parameter using API URL

        ``POST /api/v1/douyin/web/generate_x_bogus``
        """
        json_body = _drop_none({
            "url": url,
            "user_agent": user_agent,
        })
        return await self._client._request("POST", "/api/v1/douyin/web/generate_x_bogus", json=json_body)

    async def generate_a_bogus(
        self,
        *,
        url: str,
        data: str,
        user_agent: str,
        index_0: int | None = None,
        index_1: int | None = None,
        index_2: int | None = None,
    ) -> Any:
        """使用接口网址生成A-Bogus参数/Generate A-Bogus parameter using API URL

        ``POST /api/v1/douyin/web/generate_a_bogus``
        """
        json_body = _drop_none({
            "url": url,
            "data": data,
            "user_agent": user_agent,
            "index_0": index_0,
            "index_1": index_1,
            "index_2": index_2,
        })
        return await self._client._request("POST", "/api/v1/douyin/web/generate_a_bogus", json=json_body)

    async def get_sec_user_id(
        self,
        *,
        url: str,
    ) -> Any:
        """提取单个用户id/Extract single user id

        ``GET /api/v1/douyin/web/get_sec_user_id``
        """
        params = _drop_none({
            "url": url,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/get_sec_user_id", params=params)

    async def get_all_sec_user_id(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """提取列表用户id/Extract list user id

        ``POST /api/v1/douyin/web/get_all_sec_user_id``
        """
        json_body = body
        return await self._client._request("POST", "/api/v1/douyin/web/get_all_sec_user_id", json=json_body)

    async def get_aweme_id(
        self,
        *,
        url: str,
    ) -> Any:
        """提取单个作品id/Extract single video id

        ``GET /api/v1/douyin/web/get_aweme_id``
        """
        params = _drop_none({
            "url": url,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/get_aweme_id", params=params)

    async def get_all_aweme_id(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """提取列表作品id/Extract list video id

        ``POST /api/v1/douyin/web/get_all_aweme_id``
        """
        json_body = body
        return await self._client._request("POST", "/api/v1/douyin/web/get_all_aweme_id", json=json_body)

    async def get_webcast_id(
        self,
        *,
        url: str,
    ) -> Any:
        """提取直播间号/Extract webcast id

        ``GET /api/v1/douyin/web/get_webcast_id``
        """
        params = _drop_none({
            "url": url,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/get_webcast_id", params=params)

    async def get_all_webcast_id(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """提取列表直播间号/Extract list webcast id

        ``POST /api/v1/douyin/web/get_all_webcast_id``
        """
        json_body = body
        return await self._client._request("POST", "/api/v1/douyin/web/get_all_webcast_id", json=json_body)

    async def webcast_id_2_room_id(
        self,
        *,
        webcast_id: str,
    ) -> Any:
        """直播间号转房间号/Webcast id to room id

        ``GET /api/v1/douyin/web/webcast_id_2_room_id``
        """
        params = _drop_none({
            "webcast_id": webcast_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/webcast_id_2_room_id", params=params)

    async def douyin_live_room(
        self,
        *,
        live_room_url: str,
        danmaku_type: str,
    ) -> Any:
        """提取直播间弹幕/Extract live room danmaku

        ``GET /api/v1/douyin/web/douyin_live_room``
        """
        params = _drop_none({
            "live_room_url": live_room_url,
            "danmaku_type": danmaku_type,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/douyin_live_room", params=params)

    async def fetch_live_im_fetch(
        self,
        *,
        room_id: str,
        user_unique_id: str,
    ) -> Any:
        """抖音直播间弹幕参数获取/Douyin live room danmaku parameters

        ``GET /api/v1/douyin/web/fetch_live_im_fetch``
        """
        params = _drop_none({
            "room_id": room_id,
            "user_unique_id": user_unique_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_live_im_fetch", params=params)

    async def fetch_series_aweme(
        self,
        *,
        offset: int,
        count: int,
        content_type: int,
        cookie: str | None = None,
    ) -> Any:
        """短剧作品/Series Video

        ``GET /api/v1/douyin/web/fetch_series_aweme``
        """
        params = _drop_none({
            "offset": offset,
            "count": count,
            "content_type": content_type,
            "cookie": cookie,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_series_aweme", params=params)

    async def fetch_knowledge_aweme(
        self,
        *,
        count: int,
        refresh_index: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """知识作品推荐/Knowledge Video

        ``GET /api/v1/douyin/web/fetch_knowledge_aweme``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
            "cookie": cookie,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_knowledge_aweme", params=params)

    async def fetch_game_aweme(
        self,
        *,
        count: int,
        refresh_index: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """游戏作品推荐/Game Video

        ``GET /api/v1/douyin/web/fetch_game_aweme``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
            "cookie": cookie,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_game_aweme", params=params)

    async def fetch_cartoon_aweme(
        self,
        *,
        count: int,
        refresh_index: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """二次元作品推荐/Anime Video

        ``GET /api/v1/douyin/web/fetch_cartoon_aweme``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
            "cookie": cookie,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_cartoon_aweme", params=params)

    async def fetch_music_aweme(
        self,
        *,
        count: int,
        refresh_index: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """音乐作品推荐/Music Video

        ``GET /api/v1/douyin/web/fetch_music_aweme``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
            "cookie": cookie,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_music_aweme", params=params)

    async def fetch_food_aweme(
        self,
        *,
        count: int,
        refresh_index: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """美食作品推荐/Food Video

        ``GET /api/v1/douyin/web/fetch_food_aweme``
        """
        params = _drop_none({
            "count": count,
            "refresh_index": refresh_index,
            "cookie": cookie,
        })
        return await self._client._request("GET", "/api/v1/douyin/web/fetch_food_aweme", params=params)
