# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Douyin-Index-API resource.

OpenAPI tag: ``Douyin-Index-API``
SDK attribute: ``client.douyin_index`` / ``async_client.douyin_index``

Endpoints: 44
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncDouyinIndex", "DouyinIndex"]


class DouyinIndex(SyncResource):
    """Sync ``Douyin-Index-API`` resource (44 endpoints)."""

    def fetch_all_valid_date(
        self,
    ) -> Any:
        """获取所有有效日期/Get all valid dates

        ``GET /api/v1/douyin/index/fetch_all_valid_date``
        """
        return self._client._request("GET", "/api/v1/douyin/index/fetch_all_valid_date")

    def fetch_valid_date_for_relation(
        self,
    ) -> Any:
        """获取关联分析有效日期/Get valid date for relation

        ``GET /api/v1/douyin/index/fetch_valid_date_for_relation``
        """
        return self._client._request("GET", "/api/v1/douyin/index/fetch_valid_date_for_relation")

    def fetch_all_area(
        self,
    ) -> Any:
        """获取所有地区列表/Get all area list

        ``GET /api/v1/douyin/index/fetch_all_area``
        """
        return self._client._request("GET", "/api/v1/douyin/index/fetch_all_area")

    def fetch_current_hot_topic(
        self,
    ) -> Any:
        """获取实时热点排行/Get current hot topics

        ``GET /api/v1/douyin/index/fetch_current_hot_topic``
        """
        return self._client._request("GET", "/api/v1/douyin/index/fetch_current_hot_topic")

    def fetch_hot_words(
        self,
        *,
        app_name: str | None = None,
    ) -> Any:
        """获取热门关键词/Get hot words

        ``GET /api/v1/douyin/index/fetch_hot_words``
        """
        params = _drop_none({
            "app_name": app_name,
        })
        return self._client._request("GET", "/api/v1/douyin/index/fetch_hot_words", params=params)

    def fetch_keyword_valid_date(
        self,
        *,
        keyword_list: str,
    ) -> Any:
        """获取关键词有效日期/Get keyword valid date

        ``POST /api/v1/douyin/index/fetch_keyword_valid_date``
        """
        params = _drop_none({
            "keyword_list": keyword_list,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_keyword_valid_date", params=params)

    def fetch_multi_keyword_hot_trend(
        self,
        *,
        keyword_list: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
        region: str | None = None,
    ) -> Any:
        """获取多关键词热度趋势/Get multi-keyword hot trend

        ``POST /api/v1/douyin/index/fetch_multi_keyword_hot_trend``
        """
        params = _drop_none({
            "keyword_list": keyword_list,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
            "region": region,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_multi_keyword_hot_trend", params=params)

    def fetch_multi_keyword_interpretation(
        self,
        *,
        keyword_list: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
        region: str | None = None,
    ) -> Any:
        """获取多关键词解读/Get multi-keyword interpretation

        ``POST /api/v1/douyin/index/fetch_multi_keyword_interpretation``
        """
        params = _drop_none({
            "keyword_list": keyword_list,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
            "region": region,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_multi_keyword_interpretation", params=params)

    def fetch_relation_word(
        self,
        *,
        keyword: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取关联词分析/Get relation word analysis

        ``POST /api/v1/douyin/index/fetch_relation_word``
        """
        params = _drop_none({
            "keyword": keyword,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_relation_word", params=params)

    def fetch_portrait(
        self,
        *,
        keyword: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取人群画像/Get crowd portrait

        ``POST /api/v1/douyin/index/fetch_portrait``
        """
        params = _drop_none({
            "keyword": keyword,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_portrait", params=params)

    def fetch_get_user_sub_word(
        self,
    ) -> Any:
        """获取用户订阅关键词/Get user subscribed keywords

        ``POST /api/v1/douyin/index/fetch_get_user_sub_word``
        """
        return self._client._request("POST", "/api/v1/douyin/index/fetch_get_user_sub_word")

    def fetch_encrypt_user_id(
        self,
        *,
        uid: str,
    ) -> Any:
        """抖音 uid 转加密 user_id/Encrypt Douyin uid to user_id

        ``GET /api/v1/douyin/index/fetch_encrypt_user_id``
        """
        params = _drop_none({
            "uid": uid,
        })
        return self._client._request("GET", "/api/v1/douyin/index/fetch_encrypt_user_id", params=params)

    def fetch_daren_sug_great_user_list(
        self,
        *,
        keyword: str,
        total: str | None = None,
    ) -> Any:
        """达人搜索建议/Daren search suggest

        ``POST /api/v1/douyin/index/fetch_daren_sug_great_user_list``
        """
        params = _drop_none({
            "keyword": keyword,
            "total": total,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_daren_sug_great_user_list", params=params)

    def fetch_daren_compare_users_stable(
        self,
        *,
        user_list: str,
        days: str | None = None,
    ) -> Any:
        """达人趋势对比/Daren compare users

        ``POST /api/v1/douyin/index/fetch_daren_compare_users_stable``
        """
        params = _drop_none({
            "user_list": user_list,
            "days": days,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_daren_compare_users_stable", params=params)

    def fetch_daren_similar_users(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取相似达人/Get similar daren

        ``POST /api/v1/douyin/index/fetch_daren_similar_users``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_daren_similar_users", params=params)

    def fetch_daren_great_user_top_video(
        self,
        *,
        user_id: str,
        start_date: str,
        end_date: str,
    ) -> Any:
        """获取达人视频/Get daren top videos

        ``POST /api/v1/douyin/index/fetch_daren_great_user_top_video``
        """
        params = _drop_none({
            "user_id": user_id,
            "start_date": start_date,
            "end_date": end_date,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_daren_great_user_top_video", params=params)

    def fetch_daren_great_item_mile_info(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取达人核心指标/Get daren core metrics

        ``POST /api/v1/douyin/index/fetch_daren_great_item_mile_info``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_daren_great_item_mile_info", params=params)

    def fetch_daren_great_user_fans_info(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取达人粉丝分析/Get daren fans analysis

        ``POST /api/v1/douyin/index/fetch_daren_great_user_fans_info``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_daren_great_user_fans_info", params=params)

    def fetch_item_filter_options(
        self,
    ) -> Any:
        """获取视频搜索筛选选项/Get video search filter options

        ``GET /api/v1/douyin/index/fetch_item_filter_options``
        """
        return self._client._request("GET", "/api/v1/douyin/index/fetch_item_filter_options")

    def fetch_item_sug(
        self,
        *,
        query: str,
    ) -> Any:
        """视频搜索建议/Video search suggest

        ``POST /api/v1/douyin/index/fetch_item_sug``
        """
        params = _drop_none({
            "query": query,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_item_sug", params=params)

    def fetch_item_query(
        self,
        *,
        query: str,
        category_id: str | None = None,
        date_type: int | None = None,
        label_type: int | None = None,
        duration_type: int | None = None,
    ) -> Any:
        """视频搜索结果/Video search results

        ``POST /api/v1/douyin/index/fetch_item_query``
        """
        params = _drop_none({
            "query": query,
            "category_id": category_id,
            "date_type": date_type,
            "label_type": label_type,
            "duration_type": duration_type,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_item_query", params=params)

    def fetch_brand_suggest(
        self,
        *,
        keyword: str,
    ) -> Any:
        """品牌搜索建议/Brand search suggest

        ``POST /api/v1/douyin/index/fetch_brand_suggest``
        """
        params = _drop_none({
            "keyword": keyword,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_brand_suggest", params=params)

    def fetch_brand_valid_info(
        self,
        *,
        keyword_list: str,
    ) -> Any:
        """获取品牌指数/Get brand index

        ``POST /api/v1/douyin/index/fetch_brand_valid_info``
        """
        params = _drop_none({
            "keyword_list": keyword_list,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_brand_valid_info", params=params)

    def fetch_brand_radar_chart(
        self,
        *,
        brand_name: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取品牌雷达图/Get brand radar chart

        ``POST /api/v1/douyin/index/fetch_brand_radar_chart``
        """
        params = _drop_none({
            "brand_name": brand_name,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_brand_radar_chart", params=params)

    def fetch_brand_lines(
        self,
        *,
        brand_name: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取品牌趋势线/Get brand trend lines

        ``POST /api/v1/douyin/index/fetch_brand_lines``
        """
        params = _drop_none({
            "brand_name": brand_name,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_brand_lines", params=params)

    def fetch_brand_cycles(
        self,
        *,
        brand_name: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取品牌周期数据/Get brand cycles

        ``POST /api/v1/douyin/index/fetch_brand_cycles``
        """
        params = _drop_none({
            "brand_name": brand_name,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_brand_cycles", params=params)

    def fetch_brand_initiative_rank_weekly(
        self,
        *,
        brand_name: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取品牌主动排行周榜/Get brand initiative rank weekly

        ``POST /api/v1/douyin/index/fetch_brand_initiative_rank_weekly``
        """
        params = _drop_none({
            "brand_name": brand_name,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_brand_initiative_rank_weekly", params=params)

    def fetch_topic_suggest(
        self,
        *,
        keyword: str,
        app_name: str | None = None,
    ) -> Any:
        """话题搜索建议/Topic search suggest

        ``POST /api/v1/douyin/index/fetch_topic_suggest``
        """
        params = _drop_none({
            "keyword": keyword,
            "app_name": app_name,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_topic_suggest", params=params)

    def fetch_topic_query(
        self,
        *,
        keyword: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """话题搜索结果/Topic search results

        ``POST /api/v1/douyin/index/fetch_topic_query``
        """
        params = _drop_none({
            "keyword": keyword,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_topic_query", params=params)

    def fetch_content_valid_date(
        self,
    ) -> Any:
        """创作指南有效日期/Get content valid date

        ``GET /api/v1/douyin/index/fetch_content_valid_date``
        """
        return self._client._request("GET", "/api/v1/douyin/index/fetch_content_valid_date")

    def fetch_brand_hot_videos_time_scope(
        self,
    ) -> Any:
        """热门视频时间范围/Brand hot videos time scope

        ``POST /api/v1/douyin/index/fetch_brand_hot_videos_time_scope``
        """
        return self._client._request("POST", "/api/v1/douyin/index/fetch_brand_hot_videos_time_scope")

    def fetch_content_creative_keywords(
        self,
        *,
        tag_id: str,
        end_date: str,
        period: str | None = None,
    ) -> Any:
        """创作热门关键词/Content creative keywords

        ``POST /api/v1/douyin/index/fetch_content_creative_keywords``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_content_creative_keywords", params=params)

    def fetch_content_creative_keyword_items(
        self,
        *,
        tag_id: str,
        end_date: str,
        keyword: str,
        period: str | None = None,
    ) -> Any:
        """关键词相关视频/Creative keyword related items

        ``POST /api/v1/douyin/index/fetch_content_creative_keyword_items``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
            "keyword": keyword,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_content_creative_keyword_items", params=params)

    def fetch_content_creative_topic(
        self,
        *,
        tag_id: str,
        end_date: str,
        period: str | None = None,
        rank_type: str | None = None,
    ) -> Any:
        """创作热门话题/Content creative topic

        ``POST /api/v1/douyin/index/fetch_content_creative_topic``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
            "rank_type": rank_type,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_content_creative_topic", params=params)

    def fetch_content_publish_trend(
        self,
        *,
        tag_id: str,
        start_date: str,
        end_date: str,
    ) -> Any:
        """内容发布趋势/Content publish trend

        ``GET /api/v1/douyin/index/fetch_content_publish_trend``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "start_date": start_date,
            "end_date": end_date,
        })
        return self._client._request("GET", "/api/v1/douyin/index/fetch_content_publish_trend", params=params)

    def fetch_content_creative_duration(
        self,
        *,
        tag_id: str,
        end_date: str,
        period: str | None = None,
    ) -> Any:
        """创作时长分布/Content creative duration

        ``POST /api/v1/douyin/index/fetch_content_creative_duration``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_content_creative_duration", params=params)

    def fetch_content_author_portrait(
        self,
        *,
        tag_id: str,
        end_date: str,
        period: str | None = None,
    ) -> Any:
        """创作者画像/Content author portrait

        ``POST /api/v1/douyin/index/fetch_content_author_portrait``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_content_author_portrait", params=params)

    def fetch_content_consumer_portrait(
        self,
        *,
        tag_id: str,
        end_date: str,
        period: str | None = None,
    ) -> Any:
        """消费者画像/Content consumer portrait

        ``POST /api/v1/douyin/index/fetch_content_consumer_portrait``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_content_consumer_portrait", params=params)

    def fetch_content_interact_trend(
        self,
        *,
        tag_id: str,
        start_date: str,
        end_date: str,
    ) -> Any:
        """互动趋势/Content interact trend

        ``POST /api/v1/douyin/index/fetch_content_interact_trend``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "start_date": start_date,
            "end_date": end_date,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_content_interact_trend", params=params)

    def fetch_content_consume_trend(
        self,
        *,
        tag_id: str,
        start_date: str,
        end_date: str,
    ) -> Any:
        """消费趋势/Content consume trend

        ``POST /api/v1/douyin/index/fetch_content_consume_trend``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "start_date": start_date,
            "end_date": end_date,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_content_consume_trend", params=params)

    def fetch_insight_recommend(
        self,
    ) -> Any:
        """获取推荐报告/Get recommended insight reports

        ``GET /api/v1/douyin/index/fetch_insight_recommend``
        """
        return self._client._request("GET", "/api/v1/douyin/index/fetch_insight_recommend")

    def fetch_report_search(
        self,
        *,
        current_page: str | None = None,
        page_size: str | None = None,
        type: str | None = None,
        business: str | None = None,
        report_time: str | None = None,
        search: str | None = None,
        category: str | None = None,
    ) -> Any:
        """搜索趋势报告/Search trend reports

        ``POST /api/v1/douyin/index/fetch_report_search``
        """
        params = _drop_none({
            "current_page": current_page,
            "page_size": page_size,
            "type": type,
            "business": business,
            "report_time": report_time,
            "search": search,
            "category": category,
        })
        return self._client._request("POST", "/api/v1/douyin/index/fetch_report_search", params=params)

    def fetch_report_detail(
        self,
        *,
        report_id: str,
    ) -> Any:
        """获取报告详情/Get report detail

        ``GET /api/v1/douyin/index/fetch_report_detail``
        """
        params = _drop_none({
            "report_id": report_id,
        })
        return self._client._request("GET", "/api/v1/douyin/index/fetch_report_detail", params=params)

    def fetch_insight_get_rec(
        self,
        *,
        report_id: str,
    ) -> Any:
        """获取报告相关推荐/Get related insight recommendations

        ``GET /api/v1/douyin/index/fetch_insight_get_rec``
        """
        params = _drop_none({
            "report_id": report_id,
        })
        return self._client._request("GET", "/api/v1/douyin/index/fetch_insight_get_rec", params=params)


class AsyncDouyinIndex(AsyncResource):
    """Async ``Douyin-Index-API`` resource (44 endpoints)."""

    async def fetch_all_valid_date(
        self,
    ) -> Any:
        """获取所有有效日期/Get all valid dates

        ``GET /api/v1/douyin/index/fetch_all_valid_date``
        """
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_all_valid_date")

    async def fetch_valid_date_for_relation(
        self,
    ) -> Any:
        """获取关联分析有效日期/Get valid date for relation

        ``GET /api/v1/douyin/index/fetch_valid_date_for_relation``
        """
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_valid_date_for_relation")

    async def fetch_all_area(
        self,
    ) -> Any:
        """获取所有地区列表/Get all area list

        ``GET /api/v1/douyin/index/fetch_all_area``
        """
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_all_area")

    async def fetch_current_hot_topic(
        self,
    ) -> Any:
        """获取实时热点排行/Get current hot topics

        ``GET /api/v1/douyin/index/fetch_current_hot_topic``
        """
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_current_hot_topic")

    async def fetch_hot_words(
        self,
        *,
        app_name: str | None = None,
    ) -> Any:
        """获取热门关键词/Get hot words

        ``GET /api/v1/douyin/index/fetch_hot_words``
        """
        params = _drop_none({
            "app_name": app_name,
        })
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_hot_words", params=params)

    async def fetch_keyword_valid_date(
        self,
        *,
        keyword_list: str,
    ) -> Any:
        """获取关键词有效日期/Get keyword valid date

        ``POST /api/v1/douyin/index/fetch_keyword_valid_date``
        """
        params = _drop_none({
            "keyword_list": keyword_list,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_keyword_valid_date", params=params)

    async def fetch_multi_keyword_hot_trend(
        self,
        *,
        keyword_list: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
        region: str | None = None,
    ) -> Any:
        """获取多关键词热度趋势/Get multi-keyword hot trend

        ``POST /api/v1/douyin/index/fetch_multi_keyword_hot_trend``
        """
        params = _drop_none({
            "keyword_list": keyword_list,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
            "region": region,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_multi_keyword_hot_trend", params=params)

    async def fetch_multi_keyword_interpretation(
        self,
        *,
        keyword_list: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
        region: str | None = None,
    ) -> Any:
        """获取多关键词解读/Get multi-keyword interpretation

        ``POST /api/v1/douyin/index/fetch_multi_keyword_interpretation``
        """
        params = _drop_none({
            "keyword_list": keyword_list,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
            "region": region,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_multi_keyword_interpretation", params=params)

    async def fetch_relation_word(
        self,
        *,
        keyword: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取关联词分析/Get relation word analysis

        ``POST /api/v1/douyin/index/fetch_relation_word``
        """
        params = _drop_none({
            "keyword": keyword,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_relation_word", params=params)

    async def fetch_portrait(
        self,
        *,
        keyword: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取人群画像/Get crowd portrait

        ``POST /api/v1/douyin/index/fetch_portrait``
        """
        params = _drop_none({
            "keyword": keyword,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_portrait", params=params)

    async def fetch_get_user_sub_word(
        self,
    ) -> Any:
        """获取用户订阅关键词/Get user subscribed keywords

        ``POST /api/v1/douyin/index/fetch_get_user_sub_word``
        """
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_get_user_sub_word")

    async def fetch_encrypt_user_id(
        self,
        *,
        uid: str,
    ) -> Any:
        """抖音 uid 转加密 user_id/Encrypt Douyin uid to user_id

        ``GET /api/v1/douyin/index/fetch_encrypt_user_id``
        """
        params = _drop_none({
            "uid": uid,
        })
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_encrypt_user_id", params=params)

    async def fetch_daren_sug_great_user_list(
        self,
        *,
        keyword: str,
        total: str | None = None,
    ) -> Any:
        """达人搜索建议/Daren search suggest

        ``POST /api/v1/douyin/index/fetch_daren_sug_great_user_list``
        """
        params = _drop_none({
            "keyword": keyword,
            "total": total,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_daren_sug_great_user_list", params=params)

    async def fetch_daren_compare_users_stable(
        self,
        *,
        user_list: str,
        days: str | None = None,
    ) -> Any:
        """达人趋势对比/Daren compare users

        ``POST /api/v1/douyin/index/fetch_daren_compare_users_stable``
        """
        params = _drop_none({
            "user_list": user_list,
            "days": days,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_daren_compare_users_stable", params=params)

    async def fetch_daren_similar_users(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取相似达人/Get similar daren

        ``POST /api/v1/douyin/index/fetch_daren_similar_users``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_daren_similar_users", params=params)

    async def fetch_daren_great_user_top_video(
        self,
        *,
        user_id: str,
        start_date: str,
        end_date: str,
    ) -> Any:
        """获取达人视频/Get daren top videos

        ``POST /api/v1/douyin/index/fetch_daren_great_user_top_video``
        """
        params = _drop_none({
            "user_id": user_id,
            "start_date": start_date,
            "end_date": end_date,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_daren_great_user_top_video", params=params)

    async def fetch_daren_great_item_mile_info(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取达人核心指标/Get daren core metrics

        ``POST /api/v1/douyin/index/fetch_daren_great_item_mile_info``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_daren_great_item_mile_info", params=params)

    async def fetch_daren_great_user_fans_info(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取达人粉丝分析/Get daren fans analysis

        ``POST /api/v1/douyin/index/fetch_daren_great_user_fans_info``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_daren_great_user_fans_info", params=params)

    async def fetch_item_filter_options(
        self,
    ) -> Any:
        """获取视频搜索筛选选项/Get video search filter options

        ``GET /api/v1/douyin/index/fetch_item_filter_options``
        """
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_item_filter_options")

    async def fetch_item_sug(
        self,
        *,
        query: str,
    ) -> Any:
        """视频搜索建议/Video search suggest

        ``POST /api/v1/douyin/index/fetch_item_sug``
        """
        params = _drop_none({
            "query": query,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_item_sug", params=params)

    async def fetch_item_query(
        self,
        *,
        query: str,
        category_id: str | None = None,
        date_type: int | None = None,
        label_type: int | None = None,
        duration_type: int | None = None,
    ) -> Any:
        """视频搜索结果/Video search results

        ``POST /api/v1/douyin/index/fetch_item_query``
        """
        params = _drop_none({
            "query": query,
            "category_id": category_id,
            "date_type": date_type,
            "label_type": label_type,
            "duration_type": duration_type,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_item_query", params=params)

    async def fetch_brand_suggest(
        self,
        *,
        keyword: str,
    ) -> Any:
        """品牌搜索建议/Brand search suggest

        ``POST /api/v1/douyin/index/fetch_brand_suggest``
        """
        params = _drop_none({
            "keyword": keyword,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_brand_suggest", params=params)

    async def fetch_brand_valid_info(
        self,
        *,
        keyword_list: str,
    ) -> Any:
        """获取品牌指数/Get brand index

        ``POST /api/v1/douyin/index/fetch_brand_valid_info``
        """
        params = _drop_none({
            "keyword_list": keyword_list,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_brand_valid_info", params=params)

    async def fetch_brand_radar_chart(
        self,
        *,
        brand_name: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取品牌雷达图/Get brand radar chart

        ``POST /api/v1/douyin/index/fetch_brand_radar_chart``
        """
        params = _drop_none({
            "brand_name": brand_name,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_brand_radar_chart", params=params)

    async def fetch_brand_lines(
        self,
        *,
        brand_name: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取品牌趋势线/Get brand trend lines

        ``POST /api/v1/douyin/index/fetch_brand_lines``
        """
        params = _drop_none({
            "brand_name": brand_name,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_brand_lines", params=params)

    async def fetch_brand_cycles(
        self,
        *,
        brand_name: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取品牌周期数据/Get brand cycles

        ``POST /api/v1/douyin/index/fetch_brand_cycles``
        """
        params = _drop_none({
            "brand_name": brand_name,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_brand_cycles", params=params)

    async def fetch_brand_initiative_rank_weekly(
        self,
        *,
        brand_name: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """获取品牌主动排行周榜/Get brand initiative rank weekly

        ``POST /api/v1/douyin/index/fetch_brand_initiative_rank_weekly``
        """
        params = _drop_none({
            "brand_name": brand_name,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_brand_initiative_rank_weekly", params=params)

    async def fetch_topic_suggest(
        self,
        *,
        keyword: str,
        app_name: str | None = None,
    ) -> Any:
        """话题搜索建议/Topic search suggest

        ``POST /api/v1/douyin/index/fetch_topic_suggest``
        """
        params = _drop_none({
            "keyword": keyword,
            "app_name": app_name,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_topic_suggest", params=params)

    async def fetch_topic_query(
        self,
        *,
        keyword: str,
        start_date: str,
        end_date: str,
        app_name: str | None = None,
    ) -> Any:
        """话题搜索结果/Topic search results

        ``POST /api/v1/douyin/index/fetch_topic_query``
        """
        params = _drop_none({
            "keyword": keyword,
            "start_date": start_date,
            "end_date": end_date,
            "app_name": app_name,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_topic_query", params=params)

    async def fetch_content_valid_date(
        self,
    ) -> Any:
        """创作指南有效日期/Get content valid date

        ``GET /api/v1/douyin/index/fetch_content_valid_date``
        """
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_content_valid_date")

    async def fetch_brand_hot_videos_time_scope(
        self,
    ) -> Any:
        """热门视频时间范围/Brand hot videos time scope

        ``POST /api/v1/douyin/index/fetch_brand_hot_videos_time_scope``
        """
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_brand_hot_videos_time_scope")

    async def fetch_content_creative_keywords(
        self,
        *,
        tag_id: str,
        end_date: str,
        period: str | None = None,
    ) -> Any:
        """创作热门关键词/Content creative keywords

        ``POST /api/v1/douyin/index/fetch_content_creative_keywords``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_content_creative_keywords", params=params)

    async def fetch_content_creative_keyword_items(
        self,
        *,
        tag_id: str,
        end_date: str,
        keyword: str,
        period: str | None = None,
    ) -> Any:
        """关键词相关视频/Creative keyword related items

        ``POST /api/v1/douyin/index/fetch_content_creative_keyword_items``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
            "keyword": keyword,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_content_creative_keyword_items", params=params)

    async def fetch_content_creative_topic(
        self,
        *,
        tag_id: str,
        end_date: str,
        period: str | None = None,
        rank_type: str | None = None,
    ) -> Any:
        """创作热门话题/Content creative topic

        ``POST /api/v1/douyin/index/fetch_content_creative_topic``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
            "rank_type": rank_type,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_content_creative_topic", params=params)

    async def fetch_content_publish_trend(
        self,
        *,
        tag_id: str,
        start_date: str,
        end_date: str,
    ) -> Any:
        """内容发布趋势/Content publish trend

        ``GET /api/v1/douyin/index/fetch_content_publish_trend``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "start_date": start_date,
            "end_date": end_date,
        })
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_content_publish_trend", params=params)

    async def fetch_content_creative_duration(
        self,
        *,
        tag_id: str,
        end_date: str,
        period: str | None = None,
    ) -> Any:
        """创作时长分布/Content creative duration

        ``POST /api/v1/douyin/index/fetch_content_creative_duration``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_content_creative_duration", params=params)

    async def fetch_content_author_portrait(
        self,
        *,
        tag_id: str,
        end_date: str,
        period: str | None = None,
    ) -> Any:
        """创作者画像/Content author portrait

        ``POST /api/v1/douyin/index/fetch_content_author_portrait``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_content_author_portrait", params=params)

    async def fetch_content_consumer_portrait(
        self,
        *,
        tag_id: str,
        end_date: str,
        period: str | None = None,
    ) -> Any:
        """消费者画像/Content consumer portrait

        ``POST /api/v1/douyin/index/fetch_content_consumer_portrait``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "period": period,
            "end_date": end_date,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_content_consumer_portrait", params=params)

    async def fetch_content_interact_trend(
        self,
        *,
        tag_id: str,
        start_date: str,
        end_date: str,
    ) -> Any:
        """互动趋势/Content interact trend

        ``POST /api/v1/douyin/index/fetch_content_interact_trend``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "start_date": start_date,
            "end_date": end_date,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_content_interact_trend", params=params)

    async def fetch_content_consume_trend(
        self,
        *,
        tag_id: str,
        start_date: str,
        end_date: str,
    ) -> Any:
        """消费趋势/Content consume trend

        ``POST /api/v1/douyin/index/fetch_content_consume_trend``
        """
        params = _drop_none({
            "tag_id": tag_id,
            "start_date": start_date,
            "end_date": end_date,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_content_consume_trend", params=params)

    async def fetch_insight_recommend(
        self,
    ) -> Any:
        """获取推荐报告/Get recommended insight reports

        ``GET /api/v1/douyin/index/fetch_insight_recommend``
        """
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_insight_recommend")

    async def fetch_report_search(
        self,
        *,
        current_page: str | None = None,
        page_size: str | None = None,
        type: str | None = None,
        business: str | None = None,
        report_time: str | None = None,
        search: str | None = None,
        category: str | None = None,
    ) -> Any:
        """搜索趋势报告/Search trend reports

        ``POST /api/v1/douyin/index/fetch_report_search``
        """
        params = _drop_none({
            "current_page": current_page,
            "page_size": page_size,
            "type": type,
            "business": business,
            "report_time": report_time,
            "search": search,
            "category": category,
        })
        return await self._client._request("POST", "/api/v1/douyin/index/fetch_report_search", params=params)

    async def fetch_report_detail(
        self,
        *,
        report_id: str,
    ) -> Any:
        """获取报告详情/Get report detail

        ``GET /api/v1/douyin/index/fetch_report_detail``
        """
        params = _drop_none({
            "report_id": report_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_report_detail", params=params)

    async def fetch_insight_get_rec(
        self,
        *,
        report_id: str,
    ) -> Any:
        """获取报告相关推荐/Get related insight recommendations

        ``GET /api/v1/douyin/index/fetch_insight_get_rec``
        """
        params = _drop_none({
            "report_id": report_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/index/fetch_insight_get_rec", params=params)
