# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Douyin-Creator-API resource.

OpenAPI tag: ``Douyin-Creator-API``
SDK attribute: ``client.douyin_creator`` / ``async_client.douyin_creator``

Endpoints: 17
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncDouyinCreator", "DouyinCreator"]


class DouyinCreator(SyncResource):
    """Sync ``Douyin-Creator-API`` resource (17 endpoints)."""

    def fetch_creator_activity_list(
        self,
        *,
        start_time: int,
        end_time: int,
    ) -> Any:
        """获取创作者活动列表/Get creator activity list

        ``GET /api/v1/douyin/creator/fetch_creator_activity_list``
        """
        params = _drop_none({
            "start_time": start_time,
            "end_time": end_time,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_activity_list", params=params)

    def fetch_creator_activity_detail(
        self,
        *,
        activity_id: str,
    ) -> Any:
        """获取创作者活动详情/Get creator activity detail

        ``GET /api/v1/douyin/creator/fetch_creator_activity_detail``
        """
        params = _drop_none({
            "activity_id": activity_id,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_activity_detail", params=params)

    def fetch_creator_material_center_config(
        self,
    ) -> Any:
        """获取创作者中心配置/Get creator material center config

        ``GET /api/v1/douyin/creator/fetch_creator_material_center_config``
        """
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_material_center_config")

    def fetch_creator_material_center_billboard(
        self,
        *,
        billboard_tag: int | None = None,
        order_key: int | None = None,
        time_filter: int | None = None,
    ) -> Any:
        """获取创作者中心热门视频榜单/Get creator material center billboard

        ``GET /api/v1/douyin/creator/fetch_creator_material_center_billboard``
        """
        params = _drop_none({
            "billboard_tag": billboard_tag,
            "order_key": order_key,
            "time_filter": time_filter,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_material_center_billboard", params=params)

    def fetch_creator_material_center_related(
        self,
        *,
        query_id: str,
        billboard_type: int | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> Any:
        """获取话题/热点相关视频/Get topic or hot spot related videos

        ``GET /api/v1/douyin/creator/fetch_creator_material_center_related``
        """
        params = _drop_none({
            "query_id": query_id,
            "billboard_type": billboard_type,
            "limit": limit,
            "offset": offset,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_material_center_related", params=params)

    def fetch_creator_hot_spot_billboard(
        self,
        *,
        billboard_tag: str | None = None,
        hot_search_type: int | None = None,
        city_code: Any | None = None,
    ) -> Any:
        """获取创作者中心创作热点/Get creator hot spot billboard

        ``GET /api/v1/douyin/creator/fetch_creator_hot_spot_billboard``
        """
        params = _drop_none({
            "billboard_tag": billboard_tag,
            "hot_search_type": hot_search_type,
            "city_code": city_code,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_spot_billboard", params=params)

    def fetch_creator_hot_topic_billboard(
        self,
        *,
        billboard_tag: int | None = None,
        order_key: int | None = None,
        time_filter: int | None = None,
    ) -> Any:
        """获取创作者热门话题榜单/Get creator hot topic billboard

        ``GET /api/v1/douyin/creator/fetch_creator_hot_topic_billboard``
        """
        params = _drop_none({
            "billboard_tag": billboard_tag,
            "order_key": order_key,
            "time_filter": time_filter,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_topic_billboard", params=params)

    def fetch_creator_hot_props_billboard(
        self,
        *,
        billboard_tag: int | None = None,
        order_key: int | None = None,
        time_filter: int | None = None,
    ) -> Any:
        """获取创作者热门道具榜单/Get creator hot props billboard

        ``GET /api/v1/douyin/creator/fetch_creator_hot_props_billboard``
        """
        params = _drop_none({
            "billboard_tag": billboard_tag,
            "order_key": order_key,
            "time_filter": time_filter,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_props_billboard", params=params)

    def fetch_creator_hot_challenge_billboard(
        self,
    ) -> Any:
        """获取创作者热门挑战榜单/Get creator hot challenge billboard

        ``GET /api/v1/douyin/creator/fetch_creator_hot_challenge_billboard``
        """
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_challenge_billboard")

    def fetch_creator_hot_music_billboard(
        self,
        *,
        billboard_tag: int | None = None,
        order_key: int | None = None,
        time_filter: int | None = None,
    ) -> Any:
        """获取创作者热门音乐榜单/Get creator hot music billboard

        ``GET /api/v1/douyin/creator/fetch_creator_hot_music_billboard``
        """
        params = _drop_none({
            "billboard_tag": billboard_tag,
            "order_key": order_key,
            "time_filter": time_filter,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_music_billboard", params=params)

    def fetch_creator_hot_course(
        self,
        *,
        order: int | None = None,
        limit: int | None = None,
        offset: int | None = None,
        category_id: Any | None = None,
    ) -> Any:
        """获取创作者热门课程/Get creator hot course

        ``GET /api/v1/douyin/creator/fetch_creator_hot_course``
        """
        params = _drop_none({
            "order": order,
            "limit": limit,
            "offset": offset,
            "category_id": category_id,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_course", params=params)

    def fetch_creator_content_category(
        self,
    ) -> Any:
        """获取创作者内容创作合集分类/Get creator content creation category

        ``GET /api/v1/douyin/creator/fetch_creator_content_category``
        """
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_content_category")

    def fetch_creator_content_course(
        self,
        *,
        category_id: int,
        order: int | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> Any:
        """获取创作者内容创作课程/Get creator content creation course

        ``GET /api/v1/douyin/creator/fetch_creator_content_course``
        """
        params = _drop_none({
            "category_id": category_id,
            "order": order,
            "limit": limit,
            "offset": offset,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_content_course", params=params)

    def fetch_video_danmaku_list(
        self,
        *,
        item_id: str,
        count: int | None = None,
        offset: int | None = None,
        order_type: int | None = None,
        is_blocked: bool | None = None,
    ) -> Any:
        """获取作品弹幕列表/Get video danmaku list

        ``GET /api/v1/douyin/creator/fetch_video_danmaku_list``
        """
        params = _drop_none({
            "item_id": item_id,
            "count": count,
            "offset": offset,
            "order_type": order_type,
            "is_blocked": is_blocked,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_video_danmaku_list", params=params)

    def fetch_user_search(
        self,
        *,
        user_name: str,
    ) -> Any:
        """搜索用户/Search users

        ``GET /api/v1/douyin/creator/fetch_user_search``
        """
        params = _drop_none({
            "user_name": user_name,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_user_search", params=params)

    def fetch_mission_task_list(
        self,
        *,
        cursor: int | None = None,
        limit: int | None = None,
        mission_type: int | None = None,
        tab_scene: int | None = None,
        industry_lv1: int | None = None,
        industry_lv2: int | None = None,
        platform_channel: Any | None = None,
        pay_type: Any | None = None,
        greater_than_cost_progress: Any | None = None,
        publish_time_start: Any | None = None,
        quick_selector_scene: Any | None = None,
        keyword: Any | None = None,
    ) -> Any:
        """获取商单任务列表/Get mission task list

        ``GET /api/v1/douyin/creator/fetch_mission_task_list``
        """
        params = _drop_none({
            "cursor": cursor,
            "limit": limit,
            "mission_type": mission_type,
            "tab_scene": tab_scene,
            "industry_lv1": industry_lv1,
            "industry_lv2": industry_lv2,
            "platform_channel": platform_channel,
            "pay_type": pay_type,
            "greater_than_cost_progress": greater_than_cost_progress,
            "publish_time_start": publish_time_start,
            "quick_selector_scene": quick_selector_scene,
            "keyword": keyword,
        })
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_mission_task_list", params=params)

    def fetch_industry_category_config(
        self,
    ) -> Any:
        """获取行业分类配置/Get industry category config

        ``GET /api/v1/douyin/creator/fetch_industry_category_config``
        """
        return self._client._request("GET", "/api/v1/douyin/creator/fetch_industry_category_config")


class AsyncDouyinCreator(AsyncResource):
    """Async ``Douyin-Creator-API`` resource (17 endpoints)."""

    async def fetch_creator_activity_list(
        self,
        *,
        start_time: int,
        end_time: int,
    ) -> Any:
        """获取创作者活动列表/Get creator activity list

        ``GET /api/v1/douyin/creator/fetch_creator_activity_list``
        """
        params = _drop_none({
            "start_time": start_time,
            "end_time": end_time,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_activity_list", params=params)

    async def fetch_creator_activity_detail(
        self,
        *,
        activity_id: str,
    ) -> Any:
        """获取创作者活动详情/Get creator activity detail

        ``GET /api/v1/douyin/creator/fetch_creator_activity_detail``
        """
        params = _drop_none({
            "activity_id": activity_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_activity_detail", params=params)

    async def fetch_creator_material_center_config(
        self,
    ) -> Any:
        """获取创作者中心配置/Get creator material center config

        ``GET /api/v1/douyin/creator/fetch_creator_material_center_config``
        """
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_material_center_config")

    async def fetch_creator_material_center_billboard(
        self,
        *,
        billboard_tag: int | None = None,
        order_key: int | None = None,
        time_filter: int | None = None,
    ) -> Any:
        """获取创作者中心热门视频榜单/Get creator material center billboard

        ``GET /api/v1/douyin/creator/fetch_creator_material_center_billboard``
        """
        params = _drop_none({
            "billboard_tag": billboard_tag,
            "order_key": order_key,
            "time_filter": time_filter,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_material_center_billboard", params=params)

    async def fetch_creator_material_center_related(
        self,
        *,
        query_id: str,
        billboard_type: int | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> Any:
        """获取话题/热点相关视频/Get topic or hot spot related videos

        ``GET /api/v1/douyin/creator/fetch_creator_material_center_related``
        """
        params = _drop_none({
            "query_id": query_id,
            "billboard_type": billboard_type,
            "limit": limit,
            "offset": offset,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_material_center_related", params=params)

    async def fetch_creator_hot_spot_billboard(
        self,
        *,
        billboard_tag: str | None = None,
        hot_search_type: int | None = None,
        city_code: Any | None = None,
    ) -> Any:
        """获取创作者中心创作热点/Get creator hot spot billboard

        ``GET /api/v1/douyin/creator/fetch_creator_hot_spot_billboard``
        """
        params = _drop_none({
            "billboard_tag": billboard_tag,
            "hot_search_type": hot_search_type,
            "city_code": city_code,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_spot_billboard", params=params)

    async def fetch_creator_hot_topic_billboard(
        self,
        *,
        billboard_tag: int | None = None,
        order_key: int | None = None,
        time_filter: int | None = None,
    ) -> Any:
        """获取创作者热门话题榜单/Get creator hot topic billboard

        ``GET /api/v1/douyin/creator/fetch_creator_hot_topic_billboard``
        """
        params = _drop_none({
            "billboard_tag": billboard_tag,
            "order_key": order_key,
            "time_filter": time_filter,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_topic_billboard", params=params)

    async def fetch_creator_hot_props_billboard(
        self,
        *,
        billboard_tag: int | None = None,
        order_key: int | None = None,
        time_filter: int | None = None,
    ) -> Any:
        """获取创作者热门道具榜单/Get creator hot props billboard

        ``GET /api/v1/douyin/creator/fetch_creator_hot_props_billboard``
        """
        params = _drop_none({
            "billboard_tag": billboard_tag,
            "order_key": order_key,
            "time_filter": time_filter,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_props_billboard", params=params)

    async def fetch_creator_hot_challenge_billboard(
        self,
    ) -> Any:
        """获取创作者热门挑战榜单/Get creator hot challenge billboard

        ``GET /api/v1/douyin/creator/fetch_creator_hot_challenge_billboard``
        """
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_challenge_billboard")

    async def fetch_creator_hot_music_billboard(
        self,
        *,
        billboard_tag: int | None = None,
        order_key: int | None = None,
        time_filter: int | None = None,
    ) -> Any:
        """获取创作者热门音乐榜单/Get creator hot music billboard

        ``GET /api/v1/douyin/creator/fetch_creator_hot_music_billboard``
        """
        params = _drop_none({
            "billboard_tag": billboard_tag,
            "order_key": order_key,
            "time_filter": time_filter,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_music_billboard", params=params)

    async def fetch_creator_hot_course(
        self,
        *,
        order: int | None = None,
        limit: int | None = None,
        offset: int | None = None,
        category_id: Any | None = None,
    ) -> Any:
        """获取创作者热门课程/Get creator hot course

        ``GET /api/v1/douyin/creator/fetch_creator_hot_course``
        """
        params = _drop_none({
            "order": order,
            "limit": limit,
            "offset": offset,
            "category_id": category_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_hot_course", params=params)

    async def fetch_creator_content_category(
        self,
    ) -> Any:
        """获取创作者内容创作合集分类/Get creator content creation category

        ``GET /api/v1/douyin/creator/fetch_creator_content_category``
        """
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_content_category")

    async def fetch_creator_content_course(
        self,
        *,
        category_id: int,
        order: int | None = None,
        limit: int | None = None,
        offset: int | None = None,
    ) -> Any:
        """获取创作者内容创作课程/Get creator content creation course

        ``GET /api/v1/douyin/creator/fetch_creator_content_course``
        """
        params = _drop_none({
            "category_id": category_id,
            "order": order,
            "limit": limit,
            "offset": offset,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_creator_content_course", params=params)

    async def fetch_video_danmaku_list(
        self,
        *,
        item_id: str,
        count: int | None = None,
        offset: int | None = None,
        order_type: int | None = None,
        is_blocked: bool | None = None,
    ) -> Any:
        """获取作品弹幕列表/Get video danmaku list

        ``GET /api/v1/douyin/creator/fetch_video_danmaku_list``
        """
        params = _drop_none({
            "item_id": item_id,
            "count": count,
            "offset": offset,
            "order_type": order_type,
            "is_blocked": is_blocked,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_video_danmaku_list", params=params)

    async def fetch_user_search(
        self,
        *,
        user_name: str,
    ) -> Any:
        """搜索用户/Search users

        ``GET /api/v1/douyin/creator/fetch_user_search``
        """
        params = _drop_none({
            "user_name": user_name,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_user_search", params=params)

    async def fetch_mission_task_list(
        self,
        *,
        cursor: int | None = None,
        limit: int | None = None,
        mission_type: int | None = None,
        tab_scene: int | None = None,
        industry_lv1: int | None = None,
        industry_lv2: int | None = None,
        platform_channel: Any | None = None,
        pay_type: Any | None = None,
        greater_than_cost_progress: Any | None = None,
        publish_time_start: Any | None = None,
        quick_selector_scene: Any | None = None,
        keyword: Any | None = None,
    ) -> Any:
        """获取商单任务列表/Get mission task list

        ``GET /api/v1/douyin/creator/fetch_mission_task_list``
        """
        params = _drop_none({
            "cursor": cursor,
            "limit": limit,
            "mission_type": mission_type,
            "tab_scene": tab_scene,
            "industry_lv1": industry_lv1,
            "industry_lv2": industry_lv2,
            "platform_channel": platform_channel,
            "pay_type": pay_type,
            "greater_than_cost_progress": greater_than_cost_progress,
            "publish_time_start": publish_time_start,
            "quick_selector_scene": quick_selector_scene,
            "keyword": keyword,
        })
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_mission_task_list", params=params)

    async def fetch_industry_category_config(
        self,
    ) -> Any:
        """获取行业分类配置/Get industry category config

        ``GET /api/v1/douyin/creator/fetch_industry_category_config``
        """
        return await self._client._request("GET", "/api/v1/douyin/creator/fetch_industry_category_config")
