# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Instagram-V3-API resource.

OpenAPI tag: ``Instagram-V3-API``
SDK attribute: ``client.instagram_v3`` / ``async_client.instagram_v3``

Endpoints: 32
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncInstagramV3", "InstagramV3"]


class InstagramV3(SyncResource):
    """Sync ``Instagram-V3-API`` resource (32 endpoints)."""

    def search_users(
        self,
        *,
        query: str,
        rank_token: str | None = None,
    ) -> Any:
        """搜索用户/Search users

        ``GET /api/v1/instagram/v3/search_users``
        """
        params = _drop_none({
            "query": query,
            "rank_token": rank_token,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/search_users", params=params)

    def search_hashtags(
        self,
        *,
        query: str,
        rank_token: str | None = None,
    ) -> Any:
        """搜索话题标签/Search hashtags

        ``GET /api/v1/instagram/v3/search_hashtags``
        """
        params = _drop_none({
            "query": query,
            "rank_token": rank_token,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/search_hashtags", params=params)

    def search_places(
        self,
        *,
        query: str,
        rank_token: str | None = None,
    ) -> Any:
        """搜索地点/Search places

        ``GET /api/v1/instagram/v3/search_places``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        params = _drop_none({
            "query": query,
            "rank_token": rank_token,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/search_places", params=params)

    def general_search(
        self,
        *,
        query: str,
        next_max_id: str | None = None,
        rank_token: str | None = None,
        enable_metadata: bool | None = None,
    ) -> Any:
        """综合搜索（支持分页）/General search (with pagination)

        ``GET /api/v1/instagram/v3/general_search``
        """
        params = _drop_none({
            "query": query,
            "next_max_id": next_max_id,
            "rank_token": rank_token,
            "enable_metadata": enable_metadata,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/general_search", params=params)

    def get_user_id_by_username(
        self,
        *,
        username: str,
    ) -> Any:
        """通过用户名获取用户ID/Get user ID by username

        ``GET /api/v1/instagram/v3/get_user_id_by_username``
        """
        params = _drop_none({
            "username": username,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_id_by_username", params=params)

    def get_user_profile(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
    ) -> Any:
        """获取用户信息/Get user profile

        ``GET /api/v1/instagram/v3/get_user_profile``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_profile", params=params)

    def get_user_brief(
        self,
        *,
        user_id: str,
        username: str,
    ) -> Any:
        """获取用户短详情/Get user brief info

        ``GET /api/v1/instagram/v3/get_user_brief``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_brief", params=params)

    def get_user_posts(
        self,
        *,
        username: str,
        first: int | None = None,
        after: str | None = None,
        before: str | None = None,
        last: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取用户帖子列表/Get user posts

        ``GET /api/v1/instagram/v3/get_user_posts``
        """
        params = _drop_none({
            "username": username,
            "first": first,
            "after": after,
            "before": before,
            "last": last,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_posts", params=params)

    def get_user_tagged_posts(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
        first: int | None = None,
        after: str | None = None,
        before: str | None = None,
        last: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取用户被标记的帖子/Get user tagged posts

        ``GET /api/v1/instagram/v3/get_user_tagged_posts``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
            "first": first,
            "after": after,
            "before": before,
            "last": last,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_tagged_posts", params=params)

    def get_user_reels(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
        first: int | None = None,
        after: str | None = None,
        before: str | None = None,
        last: int | None = None,
        page_size: int | None = None,
    ) -> Any:
        """获取用户Reels列表/Get user reels

        ``GET /api/v1/instagram/v3/get_user_reels``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
            "first": first,
            "after": after,
            "before": before,
            "last": last,
            "page_size": page_size,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_reels", params=params)

    def get_user_highlights(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
        first: int | None = None,
        after: str | None = None,
        before: str | None = None,
        last: int | None = None,
    ) -> Any:
        """获取用户精选Highlights列表/Get user highlights

        ``GET /api/v1/instagram/v3/get_user_highlights``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
            "first": first,
            "after": after,
            "before": before,
            "last": last,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_highlights", params=params)

    def get_highlight_stories(
        self,
        *,
        highlight_id: str,
        reel_ids: str | None = None,
        first: int | None = None,
        last: int | None = None,
    ) -> Any:
        """获取Highlight精选详情/Get highlight stories

        ``GET /api/v1/instagram/v3/get_highlight_stories``
        """
        params = _drop_none({
            "highlight_id": highlight_id,
            "reel_ids": reel_ids,
            "first": first,
            "last": last,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_highlight_stories", params=params)

    def get_user_about(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
    ) -> Any:
        """获取用户账户简介/Get user about info

        ``GET /api/v1/instagram/v3/get_user_about``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_about", params=params)

    def get_user_former_usernames(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
    ) -> Any:
        """获取用户曾用用户名/Get user former usernames

        ``GET /api/v1/instagram/v3/get_user_former_usernames``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_former_usernames", params=params)

    def get_user_stories(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
    ) -> Any:
        """获取用户Stories（快拍）/Get user stories

        ``GET /api/v1/instagram/v3/get_user_stories``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_stories", params=params)

    def get_recommended_reels(
        self,
        *,
        first: int | None = None,
        after: str | None = None,
    ) -> Any:
        """获取Reels推荐列表/Get recommended Reels feed

        ``GET /api/v1/instagram/v3/get_recommended_reels``
        """
        params = _drop_none({
            "first": first,
            "after": after,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_recommended_reels", params=params)

    def get_post_info(
        self,
        *,
        media_id: Any | None = None,
        url: Any | None = None,
    ) -> Any:
        """获取帖子详情/Get post info (media_id or URL)

        ``GET /api/v1/instagram/v3/get_post_info``
        """
        params = _drop_none({
            "media_id": media_id,
            "url": url,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_post_info", params=params)

    def get_post_info_by_code(
        self,
        *,
        code: str,
    ) -> Any:
        """获取帖子详情(code)/Get post info by shortcode

        ``GET /api/v1/instagram/v3/get_post_info_by_code``
        """
        params = _drop_none({
            "code": code,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_post_info_by_code", params=params)

    def get_post_comments(
        self,
        *,
        code: str,
        min_id: str | None = None,
        sort_order: str | None = None,
    ) -> Any:
        """获取帖子评论/Get post comments

        ``GET /api/v1/instagram/v3/get_post_comments``
        """
        params = _drop_none({
            "code": code,
            "min_id": min_id,
            "sort_order": sort_order,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_post_comments", params=params)

    def get_comment_replies(
        self,
        *,
        media_id: str,
        comment_id: str,
        min_id: str | None = None,
    ) -> Any:
        """获取评论的子评论/回复/Get comment replies

        ``GET /api/v1/instagram/v3/get_comment_replies``
        """
        params = _drop_none({
            "media_id": media_id,
            "comment_id": comment_id,
            "min_id": min_id,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_comment_replies", params=params)

    def get_post_oembed(
        self,
        *,
        url: str,
        hidecaption: bool | None = None,
        maxwidth: int | None = None,
    ) -> Any:
        """获取帖子oEmbed内嵌信息/Get post oEmbed info

        ``GET /api/v1/instagram/v3/get_post_oembed``
        """
        params = _drop_none({
            "url": url,
            "hidecaption": hidecaption,
            "maxwidth": maxwidth,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_post_oembed", params=params)

    def translate_comment(
        self,
        *,
        comment_id: str,
    ) -> Any:
        """翻译评论/帖子文本/Translate comment or caption

        ``GET /api/v1/instagram/v3/translate_comment``
        """
        params = _drop_none({
            "comment_id": comment_id,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/translate_comment", params=params)

    def bulk_translate_comments(
        self,
        *,
        comment_ids: str,
    ) -> Any:
        """批量翻译评论/Bulk translate comments

        ``GET /api/v1/instagram/v3/bulk_translate_comments``
        """
        params = _drop_none({
            "comment_ids": comment_ids,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/bulk_translate_comments", params=params)

    def get_explore(
        self,
        *,
        max_id: str | None = None,
    ) -> Any:
        """获取探索页推荐帖子/Get explore feed

        ``GET /api/v1/instagram/v3/get_explore``
        """
        params = _drop_none({
            "max_id": max_id,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_explore", params=params)

    def get_user_following(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
        count: int | None = None,
        max_id: str | None = None,
    ) -> Any:
        """获取用户关注列表/Get user following list

        ``GET /api/v1/instagram/v3/get_user_following``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
            "count": count,
            "max_id": max_id,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_following", params=params)

    def get_user_followers(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
        count: int | None = None,
        max_id: str | None = None,
    ) -> Any:
        """获取用户粉丝列表/Get user followers list

        ``GET /api/v1/instagram/v3/get_user_followers``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
            "count": count,
            "max_id": max_id,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_user_followers", params=params)

    def get_location_info(
        self,
        *,
        location_id: str,
        show_nearby: bool | None = None,
    ) -> Any:
        """获取地点详情/Get location info

        ``GET /api/v1/instagram/v3/get_location_info``
        """
        params = _drop_none({
            "location_id": location_id,
            "show_nearby": show_nearby,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_location_info", params=params)

    def get_location_posts(
        self,
        *,
        location_id: str,
        tab: str | None = None,
        first: int | None = None,
        after: str | None = None,
        page_size_override: int | None = None,
    ) -> Any:
        """获取地点相关帖子/Get location posts

        ``GET /api/v1/instagram/v3/get_location_posts``
        """
        params = _drop_none({
            "location_id": location_id,
            "tab": tab,
            "first": first,
            "after": after,
            "page_size_override": page_size_override,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_location_posts", params=params)

    def get_location_nearby(
        self,
        *,
        location_id: str,
    ) -> Any:
        """获取地点附近内容/Get nearby location content

        ``GET /api/v1/instagram/v3/get_location_nearby``
        """
        params = _drop_none({
            "location_id": location_id,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/get_location_nearby", params=params)

    def shortcode_to_media_id(
        self,
        *,
        shortcode: str,
    ) -> Any:
        """短码转媒体ID/Convert shortcode to media ID

        ``GET /api/v1/instagram/v3/shortcode_to_media_id``
        """
        params = _drop_none({
            "shortcode": shortcode,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/shortcode_to_media_id", params=params)

    def media_id_to_shortcode(
        self,
        *,
        media_id: str,
    ) -> Any:
        """媒体ID转短码/Convert media ID to shortcode

        ``GET /api/v1/instagram/v3/media_id_to_shortcode``
        """
        params = _drop_none({
            "media_id": media_id,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/media_id_to_shortcode", params=params)

    def extract_shortcode(
        self,
        *,
        url: str,
    ) -> Any:
        """从URL提取短码/Extract shortcode from URL

        ``GET /api/v1/instagram/v3/extract_shortcode``
        """
        params = _drop_none({
            "url": url,
        })
        return self._client._request("GET", "/api/v1/instagram/v3/extract_shortcode", params=params)


class AsyncInstagramV3(AsyncResource):
    """Async ``Instagram-V3-API`` resource (32 endpoints)."""

    async def search_users(
        self,
        *,
        query: str,
        rank_token: str | None = None,
    ) -> Any:
        """搜索用户/Search users

        ``GET /api/v1/instagram/v3/search_users``
        """
        params = _drop_none({
            "query": query,
            "rank_token": rank_token,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/search_users", params=params)

    async def search_hashtags(
        self,
        *,
        query: str,
        rank_token: str | None = None,
    ) -> Any:
        """搜索话题标签/Search hashtags

        ``GET /api/v1/instagram/v3/search_hashtags``
        """
        params = _drop_none({
            "query": query,
            "rank_token": rank_token,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/search_hashtags", params=params)

    async def search_places(
        self,
        *,
        query: str,
        rank_token: str | None = None,
    ) -> Any:
        """搜索地点/Search places

        ``GET /api/v1/instagram/v3/search_places``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        params = _drop_none({
            "query": query,
            "rank_token": rank_token,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/search_places", params=params)

    async def general_search(
        self,
        *,
        query: str,
        next_max_id: str | None = None,
        rank_token: str | None = None,
        enable_metadata: bool | None = None,
    ) -> Any:
        """综合搜索（支持分页）/General search (with pagination)

        ``GET /api/v1/instagram/v3/general_search``
        """
        params = _drop_none({
            "query": query,
            "next_max_id": next_max_id,
            "rank_token": rank_token,
            "enable_metadata": enable_metadata,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/general_search", params=params)

    async def get_user_id_by_username(
        self,
        *,
        username: str,
    ) -> Any:
        """通过用户名获取用户ID/Get user ID by username

        ``GET /api/v1/instagram/v3/get_user_id_by_username``
        """
        params = _drop_none({
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_id_by_username", params=params)

    async def get_user_profile(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
    ) -> Any:
        """获取用户信息/Get user profile

        ``GET /api/v1/instagram/v3/get_user_profile``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_profile", params=params)

    async def get_user_brief(
        self,
        *,
        user_id: str,
        username: str,
    ) -> Any:
        """获取用户短详情/Get user brief info

        ``GET /api/v1/instagram/v3/get_user_brief``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_brief", params=params)

    async def get_user_posts(
        self,
        *,
        username: str,
        first: int | None = None,
        after: str | None = None,
        before: str | None = None,
        last: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取用户帖子列表/Get user posts

        ``GET /api/v1/instagram/v3/get_user_posts``
        """
        params = _drop_none({
            "username": username,
            "first": first,
            "after": after,
            "before": before,
            "last": last,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_posts", params=params)

    async def get_user_tagged_posts(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
        first: int | None = None,
        after: str | None = None,
        before: str | None = None,
        last: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取用户被标记的帖子/Get user tagged posts

        ``GET /api/v1/instagram/v3/get_user_tagged_posts``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
            "first": first,
            "after": after,
            "before": before,
            "last": last,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_tagged_posts", params=params)

    async def get_user_reels(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
        first: int | None = None,
        after: str | None = None,
        before: str | None = None,
        last: int | None = None,
        page_size: int | None = None,
    ) -> Any:
        """获取用户Reels列表/Get user reels

        ``GET /api/v1/instagram/v3/get_user_reels``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
            "first": first,
            "after": after,
            "before": before,
            "last": last,
            "page_size": page_size,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_reels", params=params)

    async def get_user_highlights(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
        first: int | None = None,
        after: str | None = None,
        before: str | None = None,
        last: int | None = None,
    ) -> Any:
        """获取用户精选Highlights列表/Get user highlights

        ``GET /api/v1/instagram/v3/get_user_highlights``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
            "first": first,
            "after": after,
            "before": before,
            "last": last,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_highlights", params=params)

    async def get_highlight_stories(
        self,
        *,
        highlight_id: str,
        reel_ids: str | None = None,
        first: int | None = None,
        last: int | None = None,
    ) -> Any:
        """获取Highlight精选详情/Get highlight stories

        ``GET /api/v1/instagram/v3/get_highlight_stories``
        """
        params = _drop_none({
            "highlight_id": highlight_id,
            "reel_ids": reel_ids,
            "first": first,
            "last": last,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_highlight_stories", params=params)

    async def get_user_about(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
    ) -> Any:
        """获取用户账户简介/Get user about info

        ``GET /api/v1/instagram/v3/get_user_about``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_about", params=params)

    async def get_user_former_usernames(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
    ) -> Any:
        """获取用户曾用用户名/Get user former usernames

        ``GET /api/v1/instagram/v3/get_user_former_usernames``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_former_usernames", params=params)

    async def get_user_stories(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
    ) -> Any:
        """获取用户Stories（快拍）/Get user stories

        ``GET /api/v1/instagram/v3/get_user_stories``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_stories", params=params)

    async def get_recommended_reels(
        self,
        *,
        first: int | None = None,
        after: str | None = None,
    ) -> Any:
        """获取Reels推荐列表/Get recommended Reels feed

        ``GET /api/v1/instagram/v3/get_recommended_reels``
        """
        params = _drop_none({
            "first": first,
            "after": after,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_recommended_reels", params=params)

    async def get_post_info(
        self,
        *,
        media_id: Any | None = None,
        url: Any | None = None,
    ) -> Any:
        """获取帖子详情/Get post info (media_id or URL)

        ``GET /api/v1/instagram/v3/get_post_info``
        """
        params = _drop_none({
            "media_id": media_id,
            "url": url,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_post_info", params=params)

    async def get_post_info_by_code(
        self,
        *,
        code: str,
    ) -> Any:
        """获取帖子详情(code)/Get post info by shortcode

        ``GET /api/v1/instagram/v3/get_post_info_by_code``
        """
        params = _drop_none({
            "code": code,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_post_info_by_code", params=params)

    async def get_post_comments(
        self,
        *,
        code: str,
        min_id: str | None = None,
        sort_order: str | None = None,
    ) -> Any:
        """获取帖子评论/Get post comments

        ``GET /api/v1/instagram/v3/get_post_comments``
        """
        params = _drop_none({
            "code": code,
            "min_id": min_id,
            "sort_order": sort_order,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_post_comments", params=params)

    async def get_comment_replies(
        self,
        *,
        media_id: str,
        comment_id: str,
        min_id: str | None = None,
    ) -> Any:
        """获取评论的子评论/回复/Get comment replies

        ``GET /api/v1/instagram/v3/get_comment_replies``
        """
        params = _drop_none({
            "media_id": media_id,
            "comment_id": comment_id,
            "min_id": min_id,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_comment_replies", params=params)

    async def get_post_oembed(
        self,
        *,
        url: str,
        hidecaption: bool | None = None,
        maxwidth: int | None = None,
    ) -> Any:
        """获取帖子oEmbed内嵌信息/Get post oEmbed info

        ``GET /api/v1/instagram/v3/get_post_oembed``
        """
        params = _drop_none({
            "url": url,
            "hidecaption": hidecaption,
            "maxwidth": maxwidth,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_post_oembed", params=params)

    async def translate_comment(
        self,
        *,
        comment_id: str,
    ) -> Any:
        """翻译评论/帖子文本/Translate comment or caption

        ``GET /api/v1/instagram/v3/translate_comment``
        """
        params = _drop_none({
            "comment_id": comment_id,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/translate_comment", params=params)

    async def bulk_translate_comments(
        self,
        *,
        comment_ids: str,
    ) -> Any:
        """批量翻译评论/Bulk translate comments

        ``GET /api/v1/instagram/v3/bulk_translate_comments``
        """
        params = _drop_none({
            "comment_ids": comment_ids,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/bulk_translate_comments", params=params)

    async def get_explore(
        self,
        *,
        max_id: str | None = None,
    ) -> Any:
        """获取探索页推荐帖子/Get explore feed

        ``GET /api/v1/instagram/v3/get_explore``
        """
        params = _drop_none({
            "max_id": max_id,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_explore", params=params)

    async def get_user_following(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
        count: int | None = None,
        max_id: str | None = None,
    ) -> Any:
        """获取用户关注列表/Get user following list

        ``GET /api/v1/instagram/v3/get_user_following``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
            "count": count,
            "max_id": max_id,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_following", params=params)

    async def get_user_followers(
        self,
        *,
        user_id: str | None = None,
        username: str | None = None,
        count: int | None = None,
        max_id: str | None = None,
    ) -> Any:
        """获取用户粉丝列表/Get user followers list

        ``GET /api/v1/instagram/v3/get_user_followers``
        """
        params = _drop_none({
            "user_id": user_id,
            "username": username,
            "count": count,
            "max_id": max_id,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_user_followers", params=params)

    async def get_location_info(
        self,
        *,
        location_id: str,
        show_nearby: bool | None = None,
    ) -> Any:
        """获取地点详情/Get location info

        ``GET /api/v1/instagram/v3/get_location_info``
        """
        params = _drop_none({
            "location_id": location_id,
            "show_nearby": show_nearby,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_location_info", params=params)

    async def get_location_posts(
        self,
        *,
        location_id: str,
        tab: str | None = None,
        first: int | None = None,
        after: str | None = None,
        page_size_override: int | None = None,
    ) -> Any:
        """获取地点相关帖子/Get location posts

        ``GET /api/v1/instagram/v3/get_location_posts``
        """
        params = _drop_none({
            "location_id": location_id,
            "tab": tab,
            "first": first,
            "after": after,
            "page_size_override": page_size_override,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_location_posts", params=params)

    async def get_location_nearby(
        self,
        *,
        location_id: str,
    ) -> Any:
        """获取地点附近内容/Get nearby location content

        ``GET /api/v1/instagram/v3/get_location_nearby``
        """
        params = _drop_none({
            "location_id": location_id,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/get_location_nearby", params=params)

    async def shortcode_to_media_id(
        self,
        *,
        shortcode: str,
    ) -> Any:
        """短码转媒体ID/Convert shortcode to media ID

        ``GET /api/v1/instagram/v3/shortcode_to_media_id``
        """
        params = _drop_none({
            "shortcode": shortcode,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/shortcode_to_media_id", params=params)

    async def media_id_to_shortcode(
        self,
        *,
        media_id: str,
    ) -> Any:
        """媒体ID转短码/Convert media ID to shortcode

        ``GET /api/v1/instagram/v3/media_id_to_shortcode``
        """
        params = _drop_none({
            "media_id": media_id,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/media_id_to_shortcode", params=params)

    async def extract_shortcode(
        self,
        *,
        url: str,
    ) -> Any:
        """从URL提取短码/Extract shortcode from URL

        ``GET /api/v1/instagram/v3/extract_shortcode``
        """
        params = _drop_none({
            "url": url,
        })
        return await self._client._request("GET", "/api/v1/instagram/v3/extract_shortcode", params=params)
