# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""WeChat-Channels-API resource.

OpenAPI tag: ``WeChat-Channels-API``
SDK attribute: ``client.wechat_channels`` / ``async_client.wechat_channels``

Endpoints: 12
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncWechatChannels", "WechatChannels"]


class WechatChannels(SyncResource):
    """Sync ``WeChat-Channels-API`` resource (12 endpoints)."""

    def fetch_default_search(
        self,
        *,
        keywords: str,
        session_buffer: str | None = None,
    ) -> Any:
        """微信视频号默认搜索/WeChat Channels Default Search

        ``POST /api/v1/wechat_channels/fetch_default_search``
        """
        json_body = _drop_none({
            "keywords": keywords,
            "session_buffer": session_buffer,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/fetch_default_search", json=json_body)

    def fetch_search_latest(
        self,
        *,
        keywords: str,
    ) -> Any:
        """微信视频号搜索最新视频/WeChat Channels Search Latest Videos

        ``GET /api/v1/wechat_channels/fetch_search_latest``
        """
        params = _drop_none({
            "keywords": keywords,
        })
        return self._client._request("GET", "/api/v1/wechat_channels/fetch_search_latest", params=params)

    def fetch_search_ordinary(
        self,
        *,
        keywords: str,
    ) -> Any:
        """微信视频号综合搜索/WeChat Channels Comprehensive Search

        ``GET /api/v1/wechat_channels/fetch_search_ordinary``
        """
        params = _drop_none({
            "keywords": keywords,
        })
        return self._client._request("GET", "/api/v1/wechat_channels/fetch_search_ordinary", params=params)

    def fetch_user_search(
        self,
        *,
        keywords: str,
        page: int | None = None,
    ) -> Any:
        """微信视频号用户搜索/WeChat Channels User Search

        ``GET /api/v1/wechat_channels/fetch_user_search``
        """
        params = _drop_none({
            "keywords": keywords,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/wechat_channels/fetch_user_search", params=params)

    def fetch_user_search_v2(
        self,
        *,
        keywords: str | None = None,
        page: int | None = None,
    ) -> Any:
        """微信视频号用户搜索V2/WeChat Channels User Search V2

        ``GET /api/v1/wechat_channels/fetch_user_search_v2``
        """
        params = _drop_none({
            "keywords": keywords,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/wechat_channels/fetch_user_search_v2", params=params)

    def fetch_video_detail(
        self,
        *,
        id: str | None = None,
        exportId: str | None = None,
    ) -> Any:
        """微信视频号视频详情/WeChat Channels Video Detail

        ``GET /api/v1/wechat_channels/fetch_video_detail``
        """
        params = _drop_none({
            "id": id,
            "exportId": exportId,
        })
        return self._client._request("GET", "/api/v1/wechat_channels/fetch_video_detail", params=params)

    def fetch_video_by_share_url(
        self,
        *,
        share_url: str,
    ) -> Any:
        """微信视频号分享详情/WeChat Channels Share Detail

        ``GET /api/v1/wechat_channels/fetch_video_by_share_url``
        """
        params = _drop_none({
            "share_url": share_url,
        })
        return self._client._request("GET", "/api/v1/wechat_channels/fetch_video_by_share_url", params=params)

    def fetch_home_page(
        self,
        *,
        username: str,
        last_buffer: str | None = None,
    ) -> Any:
        """微信视频号主页/WeChat Channels Home Page

        ``POST /api/v1/wechat_channels/fetch_home_page``
        """
        json_body = _drop_none({
            "username": username,
            "last_buffer": last_buffer,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/fetch_home_page", json=json_body)

    def fetch_comments(
        self,
        *,
        id: str,
        lastBuffer: str | None = None,
        comment_id: str | None = None,
    ) -> Any:
        """微信视频号评论/WeChat Channels Comments

        ``POST /api/v1/wechat_channels/fetch_comments``
        """
        json_body = _drop_none({
            "id": id,
            "lastBuffer": lastBuffer,
            "comment_id": comment_id,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/fetch_comments", json=json_body)

    def fetch_live_history(
        self,
        *,
        username: str,
    ) -> Any:
        """微信视频号直播回放/WeChat Channels Live History

        ``GET /api/v1/wechat_channels/fetch_live_history``
        """
        params = _drop_none({
            "username": username,
        })
        return self._client._request("GET", "/api/v1/wechat_channels/fetch_live_history", params=params)

    def fetch_search_channels(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        sort_type: str | None = None,
    ) -> Any:
        """微信视频号搜索/Search WeChat Channels

        ``GET /api/v1/wechat_channels/fetch_search_channels``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "sort_type": sort_type,
        })
        return self._client._request("GET", "/api/v1/wechat_channels/fetch_search_channels", params=params)

    def fetch_hot_words(
        self,
    ) -> Any:
        """微信视频号热门话题/WeChat Channels Hot Topics

        ``GET /api/v1/wechat_channels/fetch_hot_words``
        """
        return self._client._request("GET", "/api/v1/wechat_channels/fetch_hot_words")


class AsyncWechatChannels(AsyncResource):
    """Async ``WeChat-Channels-API`` resource (12 endpoints)."""

    async def fetch_default_search(
        self,
        *,
        keywords: str,
        session_buffer: str | None = None,
    ) -> Any:
        """微信视频号默认搜索/WeChat Channels Default Search

        ``POST /api/v1/wechat_channels/fetch_default_search``
        """
        json_body = _drop_none({
            "keywords": keywords,
            "session_buffer": session_buffer,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/fetch_default_search", json=json_body)

    async def fetch_search_latest(
        self,
        *,
        keywords: str,
    ) -> Any:
        """微信视频号搜索最新视频/WeChat Channels Search Latest Videos

        ``GET /api/v1/wechat_channels/fetch_search_latest``
        """
        params = _drop_none({
            "keywords": keywords,
        })
        return await self._client._request("GET", "/api/v1/wechat_channels/fetch_search_latest", params=params)

    async def fetch_search_ordinary(
        self,
        *,
        keywords: str,
    ) -> Any:
        """微信视频号综合搜索/WeChat Channels Comprehensive Search

        ``GET /api/v1/wechat_channels/fetch_search_ordinary``
        """
        params = _drop_none({
            "keywords": keywords,
        })
        return await self._client._request("GET", "/api/v1/wechat_channels/fetch_search_ordinary", params=params)

    async def fetch_user_search(
        self,
        *,
        keywords: str,
        page: int | None = None,
    ) -> Any:
        """微信视频号用户搜索/WeChat Channels User Search

        ``GET /api/v1/wechat_channels/fetch_user_search``
        """
        params = _drop_none({
            "keywords": keywords,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/wechat_channels/fetch_user_search", params=params)

    async def fetch_user_search_v2(
        self,
        *,
        keywords: str | None = None,
        page: int | None = None,
    ) -> Any:
        """微信视频号用户搜索V2/WeChat Channels User Search V2

        ``GET /api/v1/wechat_channels/fetch_user_search_v2``
        """
        params = _drop_none({
            "keywords": keywords,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/wechat_channels/fetch_user_search_v2", params=params)

    async def fetch_video_detail(
        self,
        *,
        id: str | None = None,
        exportId: str | None = None,
    ) -> Any:
        """微信视频号视频详情/WeChat Channels Video Detail

        ``GET /api/v1/wechat_channels/fetch_video_detail``
        """
        params = _drop_none({
            "id": id,
            "exportId": exportId,
        })
        return await self._client._request("GET", "/api/v1/wechat_channels/fetch_video_detail", params=params)

    async def fetch_video_by_share_url(
        self,
        *,
        share_url: str,
    ) -> Any:
        """微信视频号分享详情/WeChat Channels Share Detail

        ``GET /api/v1/wechat_channels/fetch_video_by_share_url``
        """
        params = _drop_none({
            "share_url": share_url,
        })
        return await self._client._request("GET", "/api/v1/wechat_channels/fetch_video_by_share_url", params=params)

    async def fetch_home_page(
        self,
        *,
        username: str,
        last_buffer: str | None = None,
    ) -> Any:
        """微信视频号主页/WeChat Channels Home Page

        ``POST /api/v1/wechat_channels/fetch_home_page``
        """
        json_body = _drop_none({
            "username": username,
            "last_buffer": last_buffer,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/fetch_home_page", json=json_body)

    async def fetch_comments(
        self,
        *,
        id: str,
        lastBuffer: str | None = None,
        comment_id: str | None = None,
    ) -> Any:
        """微信视频号评论/WeChat Channels Comments

        ``POST /api/v1/wechat_channels/fetch_comments``
        """
        json_body = _drop_none({
            "id": id,
            "lastBuffer": lastBuffer,
            "comment_id": comment_id,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/fetch_comments", json=json_body)

    async def fetch_live_history(
        self,
        *,
        username: str,
    ) -> Any:
        """微信视频号直播回放/WeChat Channels Live History

        ``GET /api/v1/wechat_channels/fetch_live_history``
        """
        params = _drop_none({
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/wechat_channels/fetch_live_history", params=params)

    async def fetch_search_channels(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        sort_type: str | None = None,
    ) -> Any:
        """微信视频号搜索/Search WeChat Channels

        ``GET /api/v1/wechat_channels/fetch_search_channels``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "sort_type": sort_type,
        })
        return await self._client._request("GET", "/api/v1/wechat_channels/fetch_search_channels", params=params)

    async def fetch_hot_words(
        self,
    ) -> Any:
        """微信视频号热门话题/WeChat Channels Hot Topics

        ``GET /api/v1/wechat_channels/fetch_hot_words``
        """
        return await self._client._request("GET", "/api/v1/wechat_channels/fetch_hot_words")
