# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Xiaohongshu-App-V2-API resource.

OpenAPI tag: ``Xiaohongshu-App-V2-API``
SDK attribute: ``client.xiaohongshu_app_v2`` / ``async_client.xiaohongshu_app_v2``

Endpoints: 20
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncXiaohongshuAppV2", "XiaohongshuAppV2"]


class XiaohongshuAppV2(SyncResource):
    """Sync ``Xiaohongshu-App-V2-API`` resource (20 endpoints)."""

    def get_image_note_detail(
        self,
        *,
        note_id: str | None = None,
        share_text: str | None = None,
    ) -> Any:
        """获取图文笔记详情/Get image note detail

        ``GET /api/v1/xiaohongshu/app_v2/get_image_note_detail``
        """
        params = _drop_none({
            "note_id": note_id,
            "share_text": share_text,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_image_note_detail", params=params)

    def get_video_note_detail(
        self,
        *,
        note_id: str | None = None,
        share_text: str | None = None,
    ) -> Any:
        """获取视频笔记详情/Get video note detail

        ``GET /api/v1/xiaohongshu/app_v2/get_video_note_detail``
        """
        params = _drop_none({
            "note_id": note_id,
            "share_text": share_text,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_video_note_detail", params=params)

    def get_note_comments(
        self,
        *,
        note_id: str | None = None,
        share_text: str | None = None,
        cursor: str | None = None,
        index: int | None = None,
        pageArea: str | None = None,
        sort_strategy: str | None = None,
    ) -> Any:
        """获取笔记评论列表/Get note comments

        ``GET /api/v1/xiaohongshu/app_v2/get_note_comments``
        """
        params = _drop_none({
            "note_id": note_id,
            "share_text": share_text,
            "cursor": cursor,
            "index": index,
            "pageArea": pageArea,
            "sort_strategy": sort_strategy,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_note_comments", params=params)

    def get_note_sub_comments(
        self,
        *,
        comment_id: str,
        note_id: str | None = None,
        share_text: str | None = None,
        cursor: str | None = None,
        index: int | None = None,
    ) -> Any:
        """获取笔记二级评论列表/Get note sub comments

        ``GET /api/v1/xiaohongshu/app_v2/get_note_sub_comments``
        """
        params = _drop_none({
            "note_id": note_id,
            "share_text": share_text,
            "comment_id": comment_id,
            "cursor": cursor,
            "index": index,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_note_sub_comments", params=params)

    def get_user_info(
        self,
        *,
        user_id: str | None = None,
        share_text: str | None = None,
    ) -> Any:
        """获取用户信息/Get user info

        ``GET /api/v1/xiaohongshu/app_v2/get_user_info``
        """
        params = _drop_none({
            "user_id": user_id,
            "share_text": share_text,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_user_info", params=params)

    def get_user_posted_notes(
        self,
        *,
        user_id: str | None = None,
        share_text: str | None = None,
        cursor: str | None = None,
    ) -> Any:
        """获取用户笔记列表/Get user posted notes

        ``GET /api/v1/xiaohongshu/app_v2/get_user_posted_notes``
        """
        params = _drop_none({
            "user_id": user_id,
            "share_text": share_text,
            "cursor": cursor,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_user_posted_notes", params=params)

    def get_user_faved_notes(
        self,
        *,
        user_id: str | None = None,
        share_text: str | None = None,
        cursor: str | None = None,
    ) -> Any:
        """获取用户收藏笔记列表/Get user faved notes

        ``GET /api/v1/xiaohongshu/app_v2/get_user_faved_notes``
        """
        params = _drop_none({
            "user_id": user_id,
            "share_text": share_text,
            "cursor": cursor,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_user_faved_notes", params=params)

    def search_notes(
        self,
        *,
        keyword: str,
        page: int | None = None,
        sort_type: str | None = None,
        note_type: str | None = None,
        time_filter: str | None = None,
        search_id: str | None = None,
        search_session_id: str | None = None,
        source: str | None = None,
        ai_mode: int | None = None,
    ) -> Any:
        """搜索笔记/Search notes

        ``GET /api/v1/xiaohongshu/app_v2/search_notes``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "sort_type": sort_type,
            "note_type": note_type,
            "time_filter": time_filter,
            "search_id": search_id,
            "search_session_id": search_session_id,
            "source": source,
            "ai_mode": ai_mode,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/search_notes", params=params)

    def search_users(
        self,
        *,
        keyword: str,
        page: int | None = None,
        search_id: str | None = None,
        source: str | None = None,
    ) -> Any:
        """搜索用户/Search users

        ``GET /api/v1/xiaohongshu/app_v2/search_users``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "search_id": search_id,
            "source": source,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/search_users", params=params)

    def search_images(
        self,
        *,
        keyword: str,
        page: int | None = None,
        search_id: str | None = None,
        search_session_id: str | None = None,
        word_request_id: str | None = None,
        source: str | None = None,
    ) -> Any:
        """搜索图片/Search images

        ``GET /api/v1/xiaohongshu/app_v2/search_images``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "search_id": search_id,
            "search_session_id": search_session_id,
            "word_request_id": word_request_id,
            "source": source,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/search_images", params=params)

    def search_products(
        self,
        *,
        keyword: str,
        page: int | None = None,
        search_id: str | None = None,
        source: str | None = None,
    ) -> Any:
        """搜索商品/Search products

        ``GET /api/v1/xiaohongshu/app_v2/search_products``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "search_id": search_id,
            "source": source,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/search_products", params=params)

    def search_groups(
        self,
        *,
        keyword: str,
        page_no: int | None = None,
        search_id: str | None = None,
        source: str | None = None,
        is_recommend: int | None = None,
    ) -> Any:
        """搜索群聊/Search groups

        ``GET /api/v1/xiaohongshu/app_v2/search_groups``
        """
        params = _drop_none({
            "keyword": keyword,
            "page_no": page_no,
            "search_id": search_id,
            "source": source,
            "is_recommend": is_recommend,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/search_groups", params=params)

    def get_product_detail(
        self,
        *,
        sku_id: str,
        source: str | None = None,
        pre_page: str | None = None,
    ) -> Any:
        """获取商品详情/Get product detail

        ``GET /api/v1/xiaohongshu/app_v2/get_product_detail``
        """
        params = _drop_none({
            "sku_id": sku_id,
            "source": source,
            "pre_page": pre_page,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_product_detail", params=params)

    def get_product_review_overview(
        self,
        *,
        sku_id: str,
        tab: int | None = None,
    ) -> Any:
        """获取商品评论总览/Get product review overview

        ``GET /api/v1/xiaohongshu/app_v2/get_product_review_overview``
        """
        params = _drop_none({
            "sku_id": sku_id,
            "tab": tab,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_product_review_overview", params=params)

    def get_product_reviews(
        self,
        *,
        sku_id: str,
        page: int | None = None,
        sort_strategy_type: int | None = None,
        share_pics_only: int | None = None,
        from_page: str | None = None,
    ) -> Any:
        """获取商品评论列表/Get product reviews

        ``GET /api/v1/xiaohongshu/app_v2/get_product_reviews``
        """
        params = _drop_none({
            "sku_id": sku_id,
            "page": page,
            "sort_strategy_type": sort_strategy_type,
            "share_pics_only": share_pics_only,
            "from_page": from_page,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_product_reviews", params=params)

    def get_product_recommendations(
        self,
        *,
        sku_id: str,
        cursor_score: str | None = None,
        region: str | None = None,
    ) -> Any:
        """获取商品推荐列表/Get product recommendations

        ``GET /api/v1/xiaohongshu/app_v2/get_product_recommendations``
        """
        params = _drop_none({
            "sku_id": sku_id,
            "cursor_score": cursor_score,
            "region": region,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_product_recommendations", params=params)

    def get_topic_info(
        self,
        *,
        page_id: str,
        source: str | None = None,
        note_id: str | None = None,
    ) -> Any:
        """获取话题详情/Get topic info

        ``GET /api/v1/xiaohongshu/app_v2/get_topic_info``
        """
        params = _drop_none({
            "page_id": page_id,
            "source": source,
            "note_id": note_id,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_topic_info", params=params)

    def get_topic_feed(
        self,
        *,
        page_id: str,
        sort: str | None = None,
        cursor_score: str | None = None,
        last_note_id: str | None = None,
        last_note_ct: str | None = None,
        session_id: str | None = None,
        first_load_time: str | None = None,
        source: str | None = None,
    ) -> Any:
        """获取话题笔记列表/Get topic feed

        ``GET /api/v1/xiaohongshu/app_v2/get_topic_feed``
        """
        params = _drop_none({
            "page_id": page_id,
            "sort": sort,
            "cursor_score": cursor_score,
            "last_note_id": last_note_id,
            "last_note_ct": last_note_ct,
            "session_id": session_id,
            "first_load_time": first_load_time,
            "source": source,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_topic_feed", params=params)

    def get_creator_inspiration_feed(
        self,
        *,
        cursor: str | None = None,
        tab: int | None = None,
        source: str | None = None,
    ) -> Any:
        """获取创作者推荐灵感列表/Get creator inspiration feed

        ``GET /api/v1/xiaohongshu/app_v2/get_creator_inspiration_feed``
        """
        params = _drop_none({
            "cursor": cursor,
            "tab": tab,
            "source": source,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_creator_inspiration_feed", params=params)

    def get_creator_hot_inspiration_feed(
        self,
        *,
        cursor: str | None = None,
    ) -> Any:
        """获取创作者热点灵感列表/Get creator hot inspiration feed

        ``GET /api/v1/xiaohongshu/app_v2/get_creator_hot_inspiration_feed``
        """
        params = _drop_none({
            "cursor": cursor,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_creator_hot_inspiration_feed", params=params)


class AsyncXiaohongshuAppV2(AsyncResource):
    """Async ``Xiaohongshu-App-V2-API`` resource (20 endpoints)."""

    async def get_image_note_detail(
        self,
        *,
        note_id: str | None = None,
        share_text: str | None = None,
    ) -> Any:
        """获取图文笔记详情/Get image note detail

        ``GET /api/v1/xiaohongshu/app_v2/get_image_note_detail``
        """
        params = _drop_none({
            "note_id": note_id,
            "share_text": share_text,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_image_note_detail", params=params)

    async def get_video_note_detail(
        self,
        *,
        note_id: str | None = None,
        share_text: str | None = None,
    ) -> Any:
        """获取视频笔记详情/Get video note detail

        ``GET /api/v1/xiaohongshu/app_v2/get_video_note_detail``
        """
        params = _drop_none({
            "note_id": note_id,
            "share_text": share_text,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_video_note_detail", params=params)

    async def get_note_comments(
        self,
        *,
        note_id: str | None = None,
        share_text: str | None = None,
        cursor: str | None = None,
        index: int | None = None,
        pageArea: str | None = None,
        sort_strategy: str | None = None,
    ) -> Any:
        """获取笔记评论列表/Get note comments

        ``GET /api/v1/xiaohongshu/app_v2/get_note_comments``
        """
        params = _drop_none({
            "note_id": note_id,
            "share_text": share_text,
            "cursor": cursor,
            "index": index,
            "pageArea": pageArea,
            "sort_strategy": sort_strategy,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_note_comments", params=params)

    async def get_note_sub_comments(
        self,
        *,
        comment_id: str,
        note_id: str | None = None,
        share_text: str | None = None,
        cursor: str | None = None,
        index: int | None = None,
    ) -> Any:
        """获取笔记二级评论列表/Get note sub comments

        ``GET /api/v1/xiaohongshu/app_v2/get_note_sub_comments``
        """
        params = _drop_none({
            "note_id": note_id,
            "share_text": share_text,
            "comment_id": comment_id,
            "cursor": cursor,
            "index": index,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_note_sub_comments", params=params)

    async def get_user_info(
        self,
        *,
        user_id: str | None = None,
        share_text: str | None = None,
    ) -> Any:
        """获取用户信息/Get user info

        ``GET /api/v1/xiaohongshu/app_v2/get_user_info``
        """
        params = _drop_none({
            "user_id": user_id,
            "share_text": share_text,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_user_info", params=params)

    async def get_user_posted_notes(
        self,
        *,
        user_id: str | None = None,
        share_text: str | None = None,
        cursor: str | None = None,
    ) -> Any:
        """获取用户笔记列表/Get user posted notes

        ``GET /api/v1/xiaohongshu/app_v2/get_user_posted_notes``
        """
        params = _drop_none({
            "user_id": user_id,
            "share_text": share_text,
            "cursor": cursor,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_user_posted_notes", params=params)

    async def get_user_faved_notes(
        self,
        *,
        user_id: str | None = None,
        share_text: str | None = None,
        cursor: str | None = None,
    ) -> Any:
        """获取用户收藏笔记列表/Get user faved notes

        ``GET /api/v1/xiaohongshu/app_v2/get_user_faved_notes``
        """
        params = _drop_none({
            "user_id": user_id,
            "share_text": share_text,
            "cursor": cursor,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_user_faved_notes", params=params)

    async def search_notes(
        self,
        *,
        keyword: str,
        page: int | None = None,
        sort_type: str | None = None,
        note_type: str | None = None,
        time_filter: str | None = None,
        search_id: str | None = None,
        search_session_id: str | None = None,
        source: str | None = None,
        ai_mode: int | None = None,
    ) -> Any:
        """搜索笔记/Search notes

        ``GET /api/v1/xiaohongshu/app_v2/search_notes``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "sort_type": sort_type,
            "note_type": note_type,
            "time_filter": time_filter,
            "search_id": search_id,
            "search_session_id": search_session_id,
            "source": source,
            "ai_mode": ai_mode,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/search_notes", params=params)

    async def search_users(
        self,
        *,
        keyword: str,
        page: int | None = None,
        search_id: str | None = None,
        source: str | None = None,
    ) -> Any:
        """搜索用户/Search users

        ``GET /api/v1/xiaohongshu/app_v2/search_users``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "search_id": search_id,
            "source": source,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/search_users", params=params)

    async def search_images(
        self,
        *,
        keyword: str,
        page: int | None = None,
        search_id: str | None = None,
        search_session_id: str | None = None,
        word_request_id: str | None = None,
        source: str | None = None,
    ) -> Any:
        """搜索图片/Search images

        ``GET /api/v1/xiaohongshu/app_v2/search_images``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "search_id": search_id,
            "search_session_id": search_session_id,
            "word_request_id": word_request_id,
            "source": source,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/search_images", params=params)

    async def search_products(
        self,
        *,
        keyword: str,
        page: int | None = None,
        search_id: str | None = None,
        source: str | None = None,
    ) -> Any:
        """搜索商品/Search products

        ``GET /api/v1/xiaohongshu/app_v2/search_products``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "search_id": search_id,
            "source": source,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/search_products", params=params)

    async def search_groups(
        self,
        *,
        keyword: str,
        page_no: int | None = None,
        search_id: str | None = None,
        source: str | None = None,
        is_recommend: int | None = None,
    ) -> Any:
        """搜索群聊/Search groups

        ``GET /api/v1/xiaohongshu/app_v2/search_groups``
        """
        params = _drop_none({
            "keyword": keyword,
            "page_no": page_no,
            "search_id": search_id,
            "source": source,
            "is_recommend": is_recommend,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/search_groups", params=params)

    async def get_product_detail(
        self,
        *,
        sku_id: str,
        source: str | None = None,
        pre_page: str | None = None,
    ) -> Any:
        """获取商品详情/Get product detail

        ``GET /api/v1/xiaohongshu/app_v2/get_product_detail``
        """
        params = _drop_none({
            "sku_id": sku_id,
            "source": source,
            "pre_page": pre_page,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_product_detail", params=params)

    async def get_product_review_overview(
        self,
        *,
        sku_id: str,
        tab: int | None = None,
    ) -> Any:
        """获取商品评论总览/Get product review overview

        ``GET /api/v1/xiaohongshu/app_v2/get_product_review_overview``
        """
        params = _drop_none({
            "sku_id": sku_id,
            "tab": tab,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_product_review_overview", params=params)

    async def get_product_reviews(
        self,
        *,
        sku_id: str,
        page: int | None = None,
        sort_strategy_type: int | None = None,
        share_pics_only: int | None = None,
        from_page: str | None = None,
    ) -> Any:
        """获取商品评论列表/Get product reviews

        ``GET /api/v1/xiaohongshu/app_v2/get_product_reviews``
        """
        params = _drop_none({
            "sku_id": sku_id,
            "page": page,
            "sort_strategy_type": sort_strategy_type,
            "share_pics_only": share_pics_only,
            "from_page": from_page,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_product_reviews", params=params)

    async def get_product_recommendations(
        self,
        *,
        sku_id: str,
        cursor_score: str | None = None,
        region: str | None = None,
    ) -> Any:
        """获取商品推荐列表/Get product recommendations

        ``GET /api/v1/xiaohongshu/app_v2/get_product_recommendations``
        """
        params = _drop_none({
            "sku_id": sku_id,
            "cursor_score": cursor_score,
            "region": region,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_product_recommendations", params=params)

    async def get_topic_info(
        self,
        *,
        page_id: str,
        source: str | None = None,
        note_id: str | None = None,
    ) -> Any:
        """获取话题详情/Get topic info

        ``GET /api/v1/xiaohongshu/app_v2/get_topic_info``
        """
        params = _drop_none({
            "page_id": page_id,
            "source": source,
            "note_id": note_id,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_topic_info", params=params)

    async def get_topic_feed(
        self,
        *,
        page_id: str,
        sort: str | None = None,
        cursor_score: str | None = None,
        last_note_id: str | None = None,
        last_note_ct: str | None = None,
        session_id: str | None = None,
        first_load_time: str | None = None,
        source: str | None = None,
    ) -> Any:
        """获取话题笔记列表/Get topic feed

        ``GET /api/v1/xiaohongshu/app_v2/get_topic_feed``
        """
        params = _drop_none({
            "page_id": page_id,
            "sort": sort,
            "cursor_score": cursor_score,
            "last_note_id": last_note_id,
            "last_note_ct": last_note_ct,
            "session_id": session_id,
            "first_load_time": first_load_time,
            "source": source,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_topic_feed", params=params)

    async def get_creator_inspiration_feed(
        self,
        *,
        cursor: str | None = None,
        tab: int | None = None,
        source: str | None = None,
    ) -> Any:
        """获取创作者推荐灵感列表/Get creator inspiration feed

        ``GET /api/v1/xiaohongshu/app_v2/get_creator_inspiration_feed``
        """
        params = _drop_none({
            "cursor": cursor,
            "tab": tab,
            "source": source,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_creator_inspiration_feed", params=params)

    async def get_creator_hot_inspiration_feed(
        self,
        *,
        cursor: str | None = None,
    ) -> Any:
        """获取创作者热点灵感列表/Get creator hot inspiration feed

        ``GET /api/v1/xiaohongshu/app_v2/get_creator_hot_inspiration_feed``
        """
        params = _drop_none({
            "cursor": cursor,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/app_v2/get_creator_hot_inspiration_feed", params=params)
