# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""YouTube-Web-V2-API resource.

OpenAPI tag: ``YouTube-Web-V2-API``
SDK attribute: ``client.youtube_web_v2`` / ``async_client.youtube_web_v2``

Endpoints: 25
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncYoutubeWebV2", "YoutubeWebV2"]


class YoutubeWebV2(SyncResource):
    """Sync ``YouTube-Web-V2-API`` resource (25 endpoints)."""

    def get_video_info(
        self,
        *,
        video_id: str,
        language_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取视频详情 /Get video information

        ``GET /api/v1/youtube/web_v2/get_video_info``
        """
        params = _drop_none({
            "video_id": video_id,
            "language_code": language_code,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_video_info", params=params)

    def get_video_info_v2(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取视频详情 V2/Get video information V2

        ``GET /api/v1/youtube/web_v2/get_video_info_v2``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_video_info_v2", params=params)

    def get_video_comments(
        self,
        *,
        video_id: str,
        language_code: str | None = None,
        country_code: str | None = None,
        sort_by: Any | None = None,
        continuation_token: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取视频评论/Get video comments

        ``GET /api/v1/youtube/web_v2/get_video_comments``
        """
        params = _drop_none({
            "video_id": video_id,
            "language_code": language_code,
            "country_code": country_code,
            "sort_by": sort_by,
            "continuation_token": continuation_token,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_video_comments", params=params)

    def get_video_comment_replies(
        self,
        *,
        continuation_token: str,
        language_code: str | None = None,
        country_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取视频二级评论/Get video sub comments

        ``GET /api/v1/youtube/web_v2/get_video_comment_replies``
        """
        params = _drop_none({
            "continuation_token": continuation_token,
            "language_code": language_code,
            "country_code": country_code,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_video_comment_replies", params=params)

    def get_channel_description(
        self,
        *,
        channel_id: str | None = None,
        continuation_token: str | None = None,
        language_code: str | None = None,
        country_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取频道描述信息/Get channel description

        ``GET /api/v1/youtube/web_v2/get_channel_description``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "continuation_token": continuation_token,
            "language_code": language_code,
            "country_code": country_code,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_description", params=params)

    def get_general_search(
        self,
        *,
        search_query: str,
        language_code: str | None = None,
        country_code: str | None = None,
        time_zone: str | None = None,
        upload_time: Any | None = None,
        duration: Any | None = None,
        content_type: Any | None = None,
        feature: Any | None = None,
        sort_by: Any | None = None,
        continuation_token: Any | None = None,
    ) -> Any:
        """综合搜索（原始数据，推荐使用V2）/General search (raw data, recommend V2)

        ``GET /api/v1/youtube/web_v2/get_general_search``
        """
        params = _drop_none({
            "search_query": search_query,
            "language_code": language_code,
            "country_code": country_code,
            "time_zone": time_zone,
            "upload_time": upload_time,
            "duration": duration,
            "content_type": content_type,
            "feature": feature,
            "sort_by": sort_by,
            "continuation_token": continuation_token,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_general_search", params=params)

    def get_general_search_v2(
        self,
        *,
        keyword: Any | None = None,
        continuation_token: Any | None = None,
        upload_date: Any | None = None,
        type: Any | None = None,
        duration: Any | None = None,
        features: Any | None = None,
        sort_by: Any | None = None,
    ) -> Any:
        """综合搜索V2/General search V2

        ``GET /api/v1/youtube/web_v2/get_general_search_v2``
        """
        params = _drop_none({
            "keyword": keyword,
            "continuation_token": continuation_token,
            "upload_date": upload_date,
            "type": type,
            "duration": duration,
            "features": features,
            "sort_by": sort_by,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_general_search_v2", params=params)

    def get_shorts_search(
        self,
        *,
        search_query: str,
        language_code: str | None = None,
        country_code: str | None = None,
        time_zone: str | None = None,
        upload_time: Any | None = None,
        sort_by: Any | None = None,
        continuation_token: Any | None = None,
        filter_mixed_content: bool | None = None,
    ) -> Any:
        """Shorts搜索（原始数据，推荐使用V2）/Shorts search (raw data, recommend V2)

        ``GET /api/v1/youtube/web_v2/get_shorts_search``
        """
        params = _drop_none({
            "search_query": search_query,
            "language_code": language_code,
            "country_code": country_code,
            "time_zone": time_zone,
            "upload_time": upload_time,
            "sort_by": sort_by,
            "continuation_token": continuation_token,
            "filter_mixed_content": filter_mixed_content,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_shorts_search", params=params)

    def get_shorts_search_v2(
        self,
        *,
        keyword: Any | None = None,
        continuation_token: Any | None = None,
        upload_date: Any | None = None,
        sort_by: Any | None = None,
    ) -> Any:
        """Shorts搜索V2/Shorts search V2

        ``GET /api/v1/youtube/web_v2/get_shorts_search_v2``
        """
        params = _drop_none({
            "keyword": keyword,
            "continuation_token": continuation_token,
            "upload_date": upload_date,
            "sort_by": sort_by,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_shorts_search_v2", params=params)

    def get_channel_id(
        self,
        *,
        channel_url: str,
    ) -> Any:
        """从频道URL获取频道ID /Get channel ID from URL

        ``GET /api/v1/youtube/web_v2/get_channel_id``
        """
        params = _drop_none({
            "channel_url": channel_url,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_id", params=params)

    def get_channel_url(
        self,
        *,
        channel_id: str,
    ) -> Any:
        """从频道ID获取频道URL/Get channel URL from channel ID

        ``GET /api/v1/youtube/web_v2/get_channel_url``
        """
        params = _drop_none({
            "channel_id": channel_id,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_url", params=params)

    def get_channel_videos(
        self,
        *,
        channel_id: str,
        language_code: str | None = None,
        country_code: str | None = None,
        continuation_token: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取频道视频 /Get channel videos

        ``GET /api/v1/youtube/web_v2/get_channel_videos``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "language_code": language_code,
            "country_code": country_code,
            "continuation_token": continuation_token,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_videos", params=params)

    def get_video_streams(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
    ) -> Any:
        """获取视频流信息/Get video streams info

        ``GET /api/v1/youtube/web_v2/get_video_streams``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_video_streams", params=params)

    def get_video_streams_v2(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
    ) -> Any:
        """获取视频流信息 V2/Get video streams info V2

        ``GET /api/v1/youtube/web_v2/get_video_streams_v2``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_video_streams_v2", params=params)

    def get_signed_stream_url(
        self,
        *,
        itag: int,
        video_id: str | None = None,
        video_url: str | None = None,
    ) -> Any:
        """获取已签名的视频流URL/Get signed video stream URL

        ``GET /api/v1/youtube/web_v2/get_signed_stream_url``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
            "itag": itag,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_signed_stream_url", params=params)

    def get_video_captions(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
        language_code: str | None = None,
        format: str | None = None,
    ) -> Any:
        """获取视频字幕/Get video captions

        ``GET /api/v1/youtube/web_v2/get_video_captions``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
            "language_code": language_code,
            "format": format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_video_captions", params=params)

    def get_video_captions_v2(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
        language_code: str | None = None,
        format: str | None = None,
    ) -> Any:
        """获取视频字幕 V2/Get video captions V2

        ``GET /api/v1/youtube/web_v2/get_video_captions_v2``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
            "language_code": language_code,
            "format": format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_video_captions_v2", params=params)

    def get_related_videos(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取视频相似内容/Get related videos

        ``GET /api/v1/youtube/web_v2/get_related_videos``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_related_videos", params=params)

    def get_channel_shorts(
        self,
        *,
        channel_id: str | None = None,
        channel_url: str | None = None,
        continuation_token: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取频道短视频列表/Get channel shorts

        ``GET /api/v1/youtube/web_v2/get_channel_shorts``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "channel_url": channel_url,
            "continuation_token": continuation_token,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_shorts", params=params)

    def get_search_suggestions(
        self,
        *,
        keyword: str,
        language: str | None = None,
        region: str | None = None,
    ) -> Any:
        """获取搜索推荐词/Get search suggestions

        ``GET /api/v1/youtube/web_v2/get_search_suggestions``
        """
        params = _drop_none({
            "keyword": keyword,
            "language": language,
            "region": region,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_search_suggestions", params=params)

    def search_channels(
        self,
        *,
        keyword: Any | None = None,
        continuation_token: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """搜索频道/Search channels

        ``GET /api/v1/youtube/web_v2/search_channels``
        """
        params = _drop_none({
            "keyword": keyword,
            "continuation_token": continuation_token,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/search_channels", params=params)

    def get_channel_community_posts(
        self,
        *,
        channel_id: str,
        language_code: str | None = None,
        country_code: str | None = None,
        continuation_token: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取频道帖子列表/Get channel community posts

        ``GET /api/v1/youtube/web_v2/get_channel_community_posts``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "language_code": language_code,
            "country_code": country_code,
            "continuation_token": continuation_token,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_community_posts", params=params)

    def get_post_detail(
        self,
        *,
        post_id: str,
        language_code: str | None = None,
        country_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取帖子详情/Get post detail

        ``GET /api/v1/youtube/web_v2/get_post_detail``
        """
        params = _drop_none({
            "post_id": post_id,
            "language_code": language_code,
            "country_code": country_code,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_post_detail", params=params)

    def get_post_comments(
        self,
        *,
        post_id: str | None = None,
        continuation_token: str | None = None,
        language_code: str | None = None,
        country_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取帖子评论/Get post comments

        ``GET /api/v1/youtube/web_v2/get_post_comments``
        """
        params = _drop_none({
            "post_id": post_id,
            "continuation_token": continuation_token,
            "language_code": language_code,
            "country_code": country_code,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_post_comments", params=params)

    def get_post_comment_replies(
        self,
        *,
        continuation_token: str,
        language_code: str | None = None,
        country_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取帖子评论回复/Get post comment replies

        ``GET /api/v1/youtube/web_v2/get_post_comment_replies``
        """
        params = _drop_none({
            "continuation_token": continuation_token,
            "language_code": language_code,
            "country_code": country_code,
            "need_format": need_format,
        })
        return self._client._request("GET", "/api/v1/youtube/web_v2/get_post_comment_replies", params=params)


class AsyncYoutubeWebV2(AsyncResource):
    """Async ``YouTube-Web-V2-API`` resource (25 endpoints)."""

    async def get_video_info(
        self,
        *,
        video_id: str,
        language_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取视频详情 /Get video information

        ``GET /api/v1/youtube/web_v2/get_video_info``
        """
        params = _drop_none({
            "video_id": video_id,
            "language_code": language_code,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_video_info", params=params)

    async def get_video_info_v2(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取视频详情 V2/Get video information V2

        ``GET /api/v1/youtube/web_v2/get_video_info_v2``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_video_info_v2", params=params)

    async def get_video_comments(
        self,
        *,
        video_id: str,
        language_code: str | None = None,
        country_code: str | None = None,
        sort_by: Any | None = None,
        continuation_token: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取视频评论/Get video comments

        ``GET /api/v1/youtube/web_v2/get_video_comments``
        """
        params = _drop_none({
            "video_id": video_id,
            "language_code": language_code,
            "country_code": country_code,
            "sort_by": sort_by,
            "continuation_token": continuation_token,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_video_comments", params=params)

    async def get_video_comment_replies(
        self,
        *,
        continuation_token: str,
        language_code: str | None = None,
        country_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取视频二级评论/Get video sub comments

        ``GET /api/v1/youtube/web_v2/get_video_comment_replies``
        """
        params = _drop_none({
            "continuation_token": continuation_token,
            "language_code": language_code,
            "country_code": country_code,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_video_comment_replies", params=params)

    async def get_channel_description(
        self,
        *,
        channel_id: str | None = None,
        continuation_token: str | None = None,
        language_code: str | None = None,
        country_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取频道描述信息/Get channel description

        ``GET /api/v1/youtube/web_v2/get_channel_description``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "continuation_token": continuation_token,
            "language_code": language_code,
            "country_code": country_code,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_description", params=params)

    async def get_general_search(
        self,
        *,
        search_query: str,
        language_code: str | None = None,
        country_code: str | None = None,
        time_zone: str | None = None,
        upload_time: Any | None = None,
        duration: Any | None = None,
        content_type: Any | None = None,
        feature: Any | None = None,
        sort_by: Any | None = None,
        continuation_token: Any | None = None,
    ) -> Any:
        """综合搜索（原始数据，推荐使用V2）/General search (raw data, recommend V2)

        ``GET /api/v1/youtube/web_v2/get_general_search``
        """
        params = _drop_none({
            "search_query": search_query,
            "language_code": language_code,
            "country_code": country_code,
            "time_zone": time_zone,
            "upload_time": upload_time,
            "duration": duration,
            "content_type": content_type,
            "feature": feature,
            "sort_by": sort_by,
            "continuation_token": continuation_token,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_general_search", params=params)

    async def get_general_search_v2(
        self,
        *,
        keyword: Any | None = None,
        continuation_token: Any | None = None,
        upload_date: Any | None = None,
        type: Any | None = None,
        duration: Any | None = None,
        features: Any | None = None,
        sort_by: Any | None = None,
    ) -> Any:
        """综合搜索V2/General search V2

        ``GET /api/v1/youtube/web_v2/get_general_search_v2``
        """
        params = _drop_none({
            "keyword": keyword,
            "continuation_token": continuation_token,
            "upload_date": upload_date,
            "type": type,
            "duration": duration,
            "features": features,
            "sort_by": sort_by,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_general_search_v2", params=params)

    async def get_shorts_search(
        self,
        *,
        search_query: str,
        language_code: str | None = None,
        country_code: str | None = None,
        time_zone: str | None = None,
        upload_time: Any | None = None,
        sort_by: Any | None = None,
        continuation_token: Any | None = None,
        filter_mixed_content: bool | None = None,
    ) -> Any:
        """Shorts搜索（原始数据，推荐使用V2）/Shorts search (raw data, recommend V2)

        ``GET /api/v1/youtube/web_v2/get_shorts_search``
        """
        params = _drop_none({
            "search_query": search_query,
            "language_code": language_code,
            "country_code": country_code,
            "time_zone": time_zone,
            "upload_time": upload_time,
            "sort_by": sort_by,
            "continuation_token": continuation_token,
            "filter_mixed_content": filter_mixed_content,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_shorts_search", params=params)

    async def get_shorts_search_v2(
        self,
        *,
        keyword: Any | None = None,
        continuation_token: Any | None = None,
        upload_date: Any | None = None,
        sort_by: Any | None = None,
    ) -> Any:
        """Shorts搜索V2/Shorts search V2

        ``GET /api/v1/youtube/web_v2/get_shorts_search_v2``
        """
        params = _drop_none({
            "keyword": keyword,
            "continuation_token": continuation_token,
            "upload_date": upload_date,
            "sort_by": sort_by,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_shorts_search_v2", params=params)

    async def get_channel_id(
        self,
        *,
        channel_url: str,
    ) -> Any:
        """从频道URL获取频道ID /Get channel ID from URL

        ``GET /api/v1/youtube/web_v2/get_channel_id``
        """
        params = _drop_none({
            "channel_url": channel_url,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_id", params=params)

    async def get_channel_url(
        self,
        *,
        channel_id: str,
    ) -> Any:
        """从频道ID获取频道URL/Get channel URL from channel ID

        ``GET /api/v1/youtube/web_v2/get_channel_url``
        """
        params = _drop_none({
            "channel_id": channel_id,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_url", params=params)

    async def get_channel_videos(
        self,
        *,
        channel_id: str,
        language_code: str | None = None,
        country_code: str | None = None,
        continuation_token: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取频道视频 /Get channel videos

        ``GET /api/v1/youtube/web_v2/get_channel_videos``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "language_code": language_code,
            "country_code": country_code,
            "continuation_token": continuation_token,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_videos", params=params)

    async def get_video_streams(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
    ) -> Any:
        """获取视频流信息/Get video streams info

        ``GET /api/v1/youtube/web_v2/get_video_streams``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_video_streams", params=params)

    async def get_video_streams_v2(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
    ) -> Any:
        """获取视频流信息 V2/Get video streams info V2

        ``GET /api/v1/youtube/web_v2/get_video_streams_v2``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_video_streams_v2", params=params)

    async def get_signed_stream_url(
        self,
        *,
        itag: int,
        video_id: str | None = None,
        video_url: str | None = None,
    ) -> Any:
        """获取已签名的视频流URL/Get signed video stream URL

        ``GET /api/v1/youtube/web_v2/get_signed_stream_url``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
            "itag": itag,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_signed_stream_url", params=params)

    async def get_video_captions(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
        language_code: str | None = None,
        format: str | None = None,
    ) -> Any:
        """获取视频字幕/Get video captions

        ``GET /api/v1/youtube/web_v2/get_video_captions``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
            "language_code": language_code,
            "format": format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_video_captions", params=params)

    async def get_video_captions_v2(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
        language_code: str | None = None,
        format: str | None = None,
    ) -> Any:
        """获取视频字幕 V2/Get video captions V2

        ``GET /api/v1/youtube/web_v2/get_video_captions_v2``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
            "language_code": language_code,
            "format": format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_video_captions_v2", params=params)

    async def get_related_videos(
        self,
        *,
        video_id: str | None = None,
        video_url: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取视频相似内容/Get related videos

        ``GET /api/v1/youtube/web_v2/get_related_videos``
        """
        params = _drop_none({
            "video_id": video_id,
            "video_url": video_url,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_related_videos", params=params)

    async def get_channel_shorts(
        self,
        *,
        channel_id: str | None = None,
        channel_url: str | None = None,
        continuation_token: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取频道短视频列表/Get channel shorts

        ``GET /api/v1/youtube/web_v2/get_channel_shorts``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "channel_url": channel_url,
            "continuation_token": continuation_token,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_shorts", params=params)

    async def get_search_suggestions(
        self,
        *,
        keyword: str,
        language: str | None = None,
        region: str | None = None,
    ) -> Any:
        """获取搜索推荐词/Get search suggestions

        ``GET /api/v1/youtube/web_v2/get_search_suggestions``
        """
        params = _drop_none({
            "keyword": keyword,
            "language": language,
            "region": region,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_search_suggestions", params=params)

    async def search_channels(
        self,
        *,
        keyword: Any | None = None,
        continuation_token: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """搜索频道/Search channels

        ``GET /api/v1/youtube/web_v2/search_channels``
        """
        params = _drop_none({
            "keyword": keyword,
            "continuation_token": continuation_token,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/search_channels", params=params)

    async def get_channel_community_posts(
        self,
        *,
        channel_id: str,
        language_code: str | None = None,
        country_code: str | None = None,
        continuation_token: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取频道帖子列表/Get channel community posts

        ``GET /api/v1/youtube/web_v2/get_channel_community_posts``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "language_code": language_code,
            "country_code": country_code,
            "continuation_token": continuation_token,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_channel_community_posts", params=params)

    async def get_post_detail(
        self,
        *,
        post_id: str,
        language_code: str | None = None,
        country_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取帖子详情/Get post detail

        ``GET /api/v1/youtube/web_v2/get_post_detail``
        """
        params = _drop_none({
            "post_id": post_id,
            "language_code": language_code,
            "country_code": country_code,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_post_detail", params=params)

    async def get_post_comments(
        self,
        *,
        post_id: str | None = None,
        continuation_token: str | None = None,
        language_code: str | None = None,
        country_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取帖子评论/Get post comments

        ``GET /api/v1/youtube/web_v2/get_post_comments``
        """
        params = _drop_none({
            "post_id": post_id,
            "continuation_token": continuation_token,
            "language_code": language_code,
            "country_code": country_code,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_post_comments", params=params)

    async def get_post_comment_replies(
        self,
        *,
        continuation_token: str,
        language_code: str | None = None,
        country_code: str | None = None,
        need_format: bool | None = None,
    ) -> Any:
        """获取帖子评论回复/Get post comment replies

        ``GET /api/v1/youtube/web_v2/get_post_comment_replies``
        """
        params = _drop_none({
            "continuation_token": continuation_token,
            "language_code": language_code,
            "country_code": country_code,
            "need_format": need_format,
        })
        return await self._client._request("GET", "/api/v1/youtube/web_v2/get_post_comment_replies", params=params)
