"""Example: Douyin-App-V3-API

SDK attribute: ``client.douyin_app_v3``
Endpoints: 46

Usage::

    python examples/douyin_app_v3.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/douyin/app/v3/fetch_one_video
        # 获取单个作品数据/Get single video data
        result = await client.douyin_app_v3.fetch_one_video(aweme_id='7448118827402972455')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_one_video_v2
        # 获取单个作品数据 V2/Get single video data V2
        result = await client.douyin_app_v3.fetch_one_video_v2(aweme_id='7448118827402972455')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_one_video_v3
        # 获取单个作品数据 V3 (无版权限制)/Get single video data V3 (No copyright restrictions)
        result = await client.douyin_app_v3.fetch_one_video_v3(aweme_id='7592116912205630761')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_share_info_by_share_code
        # 根据分享口令获取分享信息/Get share info by share code
        result = await client.douyin_app_v3.fetch_share_info_by_share_code(share_code='8:/ h@O.kP 05/21 【生意场上，装逼就是节省沟通成本】长按复制打开抖音，即可阅读文章 ︽︽2QnCB9aIZZ29︽︽')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/app/v3/fetch_multi_video
        # 批量获取视频信息 V1/Batch Get Video Information V1
        result = await client.douyin_app_v3.fetch_multi_video(body=[])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/app/v3/fetch_multi_video_v2
        # 批量获取视频信息 V2/Batch Get Video Information V2
        result = await client.douyin_app_v3.fetch_multi_video_v2(body=[])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_one_video_by_share_url
        # 根据分享链接获取单个作品数据/Get single video data by sharing link
        result = await client.douyin_app_v3.fetch_one_video_by_share_url(share_url='https://v.douyin.com/e3x2fjE/')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_video_high_quality_play_url
        # 获取视频的最高画质播放链接/Get the highest quality play URL of the video
        result = await client.douyin_app_v3.fetch_video_high_quality_play_url(aweme_id='7512756548356492544', share_url='https://www.douyin.com/video/7512756548356492544', region='CN')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/app/v3/fetch_multi_video_high_quality_play_url
        # 批量获取视频的最高画质播放链接/Batch get the highest quality play URL of videos
        result = await client.douyin_app_v3.fetch_multi_video_high_quality_play_url(aweme_ids='7512756548356492544,7448118827402972455,7126745726494821640', region='CN')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_video_statistics
        # 根据视频ID获取作品的统计数据（点赞数、下载数、播放数、分享数）/Get the statistical data of the Post according to the video ID (lik
        result = await client.douyin_app_v3.fetch_video_statistics(aweme_ids='7448118827402972455,7126745726494821640')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_multi_video_statistics
        # 根据视频ID批量获取作品的统计数据（点赞数、下载数、播放数、分享数）/Get the statistical data of the Post according to the video ID (l
        result = await client.douyin_app_v3.fetch_multi_video_statistics(aweme_ids='7448118827402972455,7126745726494821640')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/add_video_play_count
        # 根据视频ID来增加作品的播放数/Increase the number of plays of the work according to the video ID
        result = await client.douyin_app_v3.add_video_play_count(aweme_type=0, item_id='7197598285882789120')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/handler_user_profile
        # 获取指定用户的信息/Get information of specified user
        result = await client.douyin_app_v3.handler_user_profile(sec_user_id='MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_user_fans_list
        # 获取用户粉丝列表/Get user fans list
        result = await client.douyin_app_v3.fetch_user_fans_list(sec_user_id='MS4wLjABAAAA9y04iBlVdeMQqTJbqsQZKb-tqWqWW29jPVJqideHT70', max_time='0', count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_user_following_list
        # 获取用户关注列表 (弃用，使用 /api/v1/douyin/web/fetch_user_following_list 替代)/Get user following list (Deprecated
        result = await client.douyin_app_v3.fetch_user_following_list(sec_user_id='MS4wLjABAAAA9y04iBlVdeMQqTJbqsQZKb-tqWqWW29jPVJqideHT70', max_time='0', count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_user_post_videos
        # 获取用户主页作品数据/Get user homepage video data
        result = await client.douyin_app_v3.fetch_user_post_videos(sec_user_id='MS4wLjABAAAANXSltcLCzDGmdNFI2Q_QixVTr67NiYzjKOIP5s03CAE', max_cursor=0, count=20, sort_type=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_user_like_videos
        # 获取用户喜欢作品数据/Get user like video data
        result = await client.douyin_app_v3.fetch_user_like_videos(sec_user_id='MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y', max_cursor=0, counts=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_video_comments
        # 获取单个视频评论数据/Get single video comments data
        result = await client.douyin_app_v3.fetch_video_comments(aweme_id='7448118827402972455', cursor=0, count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_video_comment_replies
        # 获取指定视频的评论回复数据/Get comment replies data of specified video
        result = await client.douyin_app_v3.fetch_video_comment_replies(item_id='7354666303006723354', comment_id='7354669356632638218', cursor=0, count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_video_mix_detail
        # 获取抖音视频合集详情数据/Get Douyin video mix detail data
        result = await client.douyin_app_v3.fetch_video_mix_detail(mix_id='7302011174286002217')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_video_mix_post_list
        # 获取抖音视频合集作品列表数据/Get Douyin video mix post list data
        result = await client.douyin_app_v3.fetch_video_mix_post_list(mix_id='7302011174286002217', cursor=0, count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_user_series_list
        # 获取用户短剧合集列表/Get user series list
        result = await client.douyin_app_v3.fetch_user_series_list(user_id='3010877781453635', sec_user_id='MS4wLjABAAAAfAU5kMk-W4569G1z2iRsy8t6-kOxO17Eaz6yte4NQokeUeOpeqTGEc480e34O8lK', cursor=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_series_video_list
        # 获取短剧视频列表/Get series video list
        result = await client.douyin_app_v3.fetch_series_video_list(series_id='7592054624643713067', cursor=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_series_detail
        # 获取短剧详情信息/Get series detail
        result = await client.douyin_app_v3.fetch_series_detail(series_id='7592054624643713067')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_general_search_result
        # 获取指定关键词的综合搜索结果（弃用，替代接口见下方文档说明）/Get comprehensive search results of specified keywords (deprecated, s
        result = await client.douyin_app_v3.fetch_general_search_result(keyword='中华娘', offset=0, count=20, sort_type='0', publish_time='0', filter_duration='0', content_type='0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_video_search_result
        # 获取指定关键词的视频搜索结果（弃用，替代接口见下方文档说明）/Get video search results of specified keywords (deprecated, see the d
        result = await client.douyin_app_v3.fetch_video_search_result(keyword='中华娘', offset=0, count=20, sort_type='0', publish_time='0', filter_duration='0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_user_search_result
        # 获取指定关键词的用户搜索结果（弃用，替代接口见下方文档说明）/Get user search results of specified keywords (deprecated, see the do
        result = await client.douyin_app_v3.fetch_user_search_result(keyword='中华娘', offset=0, count=20, douyin_user_fans='', douyin_user_type='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_live_search_result
        # 获取指定关键词的直播搜索结果（弃用，替代接口见下方文档说明）/Get live search results of specified keywords (deprecated, see the do
        result = await client.douyin_app_v3.fetch_live_search_result(keyword='小米商城', cursor=0, count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_music_search_result
        # 获取指定关键词的音乐搜索结果（弃用，替代接口见下方文档说明）/Get music search results of specified keywords (deprecated, see the d
        result = await client.douyin_app_v3.fetch_music_search_result(keyword='中华娘', offset=0, count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_hashtag_search_result
        # 获取指定关键词的话题搜索结果（弃用，替代接口见下方文档说明）/Get hashtag search results of specified keywords (deprecated, see the
        result = await client.douyin_app_v3.fetch_hashtag_search_result(keyword='中华娘', offset=0, count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_music_detail
        # 获取指定音乐的详情数据/Get details of specified music
        result = await client.douyin_app_v3.fetch_music_detail(music_id='7136850194742315016')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_music_video_list
        # 获取指定音乐的视频列表数据/Get video list of specified music
        result = await client.douyin_app_v3.fetch_music_video_list(music_id='7136850194742315016', cursor=0, count=10)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_hashtag_detail
        # 获取指定话题的详情数据/Get details of specified hashtag
        result = await client.douyin_app_v3.fetch_hashtag_detail(ch_id=1575791821492238)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_hashtag_video_list
        # 获取指定话题的作品数据/Get video list of specified hashtag
        result = await client.douyin_app_v3.fetch_hashtag_video_list(ch_id='1575791821492238', cursor=0, sort_type=0, count=10)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_hot_search_list
        # 获取抖音热搜榜数据/Get Douyin hot search list data
        result = await client.douyin_app_v3.fetch_hot_search_list(board_type='0', board_sub_type='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_live_hot_search_list
        # 获取抖音直播热搜榜数据/Get Douyin live hot search list data
        result = await client.douyin_app_v3.fetch_live_hot_search_list()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_music_hot_search_list
        # 获取抖音音乐榜数据/Get Douyin music hot search list data
        result = await client.douyin_app_v3.fetch_music_hot_search_list(chart_type='hot', cursor='0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_brand_hot_search_list
        # 获取抖音品牌热榜分类数据/Get Douyin brand hot search list data
        result = await client.douyin_app_v3.fetch_brand_hot_search_list()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/fetch_brand_hot_search_list_detail
        # 获取抖音品牌热榜具体分类数据/Get Douyin brand hot search list detail data
        result = await client.douyin_app_v3.fetch_brand_hot_search_list_detail(category_id=10)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/generate_douyin_short_url
        # 生成抖音短链接/Generate Douyin short link
        result = await client.douyin_app_v3.generate_douyin_short_url(url='https://www.douyin.com/passport/web/logout/')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/generate_douyin_video_share_qrcode
        # 生成抖音视频分享二维码/Generate Douyin video share QR code
        result = await client.douyin_app_v3.generate_douyin_video_share_qrcode(object_id='7348044435755846962')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/register_device
        # 抖音APP注册设备/Douyin APP register device
        result = await client.douyin_app_v3.register_device(proxy='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/open_douyin_app_to_video_detail
        # 生成抖音分享链接，唤起抖音APP，跳转指定作品详情页/Generate Douyin share link, call Douyin APP, and jump to the specified vi
        result = await client.douyin_app_v3.open_douyin_app_to_video_detail(aweme_id='7348044435755846962')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/open_douyin_app_to_user_profile
        # 生成抖音分享链接，唤起抖音APP，跳转指定用户主页/Generate Douyin share link, call Douyin APP, and jump to the specified use
        result = await client.douyin_app_v3.open_douyin_app_to_user_profile(uid='96874812426', sec_uid='MS4wLjABAAAA9y04iBlVdeMQqTJbqsQZKb-tqWqWW29jPVJqideHT70')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/open_douyin_app_to_keyword_search
        # 生成抖音分享链接，唤起抖音APP，跳转指定关键词搜索结果/Generate Douyin share link, call Douyin APP, and jump to the specified
        result = await client.douyin_app_v3.open_douyin_app_to_keyword_search(keyword='雷军')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/app/v3/open_douyin_app_to_send_private_message
        # 生成抖音分享链接，唤起抖音APP，给指定用户发送私信/Generate Douyin share link, call Douyin APP, and send private messages to
        result = await client.douyin_app_v3.open_douyin_app_to_send_private_message(uid='96874812426', sec_uid='MS4wLjABAAAA9y04iBlVdeMQqTJbqsQZKb-tqWqWW29jPVJqideHT70')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
