"""Example: Douyin-Web-API

SDK attribute: ``client.douyin_web``
Endpoints: 68

Usage::

    python examples/douyin_web.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/douyin/web/fetch_one_video
        # 获取单个作品数据/Get single video data
        result = await client.douyin_web.fetch_one_video(aweme_id='7372484719365098803', need_anchor_info=False)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_one_video_v2
        # 获取单个作品数据 V2/Get single video data V2
        result = await client.douyin_web.fetch_one_video_v2(aweme_id='7372484719365098803')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_one_video_by_share_url
        # 根据分享链接获取单个作品数据/Get single video data by sharing link
        result = await client.douyin_web.fetch_one_video_by_share_url(share_url='https://v.douyin.com/e3x2fjE/')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_video_high_quality_play_url
        # 获取视频的最高画质播放链接/Get the highest quality play URL of the video
        result = await client.douyin_web.fetch_video_high_quality_play_url(aweme_id='7512756548356492544', share_url='https://www.douyin.com/video/7512756548356492544', region='CN')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/fetch_multi_video_high_quality_play_url
        # 批量获取视频的最高画质播放链接/Batch get the highest quality play URL of videos
        result = await client.douyin_web.fetch_multi_video_high_quality_play_url(aweme_ids='7512756548356492544,7448118827402972455,7126745726494821640', region='CN')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/fetch_multi_video
        # 批量获取视频信息/Batch Get Video Information
        result = await client.douyin_web.fetch_multi_video(body=[])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_one_video_danmaku
        # 获取单个作品视频弹幕数据/Get single video danmaku data
        result = await client.douyin_web.fetch_one_video_danmaku(item_id='7355433624046472498', duration=15134, end_time=15133, start_time=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_home_feed
        # 获取首页推荐数据/Get home feed data
        result = await client.douyin_web.fetch_home_feed(count=10, refresh_index=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_related_posts
        # 获取相关作品推荐数据/Get related posts recommendation data
        result = await client.douyin_web.fetch_related_posts(aweme_id='7393365489105358132', refresh_index=1, count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_post_videos
        # 获取用户主页作品数据/Get user homepage video data
        result = await client.douyin_web.fetch_user_post_videos(sec_user_id='MS4wLjABAAAANXSltcLCzDGmdNFI2Q_QixVTr67NiYzjKOIP5s03CAE', max_cursor='0', count=20, filter_type='0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/fetch_user_like_videos
        # 获取用户喜欢作品数据/Get user like video data
        result = await client.douyin_web.fetch_user_like_videos(sec_user_id='test', max_cursor=0, counts=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/fetch_user_collection_videos
        # 获取用户收藏作品数据/Get user collection video data
        result = await client.douyin_web.fetch_user_collection_videos(cookie='test', max_cursor=0, counts=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/fetch_user_collects
        # 获取用户收藏夹/Get user collection
        result = await client.douyin_web.fetch_user_collects(max_cursor=0, counts=20, cookie='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_collects_videos
        # 获取用户收藏夹数据/Get user collection data
        result = await client.douyin_web.fetch_user_collects_videos(collects_id='', max_cursor=0, counts=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_mix_videos
        # 获取用户合辑作品数据/Get user mix video data
        result = await client.douyin_web.fetch_user_mix_videos(mix_id='7348687990509553679', max_cursor=0, counts=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_live_videos
        # 获取用户直播流数据/Get user live video data
        result = await client.douyin_web.fetch_user_live_videos(webcast_id='376034101029')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_live_videos_by_sec_uid
        # 通过sec_uid获取指定用户的直播流数据/Get live video data of specified user by sec_uid
        result = await client.douyin_web.fetch_user_live_videos_by_sec_uid(sec_uid='MS4wLjABAAAAAIKOBr_x6p2fPVKOAhqG8LrC1lwwdWChifKEsl-TXFS-kGSGqpMBRexJdzoAfvUF')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_live_videos_by_room_id
        # 通过room_id获取指定用户的直播流数据 V1/Get live video data of specified user by room_id V1
        result = await client.douyin_web.fetch_user_live_videos_by_room_id(room_id='7318296342189919011')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_live_videos_by_room_id_v2
        # 通过room_id获取指定用户的直播流数据 V2/Gets the live stream data of the specified user by room_id V2
        result = await client.douyin_web.fetch_user_live_videos_by_room_id_v2(room_id='7462723839303093032')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_live_gift_ranking
        # 获取直播间送礼用户排行榜/Get live room gift user ranking
        result = await client.douyin_web.fetch_live_gift_ranking(room_id='7356585666190461731', rank_type=30)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_live_room_product_result
        # 抖音直播间商品信息/Douyin live room product information
        result = await client.douyin_web.fetch_live_room_product_result(room_id='7360830184578091776', author_id='1714858898241277', offset=0, limit=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_product_sku_list
        # 获取商品SKU列表/Get product SKU list
        result = await client.douyin_web.fetch_product_sku_list(product_id='3770337983790711029', author_id='3109048548866375')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_product_coupon
        # 获取商品优惠券信息/Get product coupon information
        result = await client.douyin_web.fetch_product_coupon(product_id='3770337983790711029', shop_id='129508461', price='1490', author_id='3109048548866375', sec_user_id='MS4wLjABAAAALoWx-cZWuQVWWvvlE-HiKgm9jel_nmwMcjAMIaEAwFq25sskN1Zgqy_T3x4D0Goy')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_product_review_score
        # 获取商品评价评分/Get product review score
        result = await client.douyin_web.fetch_product_review_score(product_id='3770337983790711029', shop_id='129508461')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_product_review_list
        # 获取商品评价列表/Get product review list
        result = await client.douyin_web.fetch_product_review_list(product_id='3770337983790711029', shop_id='129508461', cursor=0, count=20, sort_type=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_profile_by_uid
        # 使用UID获取用户信息/Get user information by UID
        result = await client.douyin_web.fetch_user_profile_by_uid(uid='68141954464')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_batch_user_profile_v1
        # 获取批量用户信息(最多10个)/Get batch user profile (up to 10)
        result = await client.douyin_web.fetch_batch_user_profile_v1(sec_user_ids='MS4wLjABAAAANXSltcLCzDGmdNFI2Q_QixVTr67NiYzjKOIP5s03CAE,MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_batch_user_profile_v2
        # 获取批量用户信息(最多50个)/Get batch user profile (up to 50)
        result = await client.douyin_web.fetch_batch_user_profile_v2(sec_user_ids='MS4wLjABAAAANXSltcLCzDGmdNFI2Q_QixVTr67NiYzjKOIP5s03CAE,MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_live_info_by_uid
        # 使用UID获取用户开播信息/Get user live information by UID
        result = await client.douyin_web.fetch_user_live_info_by_uid(uid='3081254195702747')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_profile_by_short_id
        # 使用Short ID获取用户信息/Get user information by Short ID
        result = await client.douyin_web.fetch_user_profile_by_short_id(short_id='114131058')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/handler_shorten_url
        # 生成短链接
        result = await client.douyin_web.handler_shorten_url(target_url='https://www.douyin.com/video/7575136499386720761')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/handler_user_profile
        # 使用sec_user_id获取指定用户的信息/Get information of specified user by sec_user_id
        result = await client.douyin_web.handler_user_profile(sec_user_id='MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/handler_user_profile_v2
        # 使用unique_id（抖音号）获取指定用户的信息/Get information of specified user by unique_id
        result = await client.douyin_web.handler_user_profile_v2(unique_id='TheChief')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/encrypt_uid_to_sec_user_id
        # 加密用户uid到sec_user_id/Encrypt user uid to sec_user_id
        result = await client.douyin_web.encrypt_uid_to_sec_user_id(uid='1673937488185292')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/handler_user_profile_v3
        # 根据抖音uid获取指定用户的信息/Get information of specified user by uid
        result = await client.douyin_web.handler_user_profile_v3(uid='1673937488185292')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/handler_user_profile_v4
        # 根据sec_user_id获取指定用户的信息（性别，年龄，直播等级、牌子）/Get information of specified user by sec_user_id (gender, age,
        result = await client.douyin_web.handler_user_profile_v4(sec_user_id='MS4wLjABAAAAW9FWcqS7RdQAWPd2AA5fL_ilmqsIFUCQ_Iym6Yh9_cUa6ZRqVLjVQSUjlHrfXY1Y')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_fans_list
        # 获取用户粉丝列表/Get user fans list
        result = await client.douyin_web.fetch_user_fans_list(sec_user_id='MS4wLjABAAAA9y04iBlVdeMQqTJbqsQZKb-tqWqWW29jPVJqideHT70', max_time='0', count=20, source_type=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_following_list
        # 获取用户关注列表/Get user following list
        result = await client.douyin_web.fetch_user_following_list(sec_user_id='MS4wLjABAAAA9y04iBlVdeMQqTJbqsQZKb-tqWqWW29jPVJqideHT70', max_time='0', count=20, source_type=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_video_comments
        # 获取单个视频评论数据/Get single video comments data
        result = await client.douyin_web.fetch_video_comments(aweme_id='7372484719365098803', cursor=0, count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_video_comment_replies
        # 获取指定视频的评论回复数据/Get comment replies data of specified video
        result = await client.douyin_web.fetch_video_comment_replies(item_id='7354666303006723354', comment_id='7354669356632638218', cursor=0, count=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_user_search_result_v3
        # 获取指定关键词的用户搜索结果 V3 (已弃用，替代接口请参考下方文档)/Get user search results of specified keywords V3 (deprecated, pl
        result = await client.douyin_web.fetch_user_search_result_v3(keyword='中华娘', cursor='0', douyin_user_type='', douyin_user_fans='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/fetch_challenge_posts
        # 话题作品/Challenge Posts
        result = await client.douyin_web.fetch_challenge_posts(challenge_id='1608846127610893', sort_type=0, cursor=0, count=20, cookie='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_hot_search_result
        # 获取抖音热榜数据/Get Douyin hot search results
        result = await client.douyin_web.fetch_hot_search_result()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_video_channel_result
        # 抖音视频频道数据/Douyin video channel data
        result = await client.douyin_web.fetch_video_channel_result(tag_id=300203, count=10, refresh_index=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_douyin_web_guest_cookie
        # 获取抖音Web的游客Cookie/Get the guest Cookie of Douyin Web
        result = await client.douyin_web.fetch_douyin_web_guest_cookie(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/generate_real_msToken
        # 生成真实msToken/Generate real msToken
        result = await client.douyin_web.generate_real_msToken()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/generate_ttwid
        # 生成ttwid/Generate ttwid
        result = await client.douyin_web.generate_ttwid(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/fetch_query_user
        # 查询抖音用户基本信息/Query Douyin user basic information
        result = await client.douyin_web.fetch_query_user(body=None)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/generate_verify_fp
        # 生成verify_fp/Generate verify_fp
        result = await client.douyin_web.generate_verify_fp()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/generate_s_v_web_id
        # 生成s_v_web_id/Generate s_v_web_id
        result = await client.douyin_web.generate_s_v_web_id()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/generate_wss_xb_signature
        # 生成弹幕xb签名/Generate barrage xb signature
        result = await client.douyin_web.generate_wss_xb_signature(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0', room_id='7382517534467115826', user_unique_id='7382524529011246630')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/generate_x_bogus
        # 使用接口网址生成X-Bogus参数/Generate X-Bogus parameter using API URL
        result = await client.douyin_web.generate_x_bogus(url='https://www.douyin.com/aweme/v1/web/aweme/detail/?aweme_id=7148736076176215311&device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=1920&screen_height=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Edge&browser_version=117.0.2045.47&browser_online=true&engine_name=Blink&engine_version=117.0.0.0&os_name=Windows&os_version=10&cpu_core_num=128&device_memory=10240&platform=PC&downlink=10&effective_type=4g&round_trip_time=100', user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/generate_a_bogus
        # 使用接口网址生成A-Bogus参数/Generate A-Bogus parameter using API URL
        result = await client.douyin_web.generate_a_bogus(url='https://www.douyin.com/aweme/v1/web/general/search/single/?device_platform=webapp&aid=6383&channel=channel_pc_web&search_channel=aweme_general&enable_history=1&keyword=%E4%B8%AD%E5%8D%8E%E5%A8%98&search_source=normal_search&query_correct_type=1&is_filter_search=0&from_group_id=7346905902554844468&offset=0&count=15&need_filter_settings=1&pc_client_type=1&version_code=190600&version_name=19.6.0&cookie_enabled=true&screen_width=1280&screen_height=800&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=124.0&browser_online=true&engine_name=Gecko&engine_version=124.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7348962975497324070&msToken=YCTVM6YGmjFdIpQAN9ykXLBXiSiuHdZkOkEQWTeqVOHBEPmOcM0lNwE0Kd9vgHPMPigSndZDHfAq9k-6lDmH3Jqz6mHHxmn-BzQjmLMIfLIPgirgnOixM9x4PwgcNQ%3D%3D', data='', user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36', index_0=0, index_1=1, index_2=14)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/get_sec_user_id
        # 提取单个用户id/Extract single user id
        result = await client.douyin_web.get_sec_user_id(url='https://www.douyin.com/user/MS4wLjABAAAANXSltcLCzDGmdNFI2Q_QixVTr67NiYzjKOIP5s03CAE')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/get_all_sec_user_id
        # 提取列表用户id/Extract list user id
        result = await client.douyin_web.get_all_sec_user_id(body=[])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/get_aweme_id
        # 提取单个作品id/Extract single video id
        result = await client.douyin_web.get_aweme_id(url='https://www.douyin.com/video/7298145681699622182')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/get_all_aweme_id
        # 提取列表作品id/Extract list video id
        result = await client.douyin_web.get_all_aweme_id(body=[])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/get_webcast_id
        # 提取直播间号/Extract webcast id
        result = await client.douyin_web.get_webcast_id(url='https://live.douyin.com/775841227732')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/web/get_all_webcast_id
        # 提取列表直播间号/Extract list webcast id
        result = await client.douyin_web.get_all_webcast_id(body=[])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/webcast_id_2_room_id
        # 直播间号转房间号/Webcast id to room id
        result = await client.douyin_web.webcast_id_2_room_id(webcast_id='775841227732')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/douyin_live_room
        # 提取直播间弹幕/Extract live room danmaku
        result = await client.douyin_web.douyin_live_room(live_room_url='https://live.douyin.com/834624950943', danmaku_type='WebcastRoomMessage')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_live_im_fetch
        # 抖音直播间弹幕参数获取/Douyin live room danmaku parameters
        result = await client.douyin_web.fetch_live_im_fetch(room_id='7382517534467115826', user_unique_id='7382524529011246630')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_series_aweme
        # 短剧作品/Series Video
        result = await client.douyin_web.fetch_series_aweme(offset=0, count=16, content_type=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_knowledge_aweme
        # 知识作品推荐/Knowledge Video
        result = await client.douyin_web.fetch_knowledge_aweme(count=16, refresh_index=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_game_aweme
        # 游戏作品推荐/Game Video
        result = await client.douyin_web.fetch_game_aweme(count=16, refresh_index=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_cartoon_aweme
        # 二次元作品推荐/Anime Video
        result = await client.douyin_web.fetch_cartoon_aweme(count=16, refresh_index=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_music_aweme
        # 音乐作品推荐/Music Video
        result = await client.douyin_web.fetch_music_aweme(count=16, refresh_index=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/web/fetch_food_aweme
        # 美食作品推荐/Food Video
        result = await client.douyin_web.fetch_food_aweme(count=16, refresh_index=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
