"""Example: Douyin-Index-API

SDK attribute: ``client.douyin_index``
Endpoints: 44

Usage::

    python examples/douyin_index.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/douyin/index/fetch_all_valid_date
        # 获取所有有效日期/Get all valid dates
        result = await client.douyin_index.fetch_all_valid_date()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_valid_date_for_relation
        # 获取关联分析有效日期/Get valid date for relation
        result = await client.douyin_index.fetch_valid_date_for_relation()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_all_area
        # 获取所有地区列表/Get all area list
        result = await client.douyin_index.fetch_all_area()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_current_hot_topic
        # 获取实时热点排行/Get current hot topics
        result = await client.douyin_index.fetch_current_hot_topic()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_hot_words
        # 获取热门关键词/Get hot words
        result = await client.douyin_index.fetch_hot_words(app_name='aweme')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_keyword_valid_date
        # 获取关键词有效日期/Get keyword valid date
        result = await client.douyin_index.fetch_keyword_valid_date(keyword_list='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_multi_keyword_hot_trend
        # 获取多关键词热度趋势/Get multi-keyword hot trend
        result = await client.douyin_index.fetch_multi_keyword_hot_trend(keyword_list='test', start_date='test', end_date='test', app_name='aweme', region='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_multi_keyword_interpretation
        # 获取多关键词解读/Get multi-keyword interpretation
        result = await client.douyin_index.fetch_multi_keyword_interpretation(keyword_list='test', start_date='test', end_date='test', app_name='aweme', region='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_relation_word
        # 获取关联词分析/Get relation word analysis
        result = await client.douyin_index.fetch_relation_word(keyword='test', start_date='test', end_date='test', app_name='aweme')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_portrait
        # 获取人群画像/Get crowd portrait
        result = await client.douyin_index.fetch_portrait(keyword='test', start_date='test', end_date='test', app_name='aweme')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_get_user_sub_word
        # 获取用户订阅关键词/Get user subscribed keywords
        result = await client.douyin_index.fetch_get_user_sub_word()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_encrypt_user_id
        # 抖音 uid 转加密 user_id/Encrypt Douyin uid to user_id
        result = await client.douyin_index.fetch_encrypt_user_id(uid='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_daren_sug_great_user_list
        # 达人搜索建议/Daren search suggest
        result = await client.douyin_index.fetch_daren_sug_great_user_list(keyword='test', total='20')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_daren_compare_users_stable
        # 达人趋势对比/Daren compare users
        result = await client.douyin_index.fetch_daren_compare_users_stable(user_list='test', days='7')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_daren_similar_users
        # 获取相似达人/Get similar daren
        result = await client.douyin_index.fetch_daren_similar_users(user_id='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_daren_great_user_top_video
        # 获取达人视频/Get daren top videos
        result = await client.douyin_index.fetch_daren_great_user_top_video(user_id='test', start_date='test', end_date='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_daren_great_item_mile_info
        # 获取达人核心指标/Get daren core metrics
        result = await client.douyin_index.fetch_daren_great_item_mile_info(user_id='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_daren_great_user_fans_info
        # 获取达人粉丝分析/Get daren fans analysis
        result = await client.douyin_index.fetch_daren_great_user_fans_info(user_id='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_item_filter_options
        # 获取视频搜索筛选选项/Get video search filter options
        result = await client.douyin_index.fetch_item_filter_options()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_item_sug
        # 视频搜索建议/Video search suggest
        result = await client.douyin_index.fetch_item_sug(query='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_item_query
        # 视频搜索结果/Video search results
        result = await client.douyin_index.fetch_item_query(query='test', category_id='0', date_type=0, label_type=0, duration_type=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_brand_suggest
        # 品牌搜索建议/Brand search suggest
        result = await client.douyin_index.fetch_brand_suggest(keyword='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_brand_valid_info
        # 获取品牌指数/Get brand index
        result = await client.douyin_index.fetch_brand_valid_info(keyword_list='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_brand_radar_chart
        # 获取品牌雷达图/Get brand radar chart
        result = await client.douyin_index.fetch_brand_radar_chart(brand_name='test', start_date='test', end_date='test', app_name='aweme')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_brand_lines
        # 获取品牌趋势线/Get brand trend lines
        result = await client.douyin_index.fetch_brand_lines(brand_name='test', start_date='test', end_date='test', app_name='aweme')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_brand_cycles
        # 获取品牌周期数据/Get brand cycles
        result = await client.douyin_index.fetch_brand_cycles(brand_name='test', start_date='test', end_date='test', app_name='aweme')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_brand_initiative_rank_weekly
        # 获取品牌主动排行周榜/Get brand initiative rank weekly
        result = await client.douyin_index.fetch_brand_initiative_rank_weekly(brand_name='test', start_date='test', end_date='test', app_name='aweme')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_topic_suggest
        # 话题搜索建议/Topic search suggest
        result = await client.douyin_index.fetch_topic_suggest(keyword='test', app_name='aweme')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_topic_query
        # 话题搜索结果/Topic search results
        result = await client.douyin_index.fetch_topic_query(keyword='test', start_date='test', end_date='test', app_name='aweme')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_content_valid_date
        # 创作指南有效日期/Get content valid date
        result = await client.douyin_index.fetch_content_valid_date()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_brand_hot_videos_time_scope
        # 热门视频时间范围/Brand hot videos time scope
        result = await client.douyin_index.fetch_brand_hot_videos_time_scope()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_content_creative_keywords
        # 创作热门关键词/Content creative keywords
        result = await client.douyin_index.fetch_content_creative_keywords(tag_id='test', period='7', end_date='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_content_creative_keyword_items
        # 关键词相关视频/Creative keyword related items
        result = await client.douyin_index.fetch_content_creative_keyword_items(tag_id='test', period='7', end_date='test', keyword='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_content_creative_topic
        # 创作热门话题/Content creative topic
        result = await client.douyin_index.fetch_content_creative_topic(tag_id='test', period='7', end_date='test', rank_type='index')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_content_publish_trend
        # 内容发布趋势/Content publish trend
        result = await client.douyin_index.fetch_content_publish_trend(tag_id='test', start_date='test', end_date='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_content_creative_duration
        # 创作时长分布/Content creative duration
        result = await client.douyin_index.fetch_content_creative_duration(tag_id='test', period='week', end_date='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_content_author_portrait
        # 创作者画像/Content author portrait
        result = await client.douyin_index.fetch_content_author_portrait(tag_id='test', period='month', end_date='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_content_consumer_portrait
        # 消费者画像/Content consumer portrait
        result = await client.douyin_index.fetch_content_consumer_portrait(tag_id='test', period='month', end_date='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_content_interact_trend
        # 互动趋势/Content interact trend
        result = await client.douyin_index.fetch_content_interact_trend(tag_id='test', start_date='test', end_date='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_content_consume_trend
        # 消费趋势/Content consume trend
        result = await client.douyin_index.fetch_content_consume_trend(tag_id='test', start_date='test', end_date='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_insight_recommend
        # 获取推荐报告/Get recommended insight reports
        result = await client.douyin_index.fetch_insight_recommend()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/index/fetch_report_search
        # 搜索趋势报告/Search trend reports
        result = await client.douyin_index.fetch_report_search(current_page='1', page_size='16', type='', business='', report_time='', search='', category='6')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_report_detail
        # 获取报告详情/Get report detail
        result = await client.douyin_index.fetch_report_detail(report_id='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/index/fetch_insight_get_rec
        # 获取报告相关推荐/Get related insight recommendations
        result = await client.douyin_index.fetch_insight_get_rec(report_id='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
