"""Example: Instagram-V3-API

SDK attribute: ``client.instagram_v3``
Endpoints: 32

Usage::

    python examples/instagram_v3.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/instagram/v3/search_users
        # 搜索用户/Search users
        result = await client.instagram_v3.search_users(query='justin')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/search_hashtags
        # 搜索话题标签/Search hashtags
        result = await client.instagram_v3.search_hashtags(query='fashion')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/search_places
        # 搜索地点/Search places
        result = await client.instagram_v3.search_places(query='tokyo')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/general_search
        # 综合搜索（支持分页）/General search (with pagination)
        result = await client.instagram_v3.general_search(query='justin', enable_metadata=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_id_by_username
        # 通过用户名获取用户ID/Get user ID by username
        result = await client.instagram_v3.get_user_id_by_username(username='liensue.talks')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_profile
        # 获取用户信息/Get user profile
        result = await client.instagram_v3.get_user_profile(user_id='58208242181', username='instagram')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_brief
        # 获取用户短详情/Get user brief info
        result = await client.instagram_v3.get_user_brief(user_id='791258468', username='99brasil')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_posts
        # 获取用户帖子列表/Get user posts
        result = await client.instagram_v3.get_user_posts(username='99brasil', first=12, count=12)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_tagged_posts
        # 获取用户被标记的帖子/Get user tagged posts
        result = await client.instagram_v3.get_user_tagged_posts(user_id='58208242181', username='instagram', first=12, count=12)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_reels
        # 获取用户Reels列表/Get user reels
        result = await client.instagram_v3.get_user_reels(user_id='58208242181', username='instagram', first=12, page_size=12)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_highlights
        # 获取用户精选Highlights列表/Get user highlights
        result = await client.instagram_v3.get_user_highlights(user_id='58208242181', username='instagram', first=10)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_highlight_stories
        # 获取Highlight精选详情/Get highlight stories
        result = await client.instagram_v3.get_highlight_stories(highlight_id='highlight:18064916456320419', first=3, last=2)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_about
        # 获取用户账户简介/Get user about info
        result = await client.instagram_v3.get_user_about(user_id='791258468', username='instagram')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_former_usernames
        # 获取用户曾用用户名/Get user former usernames
        result = await client.instagram_v3.get_user_former_usernames(user_id='17841403122371231', username='instagram')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_stories
        # 获取用户Stories（快拍）/Get user stories
        result = await client.instagram_v3.get_user_stories(user_id='58208242181', username='instagram')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_recommended_reels
        # 获取Reels推荐列表/Get recommended Reels feed
        result = await client.instagram_v3.get_recommended_reels(first=12)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_post_info
        # 获取帖子详情/Get post info (media_id or URL)
        result = await client.instagram_v3.get_post_info(media_id='3850699893338385742', url='https://www.instagram.com/p/DUajw4YkorV/')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_post_info_by_code
        # 获取帖子详情(code)/Get post info by shortcode
        result = await client.instagram_v3.get_post_info_by_code(code='DUajw4YkorV')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_post_comments
        # 获取帖子评论/Get post comments
        result = await client.instagram_v3.get_post_comments(code='DUajw4YkorV', sort_order='popular')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_comment_replies
        # 获取评论的子评论/回复/Get comment replies
        result = await client.instagram_v3.get_comment_replies(media_id='3829530490739515971', comment_id='18065937092249736')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_post_oembed
        # 获取帖子oEmbed内嵌信息/Get post oEmbed info
        result = await client.instagram_v3.get_post_oembed(url='https://www.instagram.com/reel/DUlObENDmJD', hidecaption=False, maxwidth=540)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/translate_comment
        # 翻译评论/帖子文本/Translate comment or caption
        result = await client.instagram_v3.translate_comment(comment_id='18191961100350646')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/bulk_translate_comments
        # 批量翻译评论/Bulk translate comments
        result = await client.instagram_v3.bulk_translate_comments(comment_ids='18099342953509681')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_explore
        # 获取探索页推荐帖子/Get explore feed
        result = await client.instagram_v3.get_explore()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_following
        # 获取用户关注列表/Get user following list
        result = await client.instagram_v3.get_user_following(user_id='58208242181', username='instagram', count=12)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_user_followers
        # 获取用户粉丝列表/Get user followers list
        result = await client.instagram_v3.get_user_followers(user_id='58208242181', username='instagram', count=12)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_location_info
        # 获取地点详情/Get location info
        result = await client.instagram_v3.get_location_info(location_id='1016248898', show_nearby=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_location_posts
        # 获取地点相关帖子/Get location posts
        result = await client.instagram_v3.get_location_posts(location_id='1016248898', tab='ranked', first=12, page_size_override=12)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/get_location_nearby
        # 获取地点附近内容/Get nearby location content
        result = await client.instagram_v3.get_location_nearby(location_id='213385402')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/shortcode_to_media_id
        # 短码转媒体ID/Convert shortcode to media ID
        result = await client.instagram_v3.shortcode_to_media_id(shortcode='CrgVBtHrFHm')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/media_id_to_shortcode
        # 媒体ID转短码/Convert media ID to shortcode
        result = await client.instagram_v3.media_id_to_shortcode(media_id='3850699893338385742')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v3/extract_shortcode
        # 从URL提取短码/Extract shortcode from URL
        result = await client.instagram_v3.extract_shortcode(url='https://www.instagram.com/p/CrgVBtHrFHm/')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
