"""Example: LinkedIn-Web-API

SDK attribute: ``client.linkedin_web``
Endpoints: 42

Usage::

    python examples/linkedin_web.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/linkedin/web/get_user_profile
        # 获取用户资料/Get user profile
        result = await client.linkedin_web.get_user_profile(username='jack')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_posts
        # 获取用户帖子/Get user posts
        result = await client.linkedin_web.get_user_posts(urn='ACoAABCtiL8B26nfi3Nbpo_AM8ngg4LeClT1Wh8', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_comments
        # 获取用户评论/Get user comments
        result = await client.linkedin_web.get_user_comments(urn='ACoAABCtiL8B26nfi3Nbpo_AM8ngg4LeClT1Wh8', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_contact
        # 获取用户联系信息/Get user contact information
        result = await client.linkedin_web.get_user_contact(username='shubhangi-shrivastava-39161bb7')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_recommendations
        # 获取用户推荐信/Get user recommendations
        result = await client.linkedin_web.get_user_recommendations(urn='ACoAAC3iNKcB3qbWJrP7K5Z3i89AF5c1snr8bhc', page=1, type='received')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_videos
        # 获取用户视频/Get user videos
        result = await client.linkedin_web.get_user_videos(urn='ACoAABCtiL8B26nfi3Nbpo_AM8ngg4LeClT1Wh8', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_images
        # 获取用户图片/Get user images
        result = await client.linkedin_web.get_user_images(urn='ACoAABCtiL8B26nfi3Nbpo_AM8ngg4LeClT1Wh8', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_company_profile
        # 获取公司资料/Get company profile
        result = await client.linkedin_web.get_company_profile(company='rapidapi')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_company_people
        # 获取公司员工/Get company people
        result = await client.linkedin_web.get_company_people(company_id='1066442', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_company_posts
        # 获取公司帖子/Get company posts
        result = await client.linkedin_web.get_company_posts(company_id='10649600', page=1, sort_by='top')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_company_jobs
        # 获取公司职位/Get company jobs
        result = await client.linkedin_web.get_company_jobs(company_id='783611', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_company_job_count
        # 获取公司职位数量/Get company job count
        result = await client.linkedin_web.get_company_job_count(company_id='783611')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_about
        # 获取用户简介/Get user about
        result = await client.linkedin_web.get_user_about(urn='ACoAAA8BYqEBCGLg_vT_ca6mMEqkpp9nVffJ3hc')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_follower_and_connection
        # 获取用户粉丝和连接数/Get user follower and connection
        result = await client.linkedin_web.get_user_follower_and_connection(username='zoranmilosevic')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_experience
        # 获取用户工作经历/Get user experience
        result = await client.linkedin_web.get_user_experience(urn='ACoAAAjpjWIBMh1iBR4OgSPK5GXetlQ6dYUT-qo', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_skills
        # 获取用户技能/Get user skills
        result = await client.linkedin_web.get_user_skills(urn='ACoAACkphDcBDruPBdXiAnqyc834jkTkd_4kRnU', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_educations
        # 获取用户教育背景/Get user educations
        result = await client.linkedin_web.get_user_educations(urn='ACoAAARpiwIBp_SzoeHPlUfOvmtibe08Ea1iCh4', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_publications
        # 获取用户出版物/Get user publications
        result = await client.linkedin_web.get_user_publications(urn='ACoAAB8rG_UB7cstjC__gk5318uYsZOIVkyysi4', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_certifications
        # 获取用户认证/Get user certifications
        result = await client.linkedin_web.get_user_certifications(urn='ACoAAARpiwIBp_SzoeHPlUfOvmtibe08Ea1iCh4', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_honors
        # 获取用户荣誉奖项/Get user honors
        result = await client.linkedin_web.get_user_honors(urn='ACoAAC41xVEBx77koDz3k1eJ5E9t8UZ7g0IVGj4', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_interests_groups
        # 获取用户感兴趣的群组/Get user interests groups
        result = await client.linkedin_web.get_user_interests_groups(urn='ACoAAAjpjWIBMh1iBR4OgSPK5GXetlQ6dYUT-qo', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_interests_companies
        # 获取用户感兴趣的公司/Get user interests companies
        result = await client.linkedin_web.get_user_interests_companies(urn='ACoAAEDH77YBEVIYXAaEwTicp5CcB_hR7DfFL9o', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_job_detail
        # 获取职位详情/Get job detail
        result = await client.linkedin_web.get_job_detail(job_id='4172815660')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/search_jobs
        # 搜索职位/Search jobs
        result = await client.linkedin_web.search_jobs(keyword='backend', page=1, geocode='103644278', company='1441')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/search_people
        # 搜索用户/Search people
        result = await client.linkedin_web.search_people(name='john', first_name='john', last_name='oliver', title='manager', page=1, geocode_location='103644278')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_reactions
        # 获取用户点赞反应/Get user reactions
        result = await client.linkedin_web.get_user_reactions(urn='ACoAABCtiL8B26nfi3Nbpo_AM8ngg4LeClT1Wh8', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_user_volunteers
        # 获取用户志愿者经历/Get user volunteers
        result = await client.linkedin_web.get_user_volunteers(urn='ACoAABCtiL8B26nfi3Nbpo_AM8ngg4LeClT1Wh8', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_company_affiliated_pages
        # 获取公司关联页面/Get company affiliated pages
        result = await client.linkedin_web.get_company_affiliated_pages(company_id='1441')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_company_associated_member_insights
        # 获取公司关联成员洞察/Get company associated member insights
        result = await client.linkedin_web.get_company_associated_member_insights(company_id='1441')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_post_detail
        # 获取帖子详情/Get post detail
        result = await client.linkedin_web.get_post_detail(post_id='7244804629786419202')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_post_comments
        # 获取帖子评论/Get post comments
        result = await client.linkedin_web.get_post_comments(post_id='7244804629786419202', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_post_reactions
        # 获取帖子点赞反应/Get post reactions
        result = await client.linkedin_web.get_post_reactions(post_id='7244804629786419202', page=1, type='all')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_post_reposts
        # 获取帖子转发/Get post reposts
        result = await client.linkedin_web.get_post_reposts(post_id='7244804629786419202', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_comments_replies
        # 获取评论回复/Get comment replies
        result = await client.linkedin_web.get_comments_replies(post_id='7244804629786419202', comment_id='test', previous_replies_token='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/search_posts
        # 搜索帖子/Search posts
        result = await client.linkedin_web.search_posts(keyword='data', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/search_location
        # 搜索地理位置/Search location
        result = await client.linkedin_web.search_location(keyword='san francisco')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/search_schools
        # 搜索学校/Search schools
        result = await client.linkedin_web.search_schools(keyword='stanford', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/search_suggestion_industry
        # 搜索行业建议/Search industry suggestions
        result = await client.linkedin_web.search_suggestion_industry(keyword='software')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_group_info
        # 获取群组信息/Get group info
        result = await client.linkedin_web.get_group_info(group_id='test')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_group_posts
        # 获取群组帖子/Get group posts
        result = await client.linkedin_web.get_group_posts(group_id='test', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/search_ads
        # 搜索广告/Search ads (Ad Library)
        result = await client.linkedin_web.search_ads(keyword='data', country='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/linkedin/web/get_ad_detail
        # 获取广告详情/Get ad detail
        result = await client.linkedin_web.get_ad_detail(ad_id='637671316')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
