"""Example: TikTok-Web-API

SDK attribute: ``client.tiktok_web``
Endpoints: 60

Usage::

    python examples/tiktok_web.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/tiktok/web/fetch_post_detail
        # 获取单个作品数据/Get single video data
        result = await client.tiktok_web.fetch_post_detail(itemId='7339393672959757570')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_post_detail_v2
        # 获取单个作品数据 V2/Get single video data V2
        result = await client.tiktok_web.fetch_post_detail_v2(itemId='7339393672959757570')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_explore_post
        # 获取探索作品数据/Get explore video data
        result = await client.tiktok_web.fetch_explore_post(categoryType='120', count=16)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_trending_post
        # 获取每日热门内容作品数据/Get daily trending video data
        result = await client.tiktok_web.fetch_trending_post()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_trending_searchwords
        # 获取每日趋势搜索关键词/Get daily trending search words
        result = await client.tiktok_web.fetch_trending_searchwords()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_user_profile
        # 获取用户的个人信息/Get user profile
        result = await client.tiktok_web.fetch_user_profile(uniqueId='tiktok', secUid='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_user_post
        # 获取用户的作品列表/Get user posts
        result = await client.tiktok_web.fetch_user_post(secUid='MS4wLjABAAAAv7iSuuXDJGDvJkmH_vz1qkDZYo1apxgzaxdBSeIuPiM', cursor=0, count=20, coverFormat=2, post_item_list_request_type=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_user_repost
        # 获取用户的转发作品列表/Get user reposts
        result = await client.tiktok_web.fetch_user_repost(secUid='MS4wLjABAAAAv7iSuuXDJGDvJkmH_vz1qkDZYo1apxgzaxdBSeIuPiM', cursor=0, count=20, coverFormat=2)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_user_like
        # 获取用户的点赞列表/Get user likes
        result = await client.tiktok_web.fetch_user_like(secUid='MS4wLjABAAAAq1iRXNduFZpY301UkVpJ1eQT60_NiWS9QQSeNqmNQEDJp0pOF8cpleNEdiJx5_IU', cursor=0, count=20, coverFormat=2, post_item_list_request_type=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_user_collect
        # 获取用户的收藏列表/Get user favorites
        result = await client.tiktok_web.fetch_user_collect(cookie='Your_Cookie', secUid='Your_SecUid', cursor=0, count=30, coverFormat=2)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_user_play_list
        # 获取用户的播放列表/Get user play list
        result = await client.tiktok_web.fetch_user_play_list(secUid='MS4wLjABAAAAv7iSuuXDJGDvJkmH_vz1qkDZYo1apxgzaxdBSeIuPiM', cursor=0, count=30)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_user_mix
        # 获取用户的合辑列表/Get user mix list
        result = await client.tiktok_web.fetch_user_mix(mixId='7101538765474106158', cursor=0, count=30)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_post_comment
        # 获取作品的评论列表/Get video comments
        result = await client.tiktok_web.fetch_post_comment(aweme_id='7304809083817774382', cursor=0, count=20, current_region='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_post_comment_reply
        # 获取作品的评论回复列表/Get video comment replies
        result = await client.tiktok_web.fetch_post_comment_reply(item_id='7304809083817774382', comment_id='7304877760886588191', cursor=0, count=20, current_region='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_user_fans
        # 获取用户的粉丝列表/Get user followers
        result = await client.tiktok_web.fetch_user_fans(secUid='MS4wLjABAAAAv7iSuuXDJGDvJkmH_vz1qkDZYo1apxgzaxdBSeIuPiM', count=30, maxCursor=0, minCursor=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_user_follow
        # 获取用户的关注列表/Get user followings
        result = await client.tiktok_web.fetch_user_follow(secUid='MS4wLjABAAAAv7iSuuXDJGDvJkmH_vz1qkDZYo1apxgzaxdBSeIuPiM', count=30, maxCursor=0, minCursor=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_user_live_detail
        # 获取用户的直播详情/Get user live details
        result = await client.tiktok_web.fetch_user_live_detail(uniqueId='tiktok')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_general_search
        # 获取综合搜索列表/Get general search list
        result = await client.tiktok_web.fetch_general_search(keyword='TikTok', offset=0, search_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_search_keyword_suggest
        # 搜索关键字推荐/Search keyword suggest
        result = await client.tiktok_web.fetch_search_keyword_suggest(keyword='TikTok')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_search_user
        # 搜索用户/Search user
        result = await client.tiktok_web.fetch_search_user(keyword='TikTok', cursor=0, search_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_search_video
        # 搜索视频/Search video
        result = await client.tiktok_web.fetch_search_video(keyword='TikTok', count=20, offset=0, search_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_search_live
        # 搜索直播/Search live
        result = await client.tiktok_web.fetch_search_live(keyword='TikTok', count=20, offset=0, search_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_search_photo
        # 搜索照片/Search photo
        result = await client.tiktok_web.fetch_search_photo(keyword='TikTok', count=20, offset=0, search_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_tag_detail
        # Tag详情/Tag Detail
        result = await client.tiktok_web.fetch_tag_detail(tag_name='tiktok')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_tag_post
        # Tag作品/Tag Post
        result = await client.tiktok_web.fetch_tag_post(challengeID='7551', count=30, cursor=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/tiktok/web/fetch_home_feed
        # 首页推荐作品/Home Feed
        result = await client.tiktok_web.fetch_home_feed(count=15)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/generate_real_msToken
        # 生成真实msToken/Generate real msToken
        result = await client.tiktok_web.generate_real_msToken(random_strData=False)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/encrypt_strData
        # 加密strData/Encrypt strData
        result = await client.tiktok_web.encrypt_strData(data='{"behavior":{"beResize":[],"beMotion":[{"ts":1701069187299,"x":null,"y":null,"z":null},{"ts":1701069202902,"x":null,"y":null,"z":null}],"bePaste":[],"beMouse":[],"beKeyboard":[],"beScroll":[],"beTouch":[],"beWheel":[],"windowState":[{"ts":1701069186257,"v":1},{"ts":1701069186257,"v":1},{"ts":1701069186388,"v":2},{"ts":1701069186388,"v":2},{"ts":1701069186402,"v":1},{"ts":1701069186402,"v":1},{"ts":1701069200309,"v":2},{"ts":1701069200309,"v":2},{"ts":1701069201865,"v":1},{"ts":1701069201865,"v":1}],"isTrusted":1},"wID":{"sdkVersion":"4.4.6","scmVersion":"1.0.0.96","msgType":2,"timestamp":"1701069221819","aid":368462,"aidList":[1988,368462],"privacyMode":516},"custom":{},"window":{"location":"https://www.tiktok.com/@funnykittensttk/video/7293517029737352454?is_from_webapp=1&web_id=7260049563725497899"},"msgMeta":{"msgType":2,"msgSrcProp":2,"msgProtocol":1,"aid":368462,"aidList":[1988,368462]}}')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/decrypt_strData
        # 解密strData/Decrypt strData
        result = await client.tiktok_web.decrypt_strData(encrypted_data='3BvqYbNXLLOcZehvxZVbjpAu7vq82RoWmFSJHLFwzDwJIZevE0AeilQfP55LridxmdGGjknoksqIsLqlMHMif0IFK/Br7JWqxOHnYuMwVCnttFc0Y4MFvdVWM5FECiEulJC0Dc+eeVsNSrFnAc9K7fazqdglyJgGLSfXIJmgyCvvQ4pg0u5HBVVugLSWs242X42fjoWymaUCLZJQo6vi6WLyuV7l5IC3Mg+lelr5xBQD6Q7hBIFEw8zzxJ1n2DyA4xLbOHTQdKvEtsK7XzyWwjpRnojPTbBl69Zosnuru+lOBIl+tFu/+hCQ1m0jYZwTP4rVE75L3Du6+KZ5v/9TyFYjq7y3y9bGLP4d7yQueJbF90G1yrZ6htElrZ2vqZKDrIqBVbmOZr/nph12k2JKrITtN0R/pMsp0sJ4gesQnXxcD/pLOFAINHk7umgbe6LzJ7+TLUdGuO4M7xiEg/jCqhjgJX1izZ4NPoBDp35zRxj6Y6OrcstlTN/cv5sz663+Nco/mEwhGq2VwrL4gAIAPycndIsb48dPdtngmLqNDNN0ZyVRjgqVIDXXrxigXCkR9CH89Dlrrb7QQqWVgRXz9/k5ihEM43BR3sd3mMU/XgFLN1Aoxf6GzzdxP2QPBI75/ZoHoAmu54v8gTmA3ntCGlEF0zgaFGTdpkGdb+oZgyQM4pw1aAyxmFINXkpD3IKKoGev9kD9gTFnhiQMGCMemhZS7ZYdbuGu0Cb+lQKaL/QTt80FMyGmW8kzVy9xW/ja9BcdEJYRoaufuFRkBFG5ay8x4WHLR6hEapXqQial/cREbLL4sQytpjtmnndFqvT7xN5DhgsLY2Z7451MJhD6NJXKNrMafGZSbItzQWY=')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/generate_fingerprint
        # 生成浏览器指纹/Generate browser fingerprint
        result = await client.tiktok_web.generate_fingerprint()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/generate_webid
        # 生成web_id/Generate web_id
        result = await client.tiktok_web.generate_webid(user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:145.0) Gecko/20100101 Firefox/145.0', url='https://www.tiktok.com/explore', referer='', user_unique_id='', app_id=1988)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/generate_ttwid
        # 生成ttwid/Generate ttwid
        result = await client.tiktok_web.generate_ttwid(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/tiktok/web/generate_xbogus
        # 生成 XBogus/Generate XBogus
        result = await client.tiktok_web.generate_xbogus(url='https://www.douyin.com/aweme/v1/web/aweme/detail/?aweme_id=7148736076176215311&device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=170400&version_name=17.4.0&cookie_enabled=true&screen_width=1920&screen_height=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Edge&browser_version=117.0.2045.47&browser_online=true&engine_name=Blink&engine_version=117.0.0.0&os_name=Windows&os_version=10&cpu_core_num=128&device_memory=10240&platform=PC&downlink=10&effective_type=4g&round_trip_time=100', user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/tiktok/web/generate_xgnarly
        # 生成 XGnarly /Generate XGnarly
        result = await client.tiktok_web.generate_xgnarly(url='https://www.tiktok.com/api/search/user/full/?WebIdLastTime=1756087650&aid=1988&app_language=zh-Hans&app_name=tiktok_web&browser_language=zh-CN&browser_name=Mozilla&browser_online=true&browser_platform=MacIntel&browser_version=5.0%20%28Macintosh%3B%20Intel%20Mac%20OS%20X%2010_15_7%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F139.0.0.0%20Safari%2F537.36&channel=tiktok_web&cookie_enabled=true&cursor=10&data_collection_enabled=false&device_id=7542339104672111234&device_platform=web_pc&focus_state=true&from_page=search&history_len=3&is_fullscreen=true&is_page_visible=true&keyword=musk&odinId=7542338997269211234&os=mac&priority_region&referer&region=US&screen_height=967&screen_width=1496&search_id&tz_name=America%2FLos_Angeles&user_is_login=false&web_search_code=%7B%22tiktok%22%3A%7B%22client_params_x%22%3A%7B%22search_engine%22%3A%7B%22ies_mt_user_live_video_card_use_libra%22%3A1%2C%22mt_search_general_user_live_card%22%3A1%7D%7D%2C%22search_server%22%3A%7B%7D%7D%7D&webcast_language=zh-Hans', body='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/tiktok/web/generate_xgnarly_and_xbogus
        # 生成 XGnarly 和 XBogus /Generate XGnarly and XBogus
        result = await client.tiktok_web.generate_xgnarly_and_xbogus(url='https://www.tiktok.com/api/search/user/full/?WebIdLastTime=1756087650&aid=1988&app_language=zh-Hans&app_name=tiktok_web&browser_language=zh-CN&browser_name=Mozilla&browser_online=true&browser_platform=MacIntel&browser_version=5.0%20%28Macintosh%3B%20Intel%20Mac%20OS%20X%2010_15_7%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F139.0.0.0%20Safari%2F537.36&channel=tiktok_web&cookie_enabled=true&cursor=10&data_collection_enabled=false&device_id=7542339104672111234&device_platform=web_pc&focus_state=true&from_page=search&history_len=3&is_fullscreen=true&is_page_visible=true&keyword=musk&odinId=7542338997269211234&os=mac&priority_region&referer&region=US&screen_height=967&screen_width=1496&search_id&tz_name=America%2FLos_Angeles&user_is_login=false&web_search_code=%7B%22tiktok%22%3A%7B%22client_params_x%22%3A%7B%22search_engine%22%3A%7B%22ies_mt_user_live_video_card_use_libra%22%3A1%2C%22mt_search_general_user_live_card%22%3A1%7D%7D%2C%22search_server%22%3A%7B%7D%7D%7D&webcast_language=zh-Hans', body='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/tiktok/web/generate_x_mssdk_info
        # 生成 X-Mssdk-Info /Generate X-Mssdk-Info
        result = await client.tiktok_web.generate_x_mssdk_info()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/get_user_id
        # 提取用户user_id/Extract user user_id
        result = await client.tiktok_web.get_user_id(url='https://www.tiktok.com/@tiktok')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/get_sec_user_id
        # 提取用户sec_user_id/Extract user sec_user_id
        result = await client.tiktok_web.get_sec_user_id(url='https://www.tiktok.com/@tiktok')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/tiktok/web/get_all_sec_user_id
        # 提取列表用户sec_user_id/Extract list user sec_user_id
        result = await client.tiktok_web.get_all_sec_user_id(body=[])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/get_aweme_id
        # 提取单个作品id/Extract single video id
        result = await client.tiktok_web.get_aweme_id(url='https://www.tiktok.com/@owlcitymusic/video/7218694761253735723')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/tiktok/web/get_all_aweme_id
        # 提取列表作品id/Extract list video id
        result = await client.tiktok_web.get_all_aweme_id(body=[])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/get_unique_id
        # 获取用户unique_id/Get user unique_id
        result = await client.tiktok_web.get_unique_id(url='https://www.tiktok.com/@tiktok')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/tiktok/web/get_all_unique_id
        # 获取列表unique_id/Get list unique_id
        result = await client.tiktok_web.get_all_unique_id(body=[])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/tiktok_live_room
        # 提取直播间弹幕/Extract live room danmaku
        result = await client.tiktok_web.tiktok_live_room(live_room_url='https://www.tiktok.com/@mpl.id.official/live', danmaku_type='WebcastChatMessage')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_live_im_fetch
        # TikTok直播间弹幕参数获取/tiktok live room danmaku parameters
        result = await client.tiktok_web.fetch_live_im_fetch(room_id='7382517534467115826', user_unique_id='7382524529011246630', resp_content_type='protobuf')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/generate_wss_xb_signature
        # 生成TikTok WSS X-Bogus签名/Generate TikTok WSS X-Bogus signature
        result = await client.tiktok_web.generate_wss_xb_signature(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 Edg/143.0.0.0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/get_live_room_id
        # 根据直播间链接提取直播间ID/Extract live room ID from live room link
        result = await client.tiktok_web.get_live_room_id(live_room_url='https://www.tiktok.com/@maksukaracun/live')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_check_live_alive
        # 直播间开播状态检测/Live room start status check
        result = await client.tiktok_web.fetch_check_live_alive(room_id='7381444193462078214')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_batch_check_live_alive
        # 批量直播间开播状态检测/Batch live room start status check
        result = await client.tiktok_web.fetch_batch_check_live_alive(room_ids='7530611486784277278,7530633767468288782,7530636465034775310,7530604930088848142')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_tiktok_live_data
        # 通过直播链接获取直播间信息/Get live room information via live link
        result = await client.tiktok_web.fetch_tiktok_live_data(live_room_url='https://www.tiktok.com/@.caseoh_daily/live')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_live_recommend
        # 获取直播间首页推荐列表/Get live room homepage recommendation list
        result = await client.tiktok_web.fetch_live_recommend(related_live_tag='VALORANT')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_live_gift_list
        # 获取直播间礼物列表/Get live room gift list
        result = await client.tiktok_web.fetch_live_gift_list(room_id='7381444193462078214')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_sso_login_qrcode
        # 获取SSO登录二维码/Get SSO login QR code
        result = await client.tiktok_web.fetch_sso_login_qrcode(device_id='7481276116461831688', region='US', proxy='None')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_sso_login_status
        # 获取SSO登录状态/Get SSO login status
        result = await client.tiktok_web.fetch_sso_login_status(token='jiHRabSoJdwNrsvJvlRKj4hecTstR2xsn2NmtmKMN8o=_useast5', device_id='7481276116461831688', verifyFp='verify_m8909xlr_d7UEdRqf_mA73_4So4_B0RT_L1gFyzsKr7IL', region='US', proxy='None')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_sso_login_auth
        # 认证SSO登录/Authenticate SSO login
        result = await client.tiktok_web.fetch_sso_login_auth(device_id='7481276116461831688', verifyFp='verify_m8909xlr_d7UEdRqf_mA73_4So4_B0RT_L1gFyzsKr7IL', region='US', proxy='None')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/generate_hashed_id
        # 生成哈希ID/Generate hashed ID
        result = await client.tiktok_web.generate_hashed_id(email='test@example.com')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/tiktok/web/fetch_gift_name_by_id
        # 根据Gift ID查询礼物名称/Get gift name by gift ID
        result = await client.tiktok_web.fetch_gift_name_by_id(gift_id='10001')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/tiktok/web/fetch_gift_names_by_ids
        # 批量查询Gift ID对应的礼物名称($0.025/次,建议50个)/Batch get gift names by gift IDs ($0.025/call, suggest 50)
        result = await client.tiktok_web.fetch_gift_names_by_ids(gift_ids=['10001', '10002', '10003'])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/fetch_tiktok_web_guest_cookie
        # 获取游客 Cookie/Get the guest Cookie
        result = await client.tiktok_web.fetch_tiktok_web_guest_cookie(user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/web/device_register
        # 设备注册/Register device for TikTok Web
        result = await client.tiktok_web.device_register()
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
