"""Example: WeChat-Media-Platform-Web-API

SDK attribute: ``client.wechat_media_platform_web``
Endpoints: 12

Usage::

    python examples/wechat_media_platform_web.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/wechat_mp/web/fetch_mp_article_detail_json
        # 获取微信公众号文章详情的JSON/Get Wechat MP Article Detail JSON
        result = await client.wechat_media_platform_web.fetch_mp_article_detail_json(url='https://mp.weixin.qq.com/s/TSNQKkRpN1qbKsT7BvzqIw')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_mp_article_detail_html
        # 获取微信公众号文章详情的HTML/Get Wechat MP Article Detail HTML
        result = await client.wechat_media_platform_web.fetch_mp_article_detail_html(url='https://mp.weixin.qq.com/s/TSNQKkRpN1qbKsT7BvzqIw')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_mp_article_list
        # 获取微信公众号文章列表/Get Wechat MP Article List
        result = await client.wechat_media_platform_web.fetch_mp_article_list(ghid='gh_a3d35d4c9d3f', offset='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_mp_article_read_count
        # 获取微信公众号文章阅读量/Get Wechat MP Article Read Count
        result = await client.wechat_media_platform_web.fetch_mp_article_read_count(url='https://mp.weixin.qq.com/s/hrTDuwh0pWyJFYC93kKCrg', comment_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_mp_article_url
        # 获取微信公众号文章永久链接/Get Wechat MP Article URL
        result = await client.wechat_media_platform_web.fetch_mp_article_url(sogou_url='https://weixin.sogou.com/link?url=dn9a_-gY295K0Rci_xozVXfdMkSQTLW6cwJThYulHEtVjXrGTiVgS5mzcw64XRlRaPIdMgILsPEBI9djq3byAlqXa8Fplpd9bV3r44ewJj5IFttt-prmTSHShu8JtNlpDYR_z_1xvD2J_XrGTUriRYOOY2mt9pZSIUQEepUVTybxAOW4P5fEPd23R0CgK6W3KEODtIkcv1U5w5VkZ8a7_lyyAqreiCgr1YH9mz_7mzFDl6rX6ZnkVYNsUHV_OmaXBUCqpZ1Pa6YO8fIRwtipOg..&type=2&query=deepseek&token=C2E90D2050EB6EA5C2C4EDB1541D855FC322013E67C5DC5A&k=4&h=k')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_mp_article_comment_list
        # 获取微信公众号文章评论列表/Get Wechat MP Article Comment List
        result = await client.wechat_media_platform_web.fetch_mp_article_comment_list(url='https://mp.weixin.qq.com/s/Iv-xRzL7WzbL0dUUIgi3Nw', comment_id='', buffer='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_mp_article_comment_reply_list
        # 获取微信公众号文章评论回复列表/Get Wechat MP Article Comment Reply List
        result = await client.wechat_media_platform_web.fetch_mp_article_comment_reply_list(url='https://mp.weixin.qq.com/s/Ko5V9jw9kwL8TO6Q7J3UqQ', comment_id='3601466901697855492', content_id='6387234930341970671', offset='0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_mp_article_ad
        # 获取微信公众号广告/Get Wechat MP Article Ad
        result = await client.wechat_media_platform_web.fetch_mp_article_ad(url='https://mp.weixin.qq.com/s/hrTDuwh0pWyJFYC93kKCrg')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_mp_article_url_conversion
        # 获取微信公众号长链接转短链接/Get Wechat MP Long URL to Short URL
        result = await client.wechat_media_platform_web.fetch_mp_article_url_conversion(url='http://mp.weixin.qq.com/s?__biz=MzIyMDQzMTM4Mg==&mid=2247504868&idx=1&sn=37ee48875df1be54cb766783177ce61d')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_mp_related_articles
        # 获取微信公众号关联文章/Get Wechat MP Related Articles
        result = await client.wechat_media_platform_web.fetch_mp_related_articles(url='https://mp.weixin.qq.com/s/Ko5V9jw9kwL8TO6Q7J3UqQ')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_search_official_account
        # 搜索微信公众号/Search Wechat Official Account
        result = await client.wechat_media_platform_web.fetch_search_official_account(keyword='人民日报', offset=0, sort_type='_0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/wechat_mp/web/fetch_search_article
        # 搜索微信公众号文章/Search Wechat MP Article
        result = await client.wechat_media_platform_web.fetch_search_article(keyword='人工智能', offset=0, sort_type='_0')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
