"""Example: Xiaohongshu-Web-API

SDK attribute: ``client.xiaohongshu_web``
Endpoints: 15

Usage::

    python examples/xiaohongshu_web.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # POST /api/v1/xiaohongshu/web/get_home_recommend
        # 获取首页推荐/Get home recommend
        result = await client.xiaohongshu_web.get_home_recommend(feed_type='0', need_filter_image=False, cursor_score='', cookie='', proxy='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/get_note_info_v4
        # 获取笔记信息 V4/Get note info V4
        result = await client.xiaohongshu_web.get_note_info_v4(note_id='665f95200000000006005624', share_text='https://xhslink.com/a/EZ4M9TwMA6c3')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/xiaohongshu/web/get_note_info_v5
        # 获取笔记信息 V5 (自带Cookie)/Get note info V5 (Self-provided Cookie)
        result = await client.xiaohongshu_web.get_note_info_v5(note_id='67855d09000000001703d449', xsec_token='ABfpRSESmZDRbX-EX7lzEztktMngxPVC9kU-dgQmuQoNo=', cookie='', proxy='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/get_note_info_v7
        # 获取笔记信息 V7/Get note info V7
        result = await client.xiaohongshu_web.get_note_info_v7(note_id='665f95200000000006005624', share_text='https://xhslink.com/a/EZ4M9TwMA6c3')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/get_note_comments
        # 获取笔记评论 V1/Get note comments V1
        result = await client.xiaohongshu_web.get_note_comments(note_id='6683b283000000001f0052bf')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/get_note_comment_replies
        # 获取笔记评论回复 V1/Get note comment replies V1
        result = await client.xiaohongshu_web.get_note_comment_replies(note_id='6683b283000000001f0052bf', comment_id='6683ec5b000000000303b91a')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/get_user_info
        # 获取用户信息 V1/Get user info V1
        result = await client.xiaohongshu_web.get_user_info(user_id='5f4a10070000000001006fc7')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/search_notes
        # 搜索笔记/Search notes
        result = await client.xiaohongshu_web.search_notes(keyword='美食', page=1, sort='general', noteType='_0', noteTime='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/search_notes_v3
        # 搜索笔记 V3/Search notes V3
        result = await client.xiaohongshu_web.search_notes_v3(keyword='美食', page=1, sort='general', noteType='_0', noteTime='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/search_users
        # 搜索用户/Search users
        result = await client.xiaohongshu_web.search_users(keyword='美食', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/get_user_notes_v2
        # 获取用户的笔记 V2/Get user notes V2
        result = await client.xiaohongshu_web.get_user_notes_v2(user_id='5f4a10070000000001006fc7')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/get_visitor_cookie
        # 获取游客Cookie/Get visitor cookie
        result = await client.xiaohongshu_web.get_visitor_cookie(proxy='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/xiaohongshu/web/sign
        # 小红书Web签名/Xiaohongshu Web sign
        result = await client.xiaohongshu_web.sign(path='/api/sns/web/v1/homefeed', data={'cursor_score': '', 'num': 35, 'refresh_type': 1, 'note_index': 35, 'unread_begin_note_id': '', 'unread_end_note_id': '', 'unread_note_count': 0, 'category': 'homefeed_recommend', 'search_key': '', 'need_num': 10, 'image_formats': ['jpg', 'webp', 'avif'], 'need_filter_image': False}, cookie='web_session=030037a04eafd37791e6e4bd05204a8cf2af05;acw_tc=0a00d79f17363096679345838efb77751cc087fb039dd1691dc954824410f6;abRequestId=384480ae-5196-5818-a835-42e6278de9f0;webBuild=4.47.1;xsecappid=xhs-pc-web;a1=194441ef694PayUbdUvgp0dSHfIcACsNsLud0Lgru50000354513;webId=6cf10a564b9b07d129729b65e0d1785a;sec_poison_id=32964532-d414-4beb-914f-98811853b75f')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/get_note_id_and_xsec_token
        # 通过分享链接获取小红书的Note ID 和 xsec_token/Get Xiaohongshu Note ID and xsec_token by share link
        result = await client.xiaohongshu_web.get_note_id_and_xsec_token(share_text='https://xhslink.com/a/EZ4M9TwMA6c3')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web/get_product_info
        # 获取小红书商品信息/Get Xiaohongshu product info
        result = await client.xiaohongshu_web.get_product_info(share_text='', item_id='65fc2e6d6b92310001d24efb', xsec_token='XBC6LTqeaEDeJETMoXo436Eg-74GxFemVnNHeONYobv7k=')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
