"""Example: Xiaohongshu-Web-V3-API

SDK attribute: ``client.xiaohongshu_web_v3``
Endpoints: 11

Usage::

    python examples/xiaohongshu_web_v3.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/xiaohongshu/web_v3/fetch_note_detail
        # 获取笔记详情/Fetch note detail
        result = await client.xiaohongshu_web_v3.fetch_note_detail(note_id='697ee7f5000000001a0225c1', xsec_token='ABkR6BvFSbUES4IbFcbjZrtCRa3FSqpqsa1KjFLyurW8U=')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_note_comments
        # 获取笔记评论/Fetch note comments
        result = await client.xiaohongshu_web_v3.fetch_note_comments(note_id='69f0817d000000002301ca13', cursor='', xsec_token='ABkUO3R6tKvwMzj0Y3pFBbab4YWPXwLhp7gfbNpfYY8Bg=')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_sub_comments
        # 获取子评论/Fetch sub comments
        result = await client.xiaohongshu_web_v3.fetch_sub_comments(note_id='69f08d5f00000000350397ba', root_comment_id='69f09736000000002803832e', num=10, cursor='', xsec_token='ABkUO3R6tKvwMzj0Y3pFBbaUK6gBt3Yj1Br95ogIzuXyI=')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_search_notes
        # 搜索笔记/Search notes
        result = await client.xiaohongshu_web_v3.fetch_search_notes(keyword='口红', page=1, sort='general', note_type=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_search_users
        # 搜索用户/Search users
        result = await client.xiaohongshu_web_v3.fetch_search_users(keyword='口红', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_trending
        # 获取热搜词/Fetch trending keywords
        result = await client.xiaohongshu_web_v3.fetch_trending()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_search_suggest
        # 获取搜索联想词/Fetch search suggestions
        result = await client.xiaohongshu_web_v3.fetch_search_suggest(keyword='口红')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_homefeed
        # 获取首页推荐/Fetch homepage feed
        result = await client.xiaohongshu_web_v3.fetch_homefeed(num=20, cursor_score='', category='homefeed_recommend', need_filter_image=False)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_homefeed_categories
        # 获取首页分类列表/Fetch homepage categories
        result = await client.xiaohongshu_web_v3.fetch_homefeed_categories()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_user_info
        # 获取用户信息/Fetch user info
        result = await client.xiaohongshu_web_v3.fetch_user_info(user_id='5e3a8ee700000000010070c6')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_user_notes
        # 获取用户笔记列表/Fetch user notes
        result = await client.xiaohongshu_web_v3.fetch_user_notes(user_id='5e3a8ee700000000010070c6', cursor='', num=30)
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
