"""Example: Xiaohongshu-Web-V2-API

SDK attribute: ``client.xiaohongshu_web_v2``
Endpoints: 7

Usage::

    python examples/xiaohongshu_web_v2.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/xiaohongshu/web_v2/fetch_feed_notes
        # 获取图文笔记详情 V1/Get image note detail V1
        result = await client.xiaohongshu_web_v2.fetch_feed_notes(note_id='66c9cc31000000001f03a4bc', share_text='http://xhslink.com/o/8GqargIxrko')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v2/fetch_feed_notes_v2
        # 获取图文笔记详情 V2/Get image note detail V2
        result = await client.xiaohongshu_web_v2.fetch_feed_notes_v2(note_id='66c9cc31000000001f03a4bc', share_text='http://xhslink.com/o/8GqargIxrko')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v2/fetch_home_notes_app
        # 获取用户笔记/Fetch user notes
        result = await client.xiaohongshu_web_v2.fetch_home_notes_app(user_id='63f63efb000000001001dd4f', cursor='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v2/fetch_note_comments
        # 获取笔记评论/Fetch note comments
        result = await client.xiaohongshu_web_v2.fetch_note_comments(note_id='651ccaa9000000001f03d7f7', cursor='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v2/fetch_sub_comments
        # 获取子评论/Fetch sub comments
        result = await client.xiaohongshu_web_v2.fetch_sub_comments(note_id='673c894c0000000007033f92', comment_id='673ecdfc000000001503bf8b', cursor='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v2/fetch_user_info_app
        # 获取App用户信息/Fetch App user info
        result = await client.xiaohongshu_web_v2.fetch_user_info_app(user_id='5e3a8ee700000000010070c6')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v2/fetch_hot_list
        # 获取小红书热榜/Fetch Xiaohongshu hot list
        result = await client.xiaohongshu_web_v2.fetch_hot_list()
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
