"""Example: Xiaohongshu-App-V2-API

SDK attribute: ``client.xiaohongshu_app_v2``
Endpoints: 20

Usage::

    python examples/xiaohongshu_app_v2.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/xiaohongshu/app_v2/get_image_note_detail
        # 获取图文笔记详情/Get image note detail
        result = await client.xiaohongshu_app_v2.get_image_note_detail(note_id='697c0eee000000000a03c308', share_text='http://xhslink.com/o/8GqargIxrko')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_video_note_detail
        # 获取视频笔记详情/Get video note detail
        result = await client.xiaohongshu_app_v2.get_video_note_detail(note_id='697c0eee000000000a03c308', share_text='http://xhslink.com/o/8GqargIxrko')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_note_comments
        # 获取笔记评论列表/Get note comments
        result = await client.xiaohongshu_app_v2.get_note_comments(note_id='697c0eee000000000a03c308', share_text='http://xhslink.com/o/8GqargIxrko', cursor='', index=0, pageArea='UNFOLDED', sort_strategy='latest_v2')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_note_sub_comments
        # 获取笔记二级评论列表/Get note sub comments
        result = await client.xiaohongshu_app_v2.get_note_sub_comments(note_id='699916e6000000001d0253da', share_text='http://xhslink.com/o/8GqargIxrko', comment_id='699fb9930000000008030db6', cursor='', index=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_user_info
        # 获取用户信息/Get user info
        result = await client.xiaohongshu_app_v2.get_user_info(user_id='61b46d790000000010008153', share_text='https://xhslink.com/m/3ZSCJZAMz0a')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_user_posted_notes
        # 获取用户笔记列表/Get user posted notes
        result = await client.xiaohongshu_app_v2.get_user_posted_notes(user_id='61b46d790000000010008153', share_text='http://xhslink.com/o/8GqargIxrko', cursor='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_user_faved_notes
        # 获取用户收藏笔记列表/Get user faved notes
        result = await client.xiaohongshu_app_v2.get_user_faved_notes(user_id='5a8cf39111be10466d285d6b', share_text='https://xhslink.com/a/EZ4M9TwMA6c3', cursor='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/search_notes
        # 搜索笔记/Search notes
        result = await client.xiaohongshu_app_v2.search_notes(keyword='美食推荐', page=1, sort_type='general', note_type='不限', time_filter='不限', search_id='', search_session_id='', source='explore_feed', ai_mode=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/search_users
        # 搜索用户/Search users
        result = await client.xiaohongshu_app_v2.search_users(keyword='美食博主', page=1, search_id='', source='explore_feed')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/search_images
        # 搜索图片/Search images
        result = await client.xiaohongshu_app_v2.search_images(keyword='壁纸', page=1, search_id='', search_session_id='', word_request_id='', source='explore_feed')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/search_products
        # 搜索商品/Search products
        result = await client.xiaohongshu_app_v2.search_products(keyword='手机壳', page=1, search_id='', source='explore_feed')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/search_groups
        # 搜索群聊/Search groups
        result = await client.xiaohongshu_app_v2.search_groups(keyword='上海', page_no=0, search_id='', source='unifiedSearchGroup', is_recommend=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_product_detail
        # 获取商品详情/Get product detail
        result = await client.xiaohongshu_app_v2.get_product_detail(sku_id='669ddd44e05f3700011067ed', source='mall_search', pre_page='mall_search')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_product_review_overview
        # 获取商品评论总览/Get product review overview
        result = await client.xiaohongshu_app_v2.get_product_review_overview(sku_id='669ddd44e05f3700011067ed', tab=2)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_product_reviews
        # 获取商品评论列表/Get product reviews
        result = await client.xiaohongshu_app_v2.get_product_reviews(sku_id='669ddd44e05f3700011067ed', page=0, sort_strategy_type=0, share_pics_only=0, from_page='score_page')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_product_recommendations
        # 获取商品推荐列表/Get product recommendations
        result = await client.xiaohongshu_app_v2.get_product_recommendations(sku_id='669ddd44e05f3700011067ed', cursor_score='', region='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_topic_info
        # 获取话题详情/Get topic info
        result = await client.xiaohongshu_app_v2.get_topic_info(page_id='5c1cc866febed9000184b7c1', source='normal', note_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_topic_feed
        # 获取话题笔记列表/Get topic feed
        result = await client.xiaohongshu_app_v2.get_topic_feed(page_id='5c1cc866febed9000184b7c1', sort='trend', cursor_score='', last_note_id='', last_note_ct='', session_id='', first_load_time='', source='normal')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_creator_inspiration_feed
        # 获取创作者推荐灵感列表/Get creator inspiration feed
        result = await client.xiaohongshu_app_v2.get_creator_inspiration_feed(cursor='', tab=0, source='creator_center')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/app_v2/get_creator_hot_inspiration_feed
        # 获取创作者热点灵感列表/Get creator hot inspiration feed
        result = await client.xiaohongshu_app_v2.get_creator_hot_inspiration_feed(cursor='')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
