"""Example: YouTube-Web-V2-API

SDK attribute: ``client.youtube_web_v2``
Endpoints: 25

Usage::

    python examples/youtube_web_v2.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/youtube/web_v2/get_video_info
        # 获取视频详情 /Get video information
        result = await client.youtube_web_v2.get_video_info(video_id='oaSNBz4qMQY', language_code='zh-CN', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_video_info_v2
        # 获取视频详情 V2/Get video information V2
        result = await client.youtube_web_v2.get_video_info_v2(video_id='dQw4w9WgXcQ', video_url='https://www.youtube.com/watch?v=dQw4w9WgXcQ', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_video_comments
        # 获取视频评论/Get video comments
        result = await client.youtube_web_v2.get_video_comments(video_id='LuIL5JATZsc', language_code='zh-CN', country_code='US', sort_by='top', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_video_comment_replies
        # 获取视频二级评论/Get video sub comments
        result = await client.youtube_web_v2.get_video_comment_replies(continuation_token='test', language_code='zh-CN', country_code='US', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_channel_description
        # 获取频道描述信息/Get channel description
        result = await client.youtube_web_v2.get_channel_description(channel_id='UCeu6U67OzJhV1KwBansH3Dg', language_code='zh-CN', country_code='US', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_general_search
        # 综合搜索（原始数据，推荐使用V2）/General search (raw data, recommend V2)
        result = await client.youtube_web_v2.get_general_search(search_query='Python编程', language_code='zh-CN', country_code='US', time_zone='America/Los_Angeles')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_general_search_v2
        # 综合搜索V2/General search V2
        result = await client.youtube_web_v2.get_general_search_v2(keyword='Python tutorial')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_shorts_search
        # Shorts搜索（原始数据，推荐使用V2）/Shorts search (raw data, recommend V2)
        result = await client.youtube_web_v2.get_shorts_search(search_query='Python编程', language_code='en-US', country_code='US', time_zone='America/Los_Angeles', continuation_token='', filter_mixed_content=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_shorts_search_v2
        # Shorts搜索V2/Shorts search V2
        result = await client.youtube_web_v2.get_shorts_search_v2(keyword='coding tips')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_channel_id
        # 从频道URL获取频道ID /Get channel ID from URL
        result = await client.youtube_web_v2.get_channel_id(channel_url='https://www.youtube.com/@CozyCraftYT')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_channel_url
        # 从频道ID获取频道URL/Get channel URL from channel ID
        result = await client.youtube_web_v2.get_channel_url(channel_id='UCeu6U67OzJhV1KwBansH3Dg')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_channel_videos
        # 获取频道视频 /Get channel videos
        result = await client.youtube_web_v2.get_channel_videos(channel_id='UCJHBJ7F-nAIlMGolm0Hu4vg', language_code='zh-CN', country_code='US', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_video_streams
        # 获取视频流信息/Get video streams info
        result = await client.youtube_web_v2.get_video_streams(video_id='dQw4w9WgXcQ', video_url='https://www.youtube.com/watch?v=dQw4w9WgXcQ')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_video_streams_v2
        # 获取视频流信息 V2/Get video streams info V2
        result = await client.youtube_web_v2.get_video_streams_v2(video_id='dQw4w9WgXcQ', video_url='https://www.youtube.com/watch?v=dQw4w9WgXcQ')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_signed_stream_url
        # 获取已签名的视频流URL/Get signed video stream URL
        result = await client.youtube_web_v2.get_signed_stream_url(video_id='dQw4w9WgXcQ', video_url='https://www.youtube.com/watch?v=dQw4w9WgXcQ', itag=18)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_video_captions
        # 获取视频字幕/Get video captions
        result = await client.youtube_web_v2.get_video_captions(video_id='dQw4w9WgXcQ', video_url='https://www.youtube.com/watch?v=dQw4w9WgXcQ', language_code='en', format='srt')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_video_captions_v2
        # 获取视频字幕 V2/Get video captions V2
        result = await client.youtube_web_v2.get_video_captions_v2(video_id='MWvpXswLFxA', video_url='https://www.youtube.com/watch?v=MWvpXswLFxA', language_code='en', format='srt')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_related_videos
        # 获取视频相似内容/Get related videos
        result = await client.youtube_web_v2.get_related_videos(video_id='dQw4w9WgXcQ', video_url='https://www.youtube.com/watch?v=dQw4w9WgXcQ', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_channel_shorts
        # 获取频道短视频列表/Get channel shorts
        result = await client.youtube_web_v2.get_channel_shorts(channel_id='UCuAXFkgsw1L7xaCfnd5JJOw', channel_url='https://www.youtube.com/channel/UCuAXFkgsw1L7xaCfnd5JJOw', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_search_suggestions
        # 获取搜索推荐词/Get search suggestions
        result = await client.youtube_web_v2.get_search_suggestions(keyword='Rick Astley', language='en', region='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/search_channels
        # 搜索频道/Search channels
        result = await client.youtube_web_v2.search_channels(keyword='Rick Astley', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_channel_community_posts
        # 获取频道帖子列表/Get channel community posts
        result = await client.youtube_web_v2.get_channel_community_posts(channel_id='UCkRfArvrzheW2E7b6SVT7vQ', language_code='zh-CN', country_code='US', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_post_detail
        # 获取帖子详情/Get post detail
        result = await client.youtube_web_v2.get_post_detail(post_id='UgkxiCSRfD6g7SPlWGPDa3vbP7aIsytXRkvy', language_code='zh-CN', country_code='US', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_post_comments
        # 获取帖子评论/Get post comments
        result = await client.youtube_web_v2.get_post_comments(post_id='UgkxiCSRfD6g7SPlWGPDa3vbP7aIsytXRkvy', language_code='zh-CN', country_code='US', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/youtube/web_v2/get_post_comment_replies
        # 获取帖子评论回复/Get post comment replies
        result = await client.youtube_web_v2.get_post_comment_replies(continuation_token='test', language_code='zh-CN', country_code='US', need_format=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
